// Generated by scripts/i18n_build.mjs. Do not edit by hand.
//
// Part of the generated src/ui/i18n.resolved.generated/ directory: one dense
// locale slice per file (each `: EnTranslations` = typeof en, so tsc red-fails a
// missing or renamed key), a back-compat barrel (index.ts) that re-exports every
// slice and assembles the runtime `translations` map, per-locale lazy loaders
// (loaders.ts), and the pending set (pending.ts). Regenerate with
// `npm run i18n:build` (also wired into `npm run build` and `pretest`).
// Reproducibility is checked by tests/i18n_resolved_equivalence.test.ts.

import { en } from './en';
import { es } from './es';
import { es_ES } from './es_ES';
import { fr_FR } from './fr_FR';
import { fr_CA } from './fr_CA';
import { en_CA } from './en_CA';
import { it_IT } from './it_IT';
import { de_DE } from './de_DE';
import { zh_CN } from './zh_CN';
import { zh_TW } from './zh_TW';
import { ko_KR } from './ko_KR';
import { ja_JP } from './ja_JP';
import { pt_BR } from './pt_BR';
import { ru_RU } from './ru_RU';
import { cs_CZ } from './cs_CZ';
import { nl_NL } from './nl_NL';
import { pl_PL } from './pl_PL';
import { id_ID } from './id_ID';
import { tr_TR } from './tr_TR';
import { sv_SE } from './sv_SE';
import { vi_VN } from './vi_VN';
import { da_DK } from './da_DK';

export { en, es, es_ES, fr_FR, fr_CA, en_CA, it_IT, de_DE, zh_CN, zh_TW, ko_KR, ja_JP, pt_BR, ru_RU, cs_CZ, nl_NL, pl_PL, id_ID, tr_TR, sv_SE, vi_VN, da_DK };
export { en_XA } from './en_XA';
export { pending } from './pending';

export const translations = {
  en,
  es,
  es_ES,
  fr_FR,
  fr_CA,
  en_CA,
  it_IT,
  de_DE,
  zh_CN,
  zh_TW,
  ko_KR,
  ja_JP,
  pt_BR,
  ru_RU,
  cs_CZ,
  nl_NL,
  pl_PL,
  id_ID,
  tr_TR,
  sv_SE,
  vi_VN,
  da_DK,
};
