// Generated by scripts/i18n_build.mjs. Do not edit by hand.
//
// Part of the generated src/ui/i18n.resolved.generated/ directory: one dense
// locale slice per file (each `: EnTranslations` = typeof en, so tsc red-fails a
// missing or renamed key), a back-compat barrel (index.ts) that re-exports every
// slice and assembles the runtime `translations` map, per-locale lazy loaders
// (loaders.ts), and the pending set (pending.ts). Regenerate with
// `npm run i18n:build` (also wired into `npm run build` and `pretest`).
// Reproducibility is checked by tests/i18n_resolved_equivalence.test.ts.

export const LOCALE_LOADERS = {
  es: () => import('./es'),
  es_ES: () => import('./es_ES'),
  fr_FR: () => import('./fr_FR'),
  fr_CA: () => import('./fr_CA'),
  en_CA: () => import('./en_CA'),
  it_IT: () => import('./it_IT'),
  de_DE: () => import('./de_DE'),
  zh_CN: () => import('./zh_CN'),
  zh_TW: () => import('./zh_TW'),
  ko_KR: () => import('./ko_KR'),
  ja_JP: () => import('./ja_JP'),
  pt_BR: () => import('./pt_BR'),
  ru_RU: () => import('./ru_RU'),
  cs_CZ: () => import('./cs_CZ'),
  nl_NL: () => import('./nl_NL'),
  pl_PL: () => import('./pl_PL'),
  id_ID: () => import('./id_ID'),
  tr_TR: () => import('./tr_TR'),
  sv_SE: () => import('./sv_SE'),
  vi_VN: () => import('./vi_VN'),
  da_DK: () => import('./da_DK'),
};

export const SUPPORTED_LANGUAGES = ['en', 'es', 'es_ES', 'fr_FR', 'fr_CA', 'en_CA', 'it_IT', 'de_DE', 'zh_CN', 'zh_TW', 'ko_KR', 'ja_JP', 'pt_BR', 'ru_RU', 'cs_CZ', 'nl_NL', 'pl_PL', 'id_ID', 'tr_TR', 'sv_SE', 'vi_VN', 'da_DK'] as const;
