// Generated by scripts/gen_sfx.mjs. Do not edit by hand.
// Maps a sound-effect key to its public audio path and loop flag.
export interface SfxEntry { url: string; loop: boolean }
export const SFX_CLIPS: Record<string, SfxEntry> =
{
  "amb_birds": {
    "url": "/audio/sfx/amb_birds.mp3",
    "loop": true
  },
  "amb_campfire": {
    "url": "/audio/sfx/amb_campfire.mp3",
    "loop": true
  },
  "amb_dungeon": {
    "url": "/audio/sfx/amb_dungeon.mp3",
    "loop": true
  },
  "amb_forge": {
    "url": "/audio/sfx/amb_forge.mp3",
    "loop": true
  },
  "amb_rain": {
    "url": "/audio/sfx/amb_rain.mp3",
    "loop": true
  },
  "amb_snow": {
    "url": "/audio/sfx/amb_snow.mp3",
    "loop": true
  },
  "amb_water": {
    "url": "/audio/sfx/amb_water.mp3",
    "loop": true
  },
  "amb_wind_marsh": {
    "url": "/audio/sfx/amb_wind_marsh.mp3",
    "loop": true
  },
  "amb_wind_peaks": {
    "url": "/audio/sfx/amb_wind_peaks.mp3",
    "loop": true
  },
  "amb_wind_vale": {
    "url": "/audio/sfx/amb_wind_vale.mp3",
    "loop": true
  },
  "buff_apply": {
    "url": "/audio/sfx/buff_apply.mp3",
    "loop": false
  },
  "cast_arcane": {
    "url": "/audio/sfx/cast_arcane.mp3",
    "loop": true
  },
  "cast_fire": {
    "url": "/audio/sfx/cast_fire.mp3",
    "loop": true
  },
  "cast_frost": {
    "url": "/audio/sfx/cast_frost.mp3",
    "loop": true
  },
  "cast_holy": {
    "url": "/audio/sfx/cast_holy.mp3",
    "loop": true
  },
  "cast_nature": {
    "url": "/audio/sfx/cast_nature.mp3",
    "loop": true
  },
  "cast_shadow": {
    "url": "/audio/sfx/cast_shadow.mp3",
    "loop": true
  },
  "combat_block": {
    "url": "/audio/sfx/combat_block.mp3",
    "loop": false
  },
  "combat_crit": {
    "url": "/audio/sfx/combat_crit.mp3",
    "loop": false
  },
  "combat_dodge": {
    "url": "/audio/sfx/combat_dodge.mp3",
    "loop": false
  },
  "combat_parry": {
    "url": "/audio/sfx/combat_parry.mp3",
    "loop": false
  },
  "debuff_apply": {
    "url": "/audio/sfx/debuff_apply.mp3",
    "loop": false
  },
  "foot_dirt": {
    "url": "/audio/sfx/foot_dirt.mp3",
    "loop": false
  },
  "foot_grass": {
    "url": "/audio/sfx/foot_grass.mp3",
    "loop": false
  },
  "foot_snow": {
    "url": "/audio/sfx/foot_snow.mp3",
    "loop": false
  },
  "foot_stone": {
    "url": "/audio/sfx/foot_stone.mp3",
    "loop": false
  },
  "foot_water": {
    "url": "/audio/sfx/foot_water.mp3",
    "loop": false
  },
  "foot_wood": {
    "url": "/audio/sfx/foot_wood.mp3",
    "loop": false
  },
  "heal_impact": {
    "url": "/audio/sfx/heal_impact.mp3",
    "loop": false
  },
  "impact_arcane": {
    "url": "/audio/sfx/impact_arcane.mp3",
    "loop": false
  },
  "impact_bone": {
    "url": "/audio/sfx/impact_bone.mp3",
    "loop": false
  },
  "impact_fire": {
    "url": "/audio/sfx/impact_fire.mp3",
    "loop": false
  },
  "impact_flesh": {
    "url": "/audio/sfx/impact_flesh.mp3",
    "loop": false
  },
  "impact_frost": {
    "url": "/audio/sfx/impact_frost.mp3",
    "loop": false
  },
  "impact_holy": {
    "url": "/audio/sfx/impact_holy.mp3",
    "loop": false
  },
  "impact_leather": {
    "url": "/audio/sfx/impact_leather.mp3",
    "loop": false
  },
  "impact_metal": {
    "url": "/audio/sfx/impact_metal.mp3",
    "loop": false
  },
  "impact_nature": {
    "url": "/audio/sfx/impact_nature.mp3",
    "loop": false
  },
  "impact_shadow": {
    "url": "/audio/sfx/impact_shadow.mp3",
    "loop": false
  },
  "melee_bow": {
    "url": "/audio/sfx/melee_bow.mp3",
    "loop": false
  },
  "melee_swing_blade": {
    "url": "/audio/sfx/melee_swing_blade.mp3",
    "loop": false
  },
  "melee_swing_heavy": {
    "url": "/audio/sfx/melee_swing_heavy.mp3",
    "loop": false
  },
  "melee_swing_light": {
    "url": "/audio/sfx/melee_swing_light.mp3",
    "loop": false
  },
  "melee_unarmed": {
    "url": "/audio/sfx/melee_unarmed.mp3",
    "loop": false
  },
  "mob_beast_aggro": {
    "url": "/audio/sfx/mob_beast_aggro.mp3",
    "loop": false
  },
  "mob_beast_attack": {
    "url": "/audio/sfx/mob_beast_attack.mp3",
    "loop": false
  },
  "mob_beast_death": {
    "url": "/audio/sfx/mob_beast_death.mp3",
    "loop": false
  },
  "mob_boar_aggro": {
    "url": "/audio/sfx/mob_boar_aggro.mp3",
    "loop": false
  },
  "mob_boar_attack": {
    "url": "/audio/sfx/mob_boar_attack.mp3",
    "loop": false
  },
  "mob_boar_death": {
    "url": "/audio/sfx/mob_boar_death.mp3",
    "loop": false
  },
  "mob_demon_aggro": {
    "url": "/audio/sfx/mob_demon_aggro.mp3",
    "loop": false
  },
  "mob_demon_attack": {
    "url": "/audio/sfx/mob_demon_attack.mp3",
    "loop": false
  },
  "mob_demon_death": {
    "url": "/audio/sfx/mob_demon_death.mp3",
    "loop": false
  },
  "mob_dragonkin_aggro": {
    "url": "/audio/sfx/mob_dragonkin_aggro.mp3",
    "loop": false
  },
  "mob_dragonkin_attack": {
    "url": "/audio/sfx/mob_dragonkin_attack.mp3",
    "loop": false
  },
  "mob_dragonkin_death": {
    "url": "/audio/sfx/mob_dragonkin_death.mp3",
    "loop": false
  },
  "mob_elemental_aggro": {
    "url": "/audio/sfx/mob_elemental_aggro.mp3",
    "loop": false
  },
  "mob_elemental_attack": {
    "url": "/audio/sfx/mob_elemental_attack.mp3",
    "loop": false
  },
  "mob_elemental_death": {
    "url": "/audio/sfx/mob_elemental_death.mp3",
    "loop": false
  },
  "mob_humanoid_aggro": {
    "url": "/audio/sfx/mob_humanoid_aggro.mp3",
    "loop": false
  },
  "mob_humanoid_attack": {
    "url": "/audio/sfx/mob_humanoid_attack.mp3",
    "loop": false
  },
  "mob_humanoid_death": {
    "url": "/audio/sfx/mob_humanoid_death.mp3",
    "loop": false
  },
  "mob_kobold_aggro": {
    "url": "/audio/sfx/mob_kobold_aggro.mp3",
    "loop": false
  },
  "mob_kobold_attack": {
    "url": "/audio/sfx/mob_kobold_attack.mp3",
    "loop": false
  },
  "mob_kobold_death": {
    "url": "/audio/sfx/mob_kobold_death.mp3",
    "loop": false
  },
  "mob_murloc_aggro": {
    "url": "/audio/sfx/mob_murloc_aggro.mp3",
    "loop": false
  },
  "mob_murloc_attack": {
    "url": "/audio/sfx/mob_murloc_attack.mp3",
    "loop": false
  },
  "mob_murloc_death": {
    "url": "/audio/sfx/mob_murloc_death.mp3",
    "loop": false
  },
  "mob_ogre_aggro": {
    "url": "/audio/sfx/mob_ogre_aggro.mp3",
    "loop": false
  },
  "mob_ogre_attack": {
    "url": "/audio/sfx/mob_ogre_attack.mp3",
    "loop": false
  },
  "mob_ogre_death": {
    "url": "/audio/sfx/mob_ogre_death.mp3",
    "loop": false
  },
  "mob_spider_aggro": {
    "url": "/audio/sfx/mob_spider_aggro.mp3",
    "loop": false
  },
  "mob_spider_attack": {
    "url": "/audio/sfx/mob_spider_attack.mp3",
    "loop": false
  },
  "mob_spider_death": {
    "url": "/audio/sfx/mob_spider_death.mp3",
    "loop": false
  },
  "mob_troll_aggro": {
    "url": "/audio/sfx/mob_troll_aggro.mp3",
    "loop": false
  },
  "mob_troll_attack": {
    "url": "/audio/sfx/mob_troll_attack.mp3",
    "loop": false
  },
  "mob_troll_death": {
    "url": "/audio/sfx/mob_troll_death.mp3",
    "loop": false
  },
  "mob_undead_aggro": {
    "url": "/audio/sfx/mob_undead_aggro.mp3",
    "loop": false
  },
  "mob_undead_attack": {
    "url": "/audio/sfx/mob_undead_attack.mp3",
    "loop": false
  },
  "mob_undead_death": {
    "url": "/audio/sfx/mob_undead_death.mp3",
    "loop": false
  },
  "move_jump": {
    "url": "/audio/sfx/move_jump.mp3",
    "loop": false
  },
  "move_land": {
    "url": "/audio/sfx/move_land.mp3",
    "loop": false
  },
  "move_splash": {
    "url": "/audio/sfx/move_splash.mp3",
    "loop": false
  },
  "move_swim": {
    "url": "/audio/sfx/move_swim.mp3",
    "loop": false
  },
  "player_death": {
    "url": "/audio/sfx/player_death.mp3",
    "loop": false
  },
  "player_hurt": {
    "url": "/audio/sfx/player_hurt.mp3",
    "loop": false
  },
  "proj_arcane": {
    "url": "/audio/sfx/proj_arcane.mp3",
    "loop": false
  },
  "proj_fire": {
    "url": "/audio/sfx/proj_fire.mp3",
    "loop": false
  },
  "proj_frost": {
    "url": "/audio/sfx/proj_frost.mp3",
    "loop": false
  },
  "proj_holy": {
    "url": "/audio/sfx/proj_holy.mp3",
    "loop": false
  },
  "proj_nature": {
    "url": "/audio/sfx/proj_nature.mp3",
    "loop": false
  },
  "proj_shadow": {
    "url": "/audio/sfx/proj_shadow.mp3",
    "loop": false
  },
  "spell_nova": {
    "url": "/audio/sfx/spell_nova.mp3",
    "loop": false
  }
} as const;
