// NPC voice-line playback. Plays the pre-rendered ElevenLabs clips under
// public/audio/voice (generated by scripts/gen_npc_lines.mjs) via a single
// HTMLAudioElement — the same plain-`Audio` approach as the main-theme player in
// main.ts, so there's no AudioContext user-gesture gate to manage here.
//
// Lookup is by line key (`greeting__<npcId>`, `quest__<questId>__offer`,
// `quest__<questId>__complete`) against the generated manifest; unknown keys and
// missing files are silent no-ops, so the game runs fine before any audio exists.

import { VOICE_LINES } from './voice_manifest.generated';

// Voices sit slightly under their slider value so NPC dialogue doesn't overpower
// the SFX/ambience mix.
const VOICE_BASE_GAIN = 0.9;

class GameVoice {
  private el: HTMLAudioElement | null = null;
  private vol = 0.9; // 0..1, from the settings slider
  private enabled = true;

  /** Set voice volume (0..1). Safe any time. */
  setVolume(v: number): void {
    this.vol = Math.min(1, Math.max(0, v));
    if (this.el) this.el.volume = this.vol * VOICE_BASE_GAIN;
  }

  /** Enable/disable voice-over. Disabling also stops any line in progress. */
  setEnabled(on: boolean): void {
    this.enabled = on;
    if (!on) this.stop();
  }

  /** Stop and reset the current line (so a new NPC interrupts the last one). */
  stop(): void {
    if (this.el) {
      this.el.pause();
      this.el.currentTime = 0;
    }
  }

  /** Play the clip for a line key, if one exists and voice-over is enabled. */
  play(lineKey: string): void {
    if (!this.enabled) return;
    const src = VOICE_LINES[lineKey];
    if (!src) return;
    this.stop();
    if (!this.el) this.el = new Audio();
    this.el.src = src;
    this.el.volume = this.vol * VOICE_BASE_GAIN;
    // Autoplay restrictions / a missing file reject the promise — ignore, the
    // dialogue text is the source of truth and audio is an enhancement.
    void this.el.play().catch(() => { /* no-op */ });
  }
}

export const voice = new GameVoice();
