import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import * as fs from 'fs';
import path from 'path';
import { describe, expect, it } from 'vitest';
// @ts-expect-error - shared zero-dep JS hash helper (no .d.ts). The scanner uses the
// SAME module, so re-deriving hashes here is an independent check of the registry
// rather than a copy of the scanner's own arithmetic.
import { contentHash, placeholdersOf } from '../scripts/i18n_hash.mjs';
import { DICT as adminDICT } from '../src/admin/i18n';
import { en, supportedLanguages } from '../src/ui/i18n';
import { DICT as serverDICT } from '../src/ui/server_i18n';
import { DICT as simDICT } from '../src/ui/sim_i18n';
import { assertDeterministic } from './helpers/i18n_determinism';

// src/ui/i18n.status.json is the generated per-key per-locale status
// registry (scripts/i18n_scan.mjs, regenerated in pretest). This suite is the
// registry-in-sync + reproducibility net: the registry must cover the whole key
// universe, every enHash must independently re-derive from the English source,
// the pending set must be empty while everything is dense, blocked rows must be
// load-bearing (no silent over-allow), the hash must move when the English text
// or its placeholder set changes, and the artifact must regenerate byte-identically.

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const registryRel = 'src/ui/i18n.status.json';
// status.json is gitignored and regenerated by pretest / the CI i18n:gen step, so it
// is always present under `npm test`. Point at the fix rather than a raw ENOENT if
// this file is run directly on a tree where the registry was never generated.
const registryPath = path.join(root, registryRel);
if (!fs.existsSync(registryPath))
  throw new Error(
    'src/ui/i18n.status.json is missing - run `npm run i18n:gen` (pretest does this for `npm test`).',
  );
const registry: any = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
// The committed audit summary (counts + per-locale rollup + universeHash, no per-key
// bodies) emitted alongside the gitignored full registry by the same scanner run.
const summaryRel = 'src/ui/i18n.status.summary.json';
const summary: any = JSON.parse(fs.readFileSync(path.join(root, summaryRel), 'utf8'));
const NON_EN = supportedLanguages.filter((l) => l !== 'en');

// Two-tier gate: the release tier runs with I18N_RELEASE_TIER=1 (see
// .github/workflows/ci.yml). An empty-`pending` set is a RELEASE guarantee, not a
// PR one - an English-only PR legitimately leaves keys pending - so that assertion
// runs release-only. Registry-in-sync (universe coverage, enHash re-derivation,
// reproducibility) stays at the PR tier.
const RELEASE_TIER = process.env.I18N_RELEASE_TIER === '1';

// Same object-vs-leaf rule as scripts/i18n_flatten.mjs (recurse PLAIN objects;
// arrays and non-objects are leaves), so the universe we expect matches the one
// the scanner walked.
function flatten(node: any, prefix = '', out: Record<string, string> = {}): Record<string, string> {
  for (const k of Object.keys(node)) {
    const v = node[k];
    const p = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === 'object' && !Array.isArray(v)) flatten(v, p, out);
    else out[p] = v as string;
  }
  return out;
}

// The English source value for every key in the universe, keyed by the registry's
// "<scope>:<key>" composite. Built straight from the imported source objects.
function expectedUniverse(): Map<string, string> {
  const m = new Map<string, string>();
  for (const [k, v] of Object.entries(flatten(en as any))) m.set(`main:${k}`, v);
  for (const [k, v] of Object.entries(simDICT.en)) m.set(`sim:${k}`, v as string);
  for (const [k, v] of Object.entries(serverDICT.en)) m.set(`server:${k}`, v as string);
  for (const [k, v] of Object.entries(adminDICT.en)) m.set(`admin:${k}`, v as string);
  return m;
}

const keyEntries = (): [string, any][] => Object.entries(registry.keys);

describe('i18n status registry: universe coverage', () => {
  it('has exactly one row per source key (en leaves + sim/server/admin DICT keys)', () => {
    const expected = expectedUniverse();
    const regKeys = new Set(Object.keys(registry.keys));
    const missing = [...expected.keys()].filter((k) => !regKeys.has(k));
    expect(missing.length, `registry is missing rows for: ${missing.slice(0, 10).join(', ')}`).toBe(
      0,
    );
    const extra = [...regKeys].filter((k) => !expected.has(k));
    expect(
      extra.length,
      `registry has rows with no source key: ${extra.slice(0, 10).join(', ')}`,
    ).toBe(0);
    expect(registry.counts.keys).toBe(expected.size);
  });

  it('tracks exactly supportedLanguages minus en, in order', () => {
    expect(registry.locales).toEqual(NON_EN);
    for (const [, entry] of keyEntries()) {
      expect(Object.keys(entry.locales)).toEqual(NON_EN);
    }
  });
});

describe('i18n status registry: enHash re-derivation (independent)', () => {
  it('each enHash == contentHash(englishText, sortedPlaceholders) recomputed from source', () => {
    // Accumulate violations and assert ONCE: a per-row expect() over the ~5k-key
    // universe costs seconds of matcher overhead and trips the default per-test
    // timeout on a loaded runner, for identical semantics.
    const expected = expectedUniverse();
    const violations: string[] = [];
    for (const [ck, enVal] of expected) {
      const row = registry.keys[ck];
      if (row.enHash !== contentHash(enVal, placeholdersOf(enVal)))
        violations.push(`${ck} enHash mismatch`);
      if (JSON.stringify(row.placeholders) !== JSON.stringify(placeholdersOf(enVal)))
        violations.push(`${ck} placeholders`);
    }
    expect(violations).toEqual([]);
  });
});

describe('i18n status registry: states', () => {
  // RELEASE-TIER ONLY. A `pending` key must never reach a cut release;
  // the release gate asserts the set is empty. At the PR tier a pending key is
  // LEGAL (English-only PRs), so this is skipped there. Today the set is empty at
  // both tiers because the overlays are still dense - this gate guards the future.
  it.runIf(RELEASE_TIER)(
    'the pending set is empty (release tier: no untranslated key may ship)',
    () => {
      expect(registry.counts.pending).toBe(0);
      let pending = 0;
      for (const [, entry] of keyEntries())
        for (const row of Object.values<any>(entry.locales)) if (row.state === 'pending') pending++;
      expect(pending).toBe(0);
    },
  );

  // Teeth for the release-tier gate above. That gate reads the real, dense registry
  // (pending=0 today), so on its own it cannot prove the assertion is non-vacuous.
  // Mirror the manual injection as a COMMITTED check: flip one translated row to
  // pending in a clone and confirm BOTH quantities the gate measures (counts.pending
  // and a fresh re-tally of pending rows) become non-zero - i.e. a pending key WOULD
  // trip the gate. Runs at both tiers so the teeth can never silently rot.
  it('the pending===0 gate is non-vacuous (a synthetic pending row trips both measured quantities)', () => {
    const clone = JSON.parse(JSON.stringify(registry));
    let flipped = false;
    for (const entry of Object.values<any>(clone.keys)) {
      for (const row of Object.values<any>(entry.locales))
        if (row.state === 'translated') {
          row.state = 'pending';
          flipped = true;
          break;
        }
      if (flipped) break;
    }
    expect(flipped, 'fixture sanity: at least one translated row must exist to flip').toBe(true);
    clone.counts.pending += 1;
    // Both conditions the release-tier gate asserts to be 0 are now non-zero:
    expect(clone.counts.pending).not.toBe(0);
    let pending = 0;
    for (const entry of Object.values<any>(clone.keys))
      for (const row of Object.values<any>(entry.locales)) if (row.state === 'pending') pending++;
    expect(pending).toBeGreaterThan(0);
  });

  it('counts are internally consistent and match a fresh re-tally', () => {
    const { keys, rows, translated, pending, blocked, blockedSource } = registry.counts;
    expect(rows).toBe(keys * NON_EN.length);
    expect(translated + pending + blocked).toBe(rows);
    expect(blockedSource).toBe(registry.blockedSource.length);
    let t = 0,
      p = 0,
      b = 0;
    for (const [, entry] of keyEntries())
      for (const row of Object.values<any>(entry.locales)) {
        if (row.state === 'translated') t++;
        else if (row.state === 'pending') p++;
        else if (row.state === 'blocked') b++;
      }
    expect([t, p, b]).toEqual([translated, pending, blocked]);
  });

  it('every translated row is fresh (srcHash === enHash) and attributed (by human|agent)', () => {
    // Accumulate violations and assert ONCE: this walks ~100k locale rows, and a
    // per-row expect() pair (~200k matcher calls) took ~6s, past the default 5s
    // per-test budget on a loaded runner (the flake seen in full-suite runs).
    // Plain JS checks keep it in milliseconds with identical semantics.
    const violations: string[] = [];
    for (const [ck, entry] of keyEntries())
      for (const [loc, row] of Object.entries<any>(entry.locales)) {
        if (row.state !== 'translated') continue;
        if (row.srcHash !== entry.enHash) violations.push(`${ck} ${loc} stale srcHash`);
        if (row.by !== 'human' && row.by !== 'agent') violations.push(`${ck} ${loc} unattributed`);
      }
    expect(violations).toEqual([]);
  });
});

describe('i18n status registry: blocked rows are load-bearing (no over-allow)', () => {
  const dicts: Record<string, any> = { server: serverDICT, admin: adminDICT };

  it('every blocked server/admin row genuinely copies English (value === en) and has a reason', () => {
    for (const [ck, entry] of keyEntries()) {
      const ci = ck.indexOf(':');
      const scope = ck.slice(0, ci);
      const key = ck.slice(ci + 1);
      if (scope !== 'server' && scope !== 'admin') continue;
      for (const [loc, row] of Object.entries<any>(entry.locales)) {
        if (row.state !== 'blocked') continue;
        expect(
          typeof row.reason === 'string' && row.reason.trim().length > 0,
          `${ck} ${loc} blocked w/o reason`,
        ).toBe(true);
        const dict = dicts[scope];
        // A cognate is, by definition, a translation that equals English. If this
        // ever fails the seed has rotted: the value got translated, so the row
        // should be translated, not blocked (silent over-allow).
        expect(dict[loc]?.[key], `${ck} ${loc} is blocked but no longer copies English`).toBe(
          dict.en[key],
        );
      }
    }
  });

  it('only server/admin scopes carry blocked rows (main/sim carry none)', () => {
    // Same accumulate-then-assert-once shape as the freshness walk above.
    const violations: string[] = [];
    for (const [ck, entry] of keyEntries()) {
      const scope = ck.slice(0, ck.indexOf(':'));
      if (scope === 'server' || scope === 'admin') continue;
      for (const row of Object.values<any>(entry.locales))
        if (row.state === 'blocked')
          violations.push(`${ck} unexpected blocked row in scope ${scope}`);
    }
    expect(violations).toEqual([]);
  });

  it('every blockedSource entry is a unique sim-channel string with a reason', () => {
    const texts: string[] = registry.blockedSource.map((b: any) => b.text);
    expect(new Set(texts).size).toBe(texts.length);
    for (const b of registry.blockedSource) {
      expect(b.channel).toBe('sim');
      expect(typeof b.reason === 'string' && b.reason.length > 0).toBe(true);
    }
  });
});

describe('i18n status registry: hash sensitivity (srcHash includes the placeholder set)', () => {
  it('changing the English text moves the hash', () => {
    expect(contentHash('You have {n} gold.')).not.toBe(contentHash('You have {n} silver.'));
  });
  it('renaming a placeholder moves the hash', () => {
    expect(contentHash('Hello {name}')).not.toBe(contentHash('Hello {playerName}'));
  });
  it('the declared placeholder set feeds the hash independently of the text, and is order-independent', () => {
    expect(contentHash('X', ['a'])).not.toBe(contentHash('X', ['b']));
    expect(contentHash('X', ['a', 'b'])).toBe(contentHash('X', ['b', 'a']));
  });
});

describe('i18n status registry: determinism (status.json is gitignored - no committed bytes to diff)', () => {
  // src/ui/i18n.status.json is build/test-only (~4.7 MB) and gitignored, so the old
  // committed-bytes `git ls-files` + `git diff --exit-code` freshness check no longer
  // applies (pretest / the CI i18n:gen step regenerate it before any test reads it).
  // Reproducibility is instead proven by double-generating into two PERTURBED-env temp
  // dirs (different TZ / LC_ALL / temp-path) and asserting byte-identity. A
  // non-deterministic scanner makes this throw. The committed summary additionally
  // keeps a `git diff` freshness check below.
  // Double-generates by spawning the scanner (cold Node + esbuild bundle of the TS
  // source) TWICE, so the default 5s per-test budget is too tight on a loaded CI
  // runner (a single cold scan is already ~1-3s there). Give it a generous timeout;
  // the assertion is about byte-identity, not speed.
  it('regenerates status.json + the summary byte-identically across two perturbed-env runs', () => {
    expect(() =>
      assertDeterministic({
        script: path.join(root, 'scripts/i18n_scan.mjs'),
        outFiles: ['i18n.status.json', 'i18n.status.summary.json'],
      }),
    ).not.toThrow();
  }, 30_000);
});

describe('i18n status summary: committed audit rollup cross-checks the full registry', () => {
  it('is committed (tracked by git) and regenerates byte-identically (freshness)', () => {
    expect(() =>
      execFileSync('git', ['ls-files', '--error-unmatch', '--', summaryRel], {
        cwd: root,
        encoding: 'utf8',
      }),
    ).not.toThrow();
    // Regenerates both artifacts; only the committed summary is diffed (status.json is
    // gitignored, so a `git diff` on it would silently pass regardless).
    execFileSync(process.execPath, [path.join(root, 'scripts/i18n_scan.mjs')], {
      cwd: root,
      encoding: 'utf8',
    });
    expect(() =>
      execFileSync('git', ['diff', '--exit-code', '--', summaryRel], {
        cwd: root,
        encoding: 'utf8',
      }),
    ).not.toThrow();
    // Spawns the scanner subprocess too (cold Node + esbuild); same slow-CI reason as
    // the determinism test above, so it gets the same generous budget.
  }, 30_000);

  it('summary counts equal the full registry counts, and locales/scopes mirror it', () => {
    expect(summary.counts).toEqual(registry.counts);
    expect(summary.locales).toEqual(registry.locales);
    expect(summary.scopes).toEqual(registry.scopes);
  });

  it('the per-locale rollup tallies to the registry totals and to keys-per-locale', () => {
    expect(Object.keys(summary.perLocale)).toEqual(NON_EN);
    let t = 0,
      p = 0,
      b = 0;
    for (const lang of NON_EN) {
      const row = summary.perLocale[lang];
      // Every key has exactly one state per locale, so the three states sum to `keys`.
      expect(row.translated + row.pending + row.blocked, `${lang} rollup != key count`).toBe(
        registry.counts.keys,
      );
      t += row.translated;
      p += row.pending;
      b += row.blocked;
    }
    expect([t, p, b]).toEqual([
      registry.counts.translated,
      registry.counts.pending,
      registry.counts.blocked,
    ]);
  });

  it('the universeHash re-derives independently from the full registry', () => {
    // Same canonical form the scanner hashes: "<composite><enHash><placeholders>"
    // per key, in registry (emit) order, joined by newlines.
    const SEP = String.fromCharCode(0x1f);
    const derived = createHash('sha256')
      .update(
        Object.entries(registry.keys)
          .map(
            ([ck, e]: [string, any]) => `${ck}${SEP}${e.enHash}${SEP}${e.placeholders.join(',')}`,
          )
          .join('\n'),
        'utf8',
      )
      .digest('hex');
    expect(summary.universeHash).toBe(derived);
  });
});
