// Generated by scripts/i18n_admin_build.mjs. Do not edit by hand.
//
// Part of the generated src/admin/i18n.resolved.generated/ directory: one dense
// ADMIN locale slice per file (each `: AdminTranslations` = typeof en, so tsc
// red-fails a missing or renamed key), a back-compat barrel (index.ts) that
// re-exports every slice and assembles the runtime `translations` map, per-locale
// loaders (loaders.ts, parity scaffolding - admin is NOT lazy), and the pending
// set (pending.ts). The admin SPA consumes ONLY this table (never the game locale
// table); regenerate with `npm run i18n:admin` (also wired into `npm run build`
// and `pretest`). Reproducibility is checked by tests/i18n_admin_catalog.test.ts.

export const pending: Record<string, readonly string[]> = {
  "es": [],
  "es_ES": [],
  "fr_FR": [],
  "fr_CA": [],
  "en_CA": [],
  "it_IT": [],
  "de_DE": [],
  "zh_CN": [],
  "zh_TW": [],
  "ko_KR": [],
  "ja_JP": [],
  "pt_BR": [],
  "ru_RU": [],
  "cs_CZ": [],
  "nl_NL": [],
  "pl_PL": [],
  "id_ID": [],
  "tr_TR": [],
  "sv_SE": [],
  "vi_VN": [],
  "da_DK": []
};
