// Bundle the Electron main-process runtime dependencies (electron-log,
// electron-updater) into self-contained CommonJS files under electron/vendor/.
//
// Why: the desktop app deliberately ships NO node_modules (package.json
// build.files has "!node_modules/**"; the repo's production dependencies are
// server/web deps like pg and three that a desktop client must not carry), so
// anything the main process needs at runtime is esbuild-bundled here instead.
// electron/vendor/ is generated output (gitignored, rebuilt by electron-dev.mjs
// and electron-build.mjs before every run); never hand-edit it. The `electron`
// module itself stays external: Electron provides it at runtime.

import { mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSync } from 'esbuild';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'electron', 'vendor');

const BUNDLES = [
  { entry: 'electron-log/main', out: 'electron_log_main.cjs' },
  { entry: 'electron-updater', out: 'electron_updater.cjs' },
];

export function buildElectronVendor() {
  mkdirSync(outDir, { recursive: true });
  for (const { entry, out } of BUNDLES) {
    buildSync({
      entryPoints: [entry],
      outfile: path.join(outDir, out),
      bundle: true,
      platform: 'node',
      format: 'cjs',
      target: 'node24',
      external: ['electron'],
      absWorkingDir: root,
      logLevel: 'warning',
      banner: { js: '// Generated by scripts/electron-vendor.mjs. Do not edit.' },
    });
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildElectronVendor();
  console.log(
    `[electron-vendor] bundled ${BUNDLES.map((b) => b.entry).join(', ')} -> electron/vendor/`,
  );
}
