// Generate every sound effect via the ElevenLabs Sound Effects API
// (POST /v1/sound-generation) from the catalog in scripts/sfx/sfx_prompts.mjs.
//
//   ELEVENLABS_API_KEY=… node scripts/gen_sfx.mjs [--force]
//
// Output:
//   public/audio/sfx/<key>.mp3            the audio (served at /audio/sfx/…)
//   src/game/sfx_manifest.generated.ts    key -> public path + loop flag
//
// Idempotent: existing files are skipped unless --force. Offline-only; the key is
// read from the environment / local .env and never committed.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { SFX } from './sfx/sfx_prompts.mjs';

const API = 'https://api.elevenlabs.io';
const OUTPUT_FORMAT = 'mp3_44100_128';
const PROMPT_INFLUENCE = 0.4; // adhere to the prompt but allow some character
const root = process.cwd();
const sfxDir = path.join(root, 'public/audio/sfx');
const manifestPath = path.join(root, 'src/game/sfx_manifest.generated.ts');

const force = process.argv.includes('--force');

try { process.loadEnvFile(); } catch { /* no .env — rely on the ambient env */ }
const KEY = process.env.ELEVENLABS_API_KEY;
if (!KEY) {
  console.error('ELEVENLABS_API_KEY is not set (env or .env). Aborting.');
  process.exit(1);
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function generate(entry, { retries = 4 } = {}) {
  const body = {
    text: entry.prompt,
    duration_seconds: entry.duration,
    prompt_influence: PROMPT_INFLUENCE,
    output_format: OUTPUT_FORMAT,
  };
  if (entry.loop) body.loop = true;
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(`${API}/v1/sound-generation`, {
      method: 'POST',
      headers: { 'xi-api-key': KEY, 'content-type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (res.ok) return Buffer.from(await res.arrayBuffer());
    const detail = await res.text().catch(() => '');
    const retryable = res.status === 429 || res.status >= 500;
    if (retryable && attempt < retries) {
      const wait = 1500 * (attempt + 1);
      console.warn(`  ${entry.key} -> ${res.status}; retrying in ${wait}ms`);
      await sleep(wait);
      continue;
    }
    throw new Error(`${entry.key} -> ${res.status} ${detail.slice(0, 200)}`);
  }
}

mkdirSync(sfxDir, { recursive: true });
let made = 0;
let skipped = 0;
let seconds = 0;
const failed = [];

for (const entry of SFX) {
  const dest = path.join(sfxDir, `${entry.key}.mp3`);
  if (existsSync(dest) && !force) { skipped++; continue; }
  process.stdout.write(`sfx  ${entry.key} (${entry.duration}s${entry.loop ? ', loop' : ''})… `);
  try {
    const mp3 = await generate(entry);
    writeFileSync(dest, mp3);
    seconds += entry.duration;
    made++;
    console.log('ok');
    await sleep(200);
  } catch (err) {
    // One bad clip shouldn't abort the whole run — record it and continue.
    console.log('FAILED');
    console.error(`  ${err.message}`);
    failed.push(entry.key);
    process.exitCode = 1;
  }
}

// Rebuild the manifest from whatever exists on disk so runtime never points at a
// missing clip after a partial run. Includes the loop flag so the engine knows
// which clips are seamless loops.
const entries = {};
for (const entry of SFX) {
  if (existsSync(path.join(sfxDir, `${entry.key}.mp3`))) {
    entries[entry.key] = { url: `/audio/sfx/${entry.key}.mp3`, loop: !!entry.loop };
  }
}
const sorted = Object.fromEntries(Object.keys(entries).sort().map((k) => [k, entries[k]]));
mkdirSync(path.dirname(manifestPath), { recursive: true });
writeFileSync(
  manifestPath,
  [
    '// Generated by scripts/gen_sfx.mjs. Do not edit by hand.',
    '// Maps a sound-effect key to its public audio path and loop flag.',
    'export interface SfxEntry { url: string; loop: boolean }',
    'export const SFX_CLIPS: Record<string, SfxEntry> =',
    `${JSON.stringify(sorted, null, 2)} as const;`,
    '',
  ].join('\n'),
);

console.log(`\nDone: ${made} generated, ${skipped} skipped, ${Object.keys(sorted).length}/${SFX.length} clips on disk.`);
console.log(`Billed ~${seconds.toFixed(1)} seconds of audio this run. Manifest: ${path.relative(root, manifestPath)}`);
if (failed.length) console.log(`Failed (${failed.length}): ${failed.join(', ')}`);
