// Build the dense resolved translation table src/ui/i18n.resolved.generated.ts.
//
// This is the load-bearing tsc safety net for the i18n scaling refactor. Every
// locale is overlaid onto a deep copy of the authoritative nested `en`, with any
// missing leaf filled from the English value, so every emitted locale is DENSE
// (no gaps). The generated file types each locale ": EnTranslations" (= typeof
// en), so tsc still red-fails any missing or renamed key. Client and admin read
// this generated table, never the raw per-locale objects (which become sparse in
// later phases).
//
// Zero runtime deps; bundles the TS source with esbuild (the same pattern as
// scripts/i18n_resolved_hash.mjs and scripts/export_loot_spreadsheet.mjs). Writes
// deterministically - key ordering is driven by `en`, indentation and quoting are
// fixed, and there are no timestamps / Date.now / Math.random anywhere - so two
// runs on the same input are byte-identical (reproducibility-checked like the
// media manifest).
//
// Usage:
//   node scripts/i18n_build.mjs   (re)generate src/ui/i18n.resolved.generated.ts

import * as esbuild from 'esbuild';
import { writeFileSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const OUT_PATH = path.join(root, 'src/ui/i18n.resolved.generated.ts');

// The authoritative ordered locale set. `en` is the nested base; the other 13 are
// the Phase 1 split locale files. This list drives both the emit order and the
// runtime supportedLanguages (Object.keys of the generated `translations`). The
// generator reads these SOURCE modules directly and never imports src/ui/i18n.ts,
// so it never depends on the file it generates (no circular import at build time).
const LOCALES = [
  'en',
  'es',
  'es_ES',
  'fr_FR',
  'fr_CA',
  'en_CA',
  'it_IT',
  'de_DE',
  'zh_CN',
  'zh_TW',
  'ko_KR',
  'ja_JP',
  'pt_BR',
  'ru_RU',
];

function sourceModule(lang) {
  return lang === 'en' ? './src/ui/i18n.en' : `./src/ui/i18n.locales/${lang}`;
}

// Bundle the source locale objects via a tiny stub and import the result. We pull
// `en` and each locale export by its code; none of this touches the generated file.
async function loadLocales() {
  const stub = LOCALES.map((lang) => `export { ${lang} } from '${sourceModule(lang)}';`).join('\n');
  const build = await esbuild.build({
    stdin: {
      contents: stub,
      resolveDir: root,
      sourcefile: 'i18n-build-entry.ts',
      loader: 'ts',
    },
    bundle: true,
    platform: 'node',
    format: 'esm',
    write: false,
    logLevel: 'silent',
  });
  const dataUrl = `data:text/javascript;base64,${Buffer.from(build.outputFiles[0].text).toString('base64')}`;
  const mod = await import(dataUrl);
  const out = {};
  for (const lang of LOCALES) out[lang] = mod[lang];
  return out;
}

function deepCopy(value) {
  return JSON.parse(JSON.stringify(value));
}

// Overlay `over` onto `base` (a fresh deep copy of en), in place: an object node
// recurses; any other leaf takes the overlay's value. Keys present only in `base`
// keep their English value (fill-from-English); keys present only in `over` are
// appended. Driving from a copy of `en` keeps the emitted key order stable.
function deepMerge(base, over) {
  for (const key of Object.keys(over)) {
    const overValue = over[key];
    const baseValue = base[key];
    const bothObjects =
      overValue && typeof overValue === 'object' && !Array.isArray(overValue) &&
      baseValue && typeof baseValue === 'object' && !Array.isArray(baseValue);
    if (bothObjects) {
      deepMerge(baseValue, overValue);
    } else {
      base[key] = overValue;
    }
  }
  return base;
}

function banner() {
  return [
    '// Generated by scripts/i18n_build.mjs. Do not edit by hand.',
    '//',
    '// Dense resolved 14-locale translation table: every locale overlaid onto the',
    '// authoritative nested `en`, with any missing leaf filled from English. Each',
    "// locale is typed `: EnTranslations` (= typeof en) so tsc red-fails a missing or",
    '// renamed key. The runtime, the client, and any table reader consume this file;',
    "// regenerate with `npm run i18n:build` (also wired into `npm run build` and",
    '// `pretest`). Reproducibility is checked by tests/i18n_resolved_equivalence.test.ts.',
  ].join('\n');
}

function emit(resolved) {
  const lines = [banner(), '', "import type { EnTranslations } from './i18n.en';", ''];
  for (const lang of LOCALES) {
    lines.push(`export const ${lang}: EnTranslations = ${JSON.stringify(resolved[lang], null, 2)};`);
    lines.push('');
  }
  lines.push(`export const translations = {`);
  for (const lang of LOCALES) lines.push(`  ${lang},`);
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

async function main() {
  const locales = await loadLocales();
  const en = locales.en;
  const resolved = {};
  for (const lang of LOCALES) {
    resolved[lang] = deepMerge(deepCopy(en), locales[lang]);
  }
  const text = emit(resolved);
  writeFileSync(OUT_PATH, text);
  console.log(
    `generated ${path.relative(root, OUT_PATH)} (${LOCALES.length} locales, ${Buffer.byteLength(text, 'utf8')} bytes)`,
  );
}

await main();
