// Build the dense resolved admin translation table
// src/admin/i18n.resolved.generated/.
//
// The admin twin of scripts/i18n_build.mjs: same per-locale directory shape (one
// dense `<lang>.ts` per locale + en_XA.ts + a back-compat barrel index.ts + a
// loaders.ts + pending.ts). The split is for IDE/diff/parity with the game table -
// the admin runtime is NOT going lazy; src/admin/i18n.ts keeps its static barrel
// import. `en` (src/admin/i18n.en.ts) is the
// authoritative FLAT English base; the 13 non-English locales are FLAT overlays
// (src/admin/i18n.locales/<lang>.ts). Each overlay is merged onto a copy of `en`,
// with any omitted key filled from English, so every emitted locale is DENSE. The
// generated file types each locale ": AdminTranslations" (= typeof en), so tsc
// red-fails a missing or renamed key. The admin SPA reads this generated table,
// never the raw overlays (which may go sparse) - and it imports its OWN table, so
// the game locale data is never pulled into the admin bundle.
//
// Admin keys are already flat dotted strings, so there is no flatten/unflatten:
// the overlay IS the locale slice and merging is a shallow Object.assign.
//
// Zero runtime deps; bundles the TS source with esbuild (same pattern as
// scripts/i18n_build.mjs). Deterministic: key order is driven by `en`, no
// Date.now / Math.random - two runs on the same input are byte-identical
// (reproducibility-checked by tests/i18n_admin_catalog.test.ts).
//
// Usage:
//   node scripts/i18n_admin_build.mjs
//   I18N_OUT_DIR=... node scripts/i18n_admin_build.mjs   emit into a custom directory

import { mkdirSync, readdirSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import * as esbuild from 'esbuild';
import { pseudoLocalize } from './i18n_pseudo.mjs';

const root = process.cwd();
// The generated output is a DIRECTORY of per-locale modules, not a single file.
// I18N_OUT_DIR overrides the destination (used by the determinism test to emit into
// a throwaway temp dir without touching the committed artifact).
const OUT_DIR = process.env.I18N_OUT_DIR
  ? path.resolve(root, process.env.I18N_OUT_DIR)
  : path.join(root, 'src/admin/i18n.resolved.generated');

// Authoritative ordered locale set (mirrors scripts/i18n_build.mjs LOCALES). `en`
// is the base; the rest are flat overlays. Drives emit order + supportedLanguages.
const LOCALES = [
  'en',
  'es',
  'es_ES',
  'fr_FR',
  'fr_CA',
  'en_CA',
  'it_IT',
  'de_DE',
  'zh_CN',
  'zh_TW',
  'ko_KR',
  'ja_JP',
  'pt_BR',
  'ru_RU',
  'cs_CZ',
  'nl_NL',
  'pl_PL',
  'id_ID',
  'tr_TR',
  'sv_SE',
  'vi_VN',
  'da_DK',
];

// Dialect locales resolve through a base (base-resolution model): nested en -> base
// overlay -> dialect overlay. Mirror of scripts/i18n_build.mjs DIALECT_BASE.
const DIALECT_BASE = { es_ES: 'es', fr_CA: 'fr_FR', en_CA: 'en' };

function sourceModule(lang) {
  return lang === 'en' ? './src/admin/i18n.en' : `./src/admin/i18n.locales/${lang}`;
}

async function loadLocales() {
  const stub = LOCALES.map((lang) => `export { ${lang} } from '${sourceModule(lang)}';`).join('\n');
  const build = await esbuild.build({
    stdin: {
      contents: stub,
      resolveDir: root,
      sourcefile: 'admin-i18n-build-entry.ts',
      loader: 'ts',
    },
    bundle: true,
    platform: 'node',
    format: 'esm',
    write: false,
    logLevel: 'silent',
  });
  const dataUrl = `data:text/javascript;base64,${Buffer.from(build.outputFiles[0].text).toString('base64')}`;
  const mod = await import(dataUrl);
  const out = {};
  for (const lang of LOCALES) out[lang] = mod[lang];
  return out;
}

const isPresent = (v) => typeof v === 'string' && v.trim().length > 0;

// Per-file do-not-edit banner. Every module in the generated directory carries it.
function fileBanner() {
  return [
    '// Generated by scripts/i18n_admin_build.mjs. Do not edit by hand.',
    '//',
    '// Part of the generated src/admin/i18n.resolved.generated/ directory: one dense',
    '// ADMIN locale slice per file (each `: AdminTranslations` = typeof en, so tsc',
    '// red-fails a missing or renamed key), a back-compat barrel (index.ts) that',
    '// re-exports every slice and assembles the runtime `translations` map, per-locale',
    '// loaders (loaders.ts, parity scaffolding - admin is NOT lazy), and the pending',
    '// set (pending.ts). The admin SPA consumes ONLY this table (never the game locale',
    '// table); regenerate with `npm run i18n:admin` (also wired into `npm run build`',
    '// and `pretest`). Reproducibility is checked by tests/i18n_admin_catalog.test.ts.',
  ].join('\n');
}

// One dense ADMIN locale slice. Typed `: AdminTranslations` (= typeof en) so tsc
// red-fails a missing or renamed key PER FILE. The `import type` reaches up one level
// to i18n.en and is erased at build time (no runtime dep into the admin bundle).
function emitLocaleModule(lang, table) {
  return [
    fileBanner(),
    '',
    "import type { AdminTranslations } from '../i18n.en';",
    '',
    `export const ${lang}: AdminTranslations = ${JSON.stringify(table, null, 2)};`,
    '',
  ].join('\n');
}

// en_XA: the dev-only ADMIN pseudo-locale. Operators are users, so the admin dashboard
// gets the same literal-surfacing tool as the game. Every admin `en` value
// accent-pushed and bracketed with {placeholders} preserved. The barrel re-exports it,
// but it is NOT a member of translations / LOCALE_LOADERS / SUPPORTED_LANGUAGES, so it
// never enters the admin supportedLanguages, the operator language list, or the admin
// release gate; the admin runtime loads it only behind a dev gate (?lang=en_XA on a
// non-release build) and a production build tree-shakes it out via the
// import.meta.env.PROD guard in src/admin/i18n.ts.
function emitEnXaModule(enXA) {
  return [
    fileBanner(),
    '',
    "import type { AdminTranslations } from '../i18n.en';",
    '',
    `export const en_XA: AdminTranslations = ${JSON.stringify(enXA, null, 2)};`,
    '',
  ].join('\n');
}

// Per-locale keys with NO real translation in the source overlay: the dense table
// carries the English FILL for each. The admin t() renders that English on a
// non-release build and HARD-FAILS on a release build (the release gate asserts this
// set is empty). Dialect-aware; `en` is the source, never pending. Mirrors
// scripts/i18n_scan.mjs `providedByLang` so build + registry agree.
function emitPendingModule(pending) {
  return [
    fileBanner(),
    '',
    'export const pending: Record<string, readonly string[]> = ' +
      JSON.stringify(pending, null, 2) +
      ';',
    '',
  ].join('\n');
}

// Per-locale dynamic-import thunks - parity scaffolding only; the admin runtime stays
// static. `en` is the eager base and en_XA is the dev-only pseudo-locale, so neither
// gets a loader. SUPPORTED_LANGUAGES mirrors the runtime `translations` key set
// (en + the 13 non-en locales, NOT en_XA). Nothing imports this module.
function emitLoadersModule(locales) {
  const lines = [fileBanner(), '', 'export const LOCALE_LOADERS = {'];
  for (const lang of locales) {
    if (lang === 'en') continue; // en is eager; en_XA is excluded by construction
    lines.push(`  ${lang}: () => import('./${lang}'),`);
  }
  lines.push('};');
  lines.push('');
  lines.push(
    `export const SUPPORTED_LANGUAGES = [${locales.map((l) => `'${l}'`).join(', ')}] as const;`,
  );
  lines.push('');
  return lines.join('\n');
}

// The back-compat barrel. Re-exports every dense ADMIN locale slice + en_XA + pending
// and assembles the runtime `translations` map. The key order is the LOCALES list, so
// Object.keys(translations) is unchanged. Preserves the EXACT import surface
// src/admin/i18n.ts and the tests expect (directory-index resolution of
// './i18n.resolved.generated' -> index.ts under moduleResolution "Bundler").
function emitBarrel(locales) {
  const lines = [fileBanner(), ''];
  for (const lang of locales) lines.push(`import { ${lang} } from './${lang}';`);
  lines.push('');
  lines.push(`export { ${locales.join(', ')} };`);
  lines.push("export { en_XA } from './en_XA';");
  lines.push("export { pending } from './pending';");
  lines.push('');
  lines.push('export const translations = {');
  for (const lang of locales) lines.push(`  ${lang},`);
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

function computePending(enKeys, locales) {
  const pending = {};
  for (const lang of LOCALES) {
    if (lang === 'en') continue;
    const provided = new Set();
    const own = locales[lang] || {};
    for (const k of Object.keys(own)) if (isPresent(own[k])) provided.add(k);
    const base = DIALECT_BASE[lang];
    if (base === 'en') {
      for (const k of enKeys) provided.add(k); // English dialect inherits every key
    } else if (base) {
      const baseOverlay = locales[base] || {};
      for (const k of Object.keys(baseOverlay)) if (isPresent(baseOverlay[k])) provided.add(k);
    }
    pending[lang] = enKeys.filter((k) => !provided.has(k)).sort();
  }
  return pending;
}

// Write a { filename -> contents } map into `dir` ATOMICALLY (per-file temp + rename)
// and prune orphan *.ts. Mirrors scripts/i18n_build.mjs writeModuleDir: an atomic
// same-dir replace keeps every slice path continuously present, so a concurrent reader
// resolving './en_XA' through the barrel never sees it missing (a bare rmSync(dir)
// would create that gap), and a removed locale leaves no orphan. The sweep also
// removes any stale *.ts.tmp left by a crashed run (it never ends in plain ".ts"),
// so a crash leftover cannot be committed. Returns total bytes.
function writeModuleDir(dir, modules) {
  mkdirSync(dir, { recursive: true });
  let totalBytes = 0;
  for (const [name, text] of Object.entries(modules)) {
    const dest = path.join(dir, name);
    const tmp = `${dest}.tmp`;
    writeFileSync(tmp, text);
    renameSync(tmp, dest);
    totalBytes += Buffer.byteLength(text, 'utf8');
  }
  const keep = new Set(Object.keys(modules));
  for (const entry of readdirSync(dir)) {
    if ((entry.endsWith('.ts') || entry.endsWith('.ts.tmp')) && !keep.has(entry)) {
      rmSync(path.join(dir, entry), { force: true });
    }
  }
  return totalBytes;
}

async function main() {
  const locales = await loadLocales();
  const en = locales.en;
  const enKeys = Object.keys(en);
  const enKeySet = new Set(enKeys);

  // Fail loud on a phantom overlay key (one not in the English base). The flat
  // resolve below would otherwise smuggle it into the dense table and break the
  // `: AdminTranslations` excess-property contract. (Runtime backstop for the same
  // invariant tests/i18n_admin_catalog.test.ts asserts.)
  for (const lang of LOCALES) {
    if (lang === 'en') continue;
    for (const k of Object.keys(locales[lang] || {})) {
      if (!enKeySet.has(k)) {
        throw new Error(
          `i18n:admin: overlay "${lang}" has key "${k}" not present in the admin en base (typo/stale?)`,
        );
      }
    }
  }

  const resolved = {};
  for (const lang of LOCALES) {
    const out = { ...en };
    if (lang !== 'en') {
      const baseLocale = DIALECT_BASE[lang];
      if (baseLocale && baseLocale !== 'en') Object.assign(out, locales[baseLocale]);
      Object.assign(out, locales[lang]);
    }
    resolved[lang] = out;
  }
  const pending = computePending(enKeys, locales);
  // Generate en_XA from the resolved (dense) admin `en` and emit it as a separate
  // dev-only export (never in `translations`).
  const enXA = pseudoLocalize(resolved.en);

  // Compute every module fully in memory FIRST, then write the directory atomically
  // (see writeModuleDir).
  const modules = {};
  for (const lang of LOCALES) modules[`${lang}.ts`] = emitLocaleModule(lang, resolved[lang]);
  modules['en_XA.ts'] = emitEnXaModule(enXA);
  modules['pending.ts'] = emitPendingModule(pending);
  modules['loaders.ts'] = emitLoadersModule(LOCALES);
  modules['index.ts'] = emitBarrel(LOCALES);

  const totalBytes = writeModuleDir(OUT_DIR, modules);
  const pendingTotal = Object.values(pending).reduce((n, ks) => n + ks.length, 0);
  console.log(
    `generated ${path.relative(root, OUT_DIR)}/ (${LOCALES.length} locales + en_XA pseudo + barrel + loaders + pending, ` +
      `${enKeys.length} keys, pending=${pendingTotal}, ${totalBytes} bytes)`,
  );
}

await main();
