// The Book of Deeds v1 catalog: data-as-code, one DeedDef per deed. No engine
// logic lives here; the evaluator is src/sim/deeds.ts. Names, descs, and
// reward title/border strings are English content re-localized at the client
// boundary (the sim never emits deed text, only ids).
//
// DEED_ORDER is append-only, the QUEST_ORDER determinism contract: append new
// deeds at the END of the table and never reorder or remove an entry (ids are
// persisted in character saves and, later, on Steam, where API names are
// stable forever).

import type { DeedDef } from '../types';

// The current content era. Bumped ONLY by the maintainer at era boundaries;
// feats gated on an era stay visible afterward as history markers and a
// sibling feat is minted for the new era.
export const DEEDS_ERA = 'first_era';

// feat_book_complete is the one dynamic meta: every non-feat, non-hidden deed
// in the live catalog (recomputed per content release by construction, which
// is why it carries 0 Renown and feat status). Populated below, after the
// table literal, so it always matches the shipped catalog exactly.
const BOOK_COMPLETE_REQUIREMENTS: string[] = [];

export const DEEDS: Record<string, DeedDef> = {
  prog_first_steps: {
    id: 'prog_first_steps',
    name: 'First Steps',
    desc: 'Reach level 2 and take your first step on a long road.',
    category: 'progression',
    renown: 5,
    trigger: { kind: 'level', level: 2 },
  },
  prog_finding_your_feet: {
    id: 'prog_finding_your_feet',
    name: 'Finding Your Feet',
    desc: 'Reach level 5; the wilds already look a little smaller.',
    category: 'progression',
    renown: 5,
    trigger: { kind: 'level', level: 5 },
  },
  prog_double_digits: {
    id: 'prog_double_digits',
    name: 'Double Digits',
    desc: 'Reach level 10 and unlock your talents.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'level', level: 10 },
  },
  prog_the_long_middle: {
    id: 'prog_the_long_middle',
    name: 'The Long Middle',
    desc: 'Reach level 15.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'level', level: 15 },
  },
  prog_level_cap: {
    id: 'prog_level_cap',
    name: 'The View From the Top',
    desc: 'Reach level 20, the level cap.',
    category: 'progression',
    renown: 25,
    trigger: { kind: 'level', level: 20 },
  },
  prog_well_rested: {
    id: 'prog_well_rested',
    name: 'Well Rested',
    desc: 'Settle in at an inn until you have earned rested experience.',
    category: 'progression',
    renown: 5,
    trigger: { kind: 'flag', flag: 'hasRestedXp' },
  },
  prog_talented: {
    id: 'prog_talented',
    name: 'A Point Well Spent',
    desc: 'Spend your first talent point.',
    category: 'progression',
    renown: 5,
    trigger: { kind: 'meter', meter: 'talentPoints', amount: 1 },
  },
  prog_specialized: {
    id: 'prog_specialized',
    name: 'Declaration of Intent',
    desc: 'Choose a specialization and learn its signature ability.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'flag', flag: 'talentSpecChosen' },
  },
  prog_deep_roots: {
    id: 'prog_deep_roots',
    name: 'Deep Roots',
    desc: 'Spend a talent point in a final-row talent.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'flag', flag: 'talentCapstone' },
  },
  prog_full_build: {
    id: 'prog_full_build',
    name: 'The Full Eleven',
    desc: 'Spend all eleven talent points on a single build.',
    category: 'progression',
    renown: 25,
    trigger: { kind: 'meter', meter: 'talentPoints', amount: 11 },
  },
  prog_veteran: {
    id: 'prog_veteran',
    name: 'Veteran',
    desc: 'Earn 250,000 lifetime experience.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'lifetimeXp', amount: 250000 },
    reward: { kind: 'title', text: 'Veteran' },
  },
  prog_champion: {
    id: 'prog_champion',
    name: 'Champion',
    desc: 'Earn 500,000 lifetime experience.',
    category: 'progression',
    renown: 25,
    trigger: { kind: 'lifetimeXp', amount: 500000 },
    reward: { kind: 'title', text: 'Champion' },
  },
  prog_paragon: {
    id: 'prog_paragon',
    name: 'Paragon',
    desc: 'Earn 1,000,000 lifetime experience.',
    category: 'progression',
    renown: 25,
    trigger: { kind: 'lifetimeXp', amount: 1000000 },
    reward: { kind: 'title', text: 'Paragon' },
  },
  prog_mythic: {
    id: 'prog_mythic',
    name: 'Mythic',
    desc: 'Earn 2,500,000 lifetime experience.',
    category: 'progression',
    renown: 50,
    trigger: { kind: 'lifetimeXp', amount: 2500000 },
    reward: { kind: 'title', text: 'Mythic' },
  },
  prog_eternal: {
    id: 'prog_eternal',
    name: 'Eternal',
    desc: 'Earn 5,000,000 lifetime experience.',
    category: 'progression',
    renown: 50,
    trigger: { kind: 'lifetimeXp', amount: 5000000 },
    reward: { kind: 'title', text: 'Eternal' },
  },
  prog_prestige: {
    id: 'prog_prestige',
    name: 'Begin Again',
    desc: 'Reach the level cap, fill the bar once more, and claim prestige rank 1.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'meter', meter: 'prestigeRank', amount: 1 },
  },
  prog_prestige_5: {
    id: 'prog_prestige_5',
    name: 'Old Habits',
    desc: 'Reach prestige rank 5.',
    category: 'progression',
    renown: 25,
    trigger: { kind: 'meter', meter: 'prestigeRank', amount: 5 },
  },
  prog_prestige_10: {
    id: 'prog_prestige_10',
    name: 'Perpetual Motion',
    desc: 'Reach prestige rank 10.',
    category: 'progression',
    renown: 50,
    trigger: { kind: 'meter', meter: 'prestigeRank', amount: 10 },
    reward: { kind: 'border', slug: 'prestige_laurels' },
  },
  prog_first_harvest: {
    id: 'prog_first_harvest',
    name: 'Fruits of the Field',
    desc: 'Harvest your first gathering node.',
    category: 'progression',
    renown: 5,
    trigger: { kind: 'gathering', amount: 1 },
  },
  prog_mining_100: {
    id: 'prog_mining_100',
    name: 'Ore in the Blood',
    desc: 'Reach 100 Mining proficiency.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'gathering', professionId: 'mining', amount: 100 },
  },
  prog_logging_100: {
    id: 'prog_logging_100',
    name: 'Heartwood Hewer',
    desc: 'Reach 100 Logging proficiency.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'gathering', professionId: 'logging', amount: 100 },
  },
  prog_herbalism_100: {
    id: 'prog_herbalism_100',
    name: 'Master of the Meadow',
    desc: 'Reach 100 Herbalism proficiency.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'gathering', professionId: 'herbalism', amount: 100 },
  },
  prog_master_gatherer: {
    id: 'prog_master_gatherer',
    name: 'Master Gatherer',
    desc: 'Reach 100 proficiency in Mining, Logging, and Herbalism.',
    category: 'progression',
    renown: 25,
    trigger: { kind: 'gathering', amount: 100, count: 3 },
  },
  prog_first_craft: {
    id: 'prog_first_craft',
    name: 'Made By Hand',
    desc: 'Complete your first successful craft.',
    category: 'progression',
    renown: 5,
    trigger: { kind: 'stat', stat: 'craftsPerformed', count: 1 },
  },
  prog_craft_specialist: {
    id: 'prog_craft_specialist',
    name: 'Trade Secrets',
    desc: 'Reach 75 skill in any one craft and unlock its specialization perks.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'craftSkill', level: 75 },
  },
  prog_around_the_ring: {
    id: 'prog_around_the_ring',
    name: 'Around the Ring',
    desc: 'Reach 25 skill in five different crafts.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'craftSkill', level: 25, count: 5 },
  },
  cmb_first_blood: {
    id: 'cmb_first_blood',
    name: 'First Blood',
    desc: 'Defeat your first enemy.',
    category: 'combat',
    renown: 5,
    trigger: { kind: 'stat', stat: 'kills', count: 1 },
  },
  cmb_slayer: {
    id: 'cmb_slayer',
    name: 'Slayer',
    desc: 'Defeat 1,000 enemies.',
    category: 'combat',
    renown: 10,
    trigger: { kind: 'stat', stat: 'kills', count: 1000 },
  },
  cmb_legion_of_one: {
    id: 'cmb_legion_of_one',
    name: 'Legion of One',
    desc: 'Defeat 10,000 enemies.',
    category: 'combat',
    renown: 25,
    trigger: { kind: 'stat', stat: 'kills', count: 10000 },
  },
  cmb_heavy_hitter: {
    id: 'cmb_heavy_hitter',
    name: 'Heavy Hitter',
    desc: 'Deal 500,000 total damage.',
    category: 'combat',
    renown: 10,
    trigger: { kind: 'stat', stat: 'damageDealt', count: 500000 },
  },
  cmb_critical_eye: {
    id: 'cmb_critical_eye',
    name: 'Critical Eye',
    desc: 'Land 500 critical strikes.',
    category: 'combat',
    renown: 10,
    trigger: { kind: 'stat', stat: 'crits', count: 500 },
  },
  cmb_giantslayer: {
    id: 'cmb_giantslayer',
    name: 'Giantslayer',
    desc: 'Land the killing blow on an enemy at least five levels above you.',
    category: 'combat',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  cmb_first_fall: {
    id: 'cmb_first_fall',
    name: 'Dust Yourself Off',
    desc: 'Die for the first time; it happens to the best of us.',
    category: 'combat',
    renown: 5,
    trigger: { kind: 'stat', stat: 'deaths', count: 1 },
  },

  dgn_hollow_crypt: {
    id: 'dgn_hollow_crypt',
    name: 'Cryptbreaker',
    desc: 'Defeat Morthen the Gravecaller in the Hollow Crypt.',
    category: 'dungeon',
    renown: 5,
    trigger: { kind: 'dungeonClears', dungeonId: 'hollow_crypt', count: 1 },
  },
  dgn_sunken_bastion: {
    id: 'dgn_sunken_bastion',
    name: 'Fogbinder Unbound',
    desc: 'Defeat Vael the Fogbinder in the Sunken Bastion.',
    category: 'dungeon',
    renown: 5,
    trigger: { kind: 'dungeonClears', dungeonId: 'sunken_bastion', count: 1 },
  },
  dgn_drowned_temple: {
    id: 'dgn_drowned_temple',
    name: 'Drowning the Moon',
    desc: 'Defeat Ysolei, Avatar of the Drowned Moon, in the Drowned Temple.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'dungeonClears', dungeonId: 'drowned_temple', count: 1 },
  },
  dgn_gravewyrm_sanctum: {
    id: 'dgn_gravewyrm_sanctum',
    name: 'The Wyrm Below',
    desc: 'Defeat Korzul the Gravewyrm in Gravewyrm Sanctum.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'dungeonClears', dungeonId: 'gravewyrm_sanctum', count: 1 },
  },
  dgn_hollow_crypt_heroic: {
    id: 'dgn_hollow_crypt_heroic',
    name: 'Heroic: The Hollow Crypt',
    desc: 'Defeat Morthen the Gravecaller in the Hollow Crypt on Heroic difficulty.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'dungeonClears', dungeonId: 'hollow_crypt', difficulty: 'heroic', count: 1 },
  },
  dgn_sunken_bastion_heroic: {
    id: 'dgn_sunken_bastion_heroic',
    name: 'Heroic: The Sunken Bastion',
    desc: 'Defeat Vael the Fogbinder in the Sunken Bastion on Heroic difficulty.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'dungeonClears', dungeonId: 'sunken_bastion', difficulty: 'heroic', count: 1 },
  },
  dgn_drowned_temple_heroic: {
    id: 'dgn_drowned_temple_heroic',
    name: 'Heroic: The Drowned Temple',
    desc: 'Defeat Ysolei, Avatar of the Drowned Moon, in the Drowned Temple on Heroic difficulty.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'dungeonClears', dungeonId: 'drowned_temple', difficulty: 'heroic', count: 1 },
  },
  dgn_gravewyrm_sanctum_heroic: {
    id: 'dgn_gravewyrm_sanctum_heroic',
    name: 'Heroic: Gravewyrm Sanctum',
    desc: 'Defeat Korzul the Gravewyrm in Gravewyrm Sanctum on Heroic difficulty.',
    category: 'dungeon',
    renown: 10,
    trigger: {
      kind: 'dungeonClears',
      dungeonId: 'gravewyrm_sanctum',
      difficulty: 'heroic',
      count: 1,
    },
  },
  dgn_nythraxis: {
    id: 'dgn_nythraxis',
    name: 'Scourge No More',
    desc: 'Defeat Nythraxis, Scourge of Thornpeak, beyond the sealed royal door.',
    category: 'dungeon',
    renown: 25,
    trigger: { kind: 'dungeonClears', dungeonId: 'nythraxis_boss_arena', count: 1 },
  },
  dgn_nythraxis_heroic: {
    id: 'dgn_nythraxis_heroic',
    name: 'Heroic: Scourge No More',
    desc: 'Defeat Nythraxis, Scourge of Thornpeak, on Heroic difficulty.',
    category: 'dungeon',
    renown: 25,
    trigger: {
      kind: 'dungeonClears',
      dungeonId: 'nythraxis_boss_arena',
      difficulty: 'heroic',
      count: 1,
    },
  },
  dgn_thornpeak_rounds: {
    id: 'dgn_thornpeak_rounds',
    name: 'Making the Rounds',
    desc: 'Clear the Hollow Crypt, the Sunken Bastion, the Drowned Temple, and Gravewyrm Sanctum.',
    category: 'dungeon',
    renown: 10,
    trigger: {
      kind: 'meta',
      deedIds: [
        'dgn_hollow_crypt',
        'dgn_sunken_bastion',
        'dgn_drowned_temple',
        'dgn_gravewyrm_sanctum',
      ],
    },
  },
  dgn_deepward: {
    id: 'dgn_deepward',
    name: 'Deepward',
    desc: 'Conquer every dungeon, the raid, and both delves on Heroic difficulty.',
    category: 'dungeon',
    renown: 50,
    trigger: {
      kind: 'meta',
      deedIds: [
        'dgn_hollow_crypt_heroic',
        'dgn_sunken_bastion_heroic',
        'dgn_drowned_temple_heroic',
        'dgn_gravewyrm_sanctum_heroic',
        'dgn_nythraxis_heroic',
        'dlv_reliquary_heroic',
        'dlv_litany_heroic',
      ],
    },
    reward: { kind: 'border', slug: 'deepward' },
  },
  dgn_mark_circuit: {
    id: 'dgn_mark_circuit',
    name: 'The Full Circuit',
    desc: 'Earn Heroic Marks from all four Heroic dungeons in a single day.',
    category: 'dungeon',
    renown: 25,
    trigger: { kind: 'flag', flag: 'heroicMarkCircuit' },
  },
  dgn_boss_clears_50: {
    id: 'dgn_boss_clears_50',
    name: 'Fifty Doors Down',
    desc: 'Defeat 50 dungeon end bosses.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'stat', stat: 'dungeonFinalBossKills', count: 50 },
  },
  dgn_morthen_flawless: {
    id: 'dgn_morthen_flawless',
    name: 'No Bones About It',
    desc: 'Defeat Morthen the Gravecaller on Heroic difficulty without any party member dying.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  dgn_morthen_trio: {
    id: 'dgn_morthen_trio',
    name: 'Three Against the Grave',
    desc: 'Defeat Morthen the Gravecaller with three or fewer players.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  dgn_olen_arc: {
    id: 'dgn_olen_arc',
    name: 'Sidestep the Reaper',
    desc: 'Defeat Knight-Commander Olen without his Reaping Arc striking anyone but his current target.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  dgn_vael_thralls: {
    id: 'dgn_vael_thralls',
    name: 'No Thrall of Mine',
    desc: 'Defeat Vael the Fogbinder with every Drowned Thrall he calls already slain.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  dgn_ysolei_moonspawn: {
    id: 'dgn_ysolei_moonspawn',
    name: 'Every Last Moonspawn',
    desc: 'Defeat Ysolei with every Moonspawn she calls already slain.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  dgn_ysolei_flawless: {
    id: 'dgn_ysolei_flawless',
    name: 'Dry Eyes',
    desc: 'Defeat Ysolei, Avatar of the Drowned Moon, on Heroic difficulty without any party member dying.',
    category: 'dungeon',
    renown: 25,
    trigger: { kind: 'manual' },
  },
  dgn_velkhar_bonewalkers: {
    id: 'dgn_velkhar_bonewalkers',
    name: 'Stay Buried',
    desc: 'Defeat Grand Necromancer Velkhar with every Raised Bonewalker destroyed before he falls.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  dgn_korzul_flawless: {
    id: 'dgn_korzul_flawless',
    name: 'Wyrmfeller',
    desc: 'Defeat Korzul the Gravewyrm on Heroic difficulty without any party member dying.',
    category: 'dungeon',
    renown: 25,
    trigger: { kind: 'manual' },
    reward: { kind: 'title', text: 'Wyrmfeller' },
  },
  dgn_sanctum_speed: {
    id: 'dgn_sanctum_speed',
    name: 'Sanctum Sprint',
    desc: 'Defeat Korzul the Gravewyrm within 15 minutes of your party claiming Gravewyrm Sanctum.',
    category: 'dungeon',
    renown: 25,
    trigger: { kind: 'manual' },
  },
  dgn_nythraxis_gravebreaker: {
    id: 'dgn_nythraxis_gravebreaker',
    name: 'Kneel to No King',
    desc: 'Defeat Nythraxis with Gravebreaker never striking anyone but his current target.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  dgn_nythraxis_wardens: {
    id: 'dgn_nythraxis_wardens',
    name: 'Keepers of the Wardstones',
    desc: 'Defeat Nythraxis with every Deathless Rage broken before it lands.',
    category: 'dungeon',
    renown: 25,
    trigger: { kind: 'manual' },
  },
  dgn_nythraxis_deathless: {
    id: 'dgn_nythraxis_deathless',
    name: 'None More Deathless',
    desc: 'Defeat Nythraxis, Scourge of Thornpeak, on Heroic difficulty without a single raider dying.',
    category: 'dungeon',
    renown: 50,
    trigger: { kind: 'manual' },
    reward: { kind: 'title', text: 'the Deathless' },
  },
  cmb_thunzharr: {
    id: 'cmb_thunzharr',
    name: 'The Mountain Fell',
    desc: 'Bring down Thunzharr, the Waking Peak, at Stormcrag.',
    category: 'combat',
    renown: 25,
    trigger: { kind: 'manual' },
  },
  cmb_thunzharr_unbroken: {
    id: 'cmb_thunzharr_unbroken',
    name: 'Peakbreaker',
    desc: 'Bring down Thunzharr, the Waking Peak, without dying from your first blow to his last breath.',
    category: 'combat',
    renown: 25,
    trigger: { kind: 'manual' },
    reward: { kind: 'title', text: 'Peakbreaker' },
  },
  cmb_thunzharr_ten: {
    id: 'cmb_thunzharr_ten',
    name: 'A Habit of Mountains',
    desc: 'Bring down Thunzharr, the Waking Peak, ten times.',
    category: 'combat',
    renown: 10,
    trigger: { kind: 'stat', stat: 'thunzharrKills', count: 10 },
  },
  dlv_reliquary: {
    id: 'dlv_reliquary',
    name: 'Reliquary Runner',
    desc: 'Clear the Collapsed Reliquary.',
    category: 'delve',
    renown: 5,
    trigger: { kind: 'delveClears', delveId: 'collapsed_reliquary', count: 1 },
  },
  dlv_reliquary_heroic: {
    id: 'dlv_reliquary_heroic',
    name: 'Heroic: The Collapsed Reliquary',
    desc: 'Clear the Collapsed Reliquary on the Heroic tier.',
    category: 'delve',
    renown: 10,
    trigger: { kind: 'delveClears', delveId: 'collapsed_reliquary', tier: 'heroic', count: 1 },
  },
  dlv_litany: {
    id: 'dlv_litany',
    name: 'Hush the Litany',
    desc: 'Clear the Drowned Litany.',
    category: 'delve',
    renown: 5,
    trigger: { kind: 'delveClears', delveId: 'drowned_litany', count: 1 },
  },
  dlv_litany_heroic: {
    id: 'dlv_litany_heroic',
    name: 'Heroic: The Drowned Litany',
    desc: 'Clear the Drowned Litany on the Heroic tier.',
    category: 'delve',
    renown: 10,
    trigger: { kind: 'delveClears', delveId: 'drowned_litany', tier: 'heroic', count: 1 },
  },
  dlv_lore_journal: {
    id: 'dlv_lore_journal',
    name: 'Marginalia',
    desc: 'Unlock all five entries of the delve journal.',
    category: 'delve',
    renown: 10,
    trigger: { kind: 'meter', meter: 'delveLoreCount', amount: 5 },
  },
  dlv_companion_max: {
    id: 'dlv_companion_max',
    name: 'A Friend in the Deep',
    desc: 'Raise a delve companion to her highest rank.',
    category: 'delve',
    renown: 10,
    trigger: { kind: 'meter', meter: 'companionRankBest', amount: 3 },
  },
  dlv_companions_both: {
    id: 'dlv_companions_both',
    name: 'Both Lanterns Lit',
    desc: 'Raise both delve companions, Acolyte Tessa and Edda Reedhand, to their highest rank.',
    category: 'delve',
    renown: 25,
    trigger: { kind: 'flag', flag: 'companionsBothMax' },
  },
  dlv_clears_50: {
    id: 'dlv_clears_50',
    name: 'Fifty Fathoms',
    desc: 'Complete 50 delve runs.',
    category: 'delve',
    renown: 10,
    trigger: { kind: 'delveClears', count: 50 },
  },
  dlv_solo_heroic: {
    id: 'dlv_solo_heroic',
    name: "Two's a Crowd",
    desc: 'Clear a Heroic-tier delve with no other player, just you and your companion.',
    category: 'delve',
    renown: 25,
    trigger: { kind: 'manual' },
  },
  dlv_tumbler_premium: {
    id: 'dlv_tumbler_premium',
    name: "The Tumbler's Path, Mastered",
    desc: 'Open a warded reliquary chest at the highest ante, flawless on your only try.',
    category: 'delve',
    renown: 25,
    trigger: { kind: 'manual' },
  },
  dlv_rite_flawless: {
    id: 'dlv_rite_flawless',
    name: 'Word-Perfect',
    desc: 'Complete the Drowned Reliquary Rite without a single mistake.',
    category: 'delve',
    renown: 25,
    trigger: { kind: 'manual' },
  },
  dlv_varric_ringers: {
    id: 'dlv_varric_ringers',
    name: 'The Bells Fall Silent',
    desc: 'Defeat Deacon Varric with every Funeral Ringer he raises already slain.',
    category: 'delve',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  dlv_nhalia_bells: {
    id: 'dlv_nhalia_bells',
    name: 'Bellstiller',
    desc: 'Defeat Sister Nhalia, the Drowned Canticle, without any party member struck by a Tolling Bell.',
    category: 'delve',
    renown: 25,
    trigger: { kind: 'manual' },
    reward: { kind: 'title', text: 'Bellstiller' },
  },

  chr_vale_chapter_i: {
    id: 'chr_vale_chapter_i',
    name: 'Vale Chronicle, Chapter I',
    desc: "Finish the first chapter of Saul's chronicle: Eastbrook's opening errands, the lay of the Vale, and a first taste of its trades.",
    category: 'chronicle',
    renown: 5,
    trigger: {
      kind: 'meta',
      deedIds: ['exp_vale_wayfarer', 'chr_vale_gatherer', 'chr_vale_first_cast'],
      questIds: ['q_wolves', 'q_boars', 'q_spiders', 'q_greyjaw'],
    },
  },
  chr_vale_chapter_ii: {
    id: 'chr_vale_chapter_ii',
    name: 'Vale Chronicle, Chapter II',
    desc: "Finish the second chapter of Saul's chronicle: bandits, murlocs, and mine vermin put down, the Sowfield played, and the Reliquary braved.",
    category: 'chronicle',
    renown: 10,
    trigger: {
      kind: 'meta',
      deedIds: ['chr_vale_packbreaker', 'chr_vale_cup_debut', 'dlv_reliquary'],
      questIds: ['q_murlocs', 'q_supplies', 'q_bandits', 'q_ringleader', 'q_mine', 'q_bones'],
    },
  },
  chr_vale_chapter_iii: {
    id: 'chr_vale_chapter_iii',
    name: 'Chronicle of the Vale',
    desc: "See the Vale's whole story through: the Gravecaller unmasked, the Hollow Crypt cleansed, and every named terror of the Vale laid low.",
    category: 'chronicle',
    renown: 25,
    trigger: {
      kind: 'meta',
      deedIds: ['chr_vale_chapter_i', 'chr_vale_chapter_ii', 'chr_vale_rares', 'dgn_hollow_crypt'],
      questIds: [
        'q_whispers',
        'q_names_of_the_dead',
        'q_silence_the_call',
        'q_rite',
        'q_sexton',
        'q_hollow',
        'q_gravecallers_trail',
        'q_mogger',
      ],
    },
    reward: { kind: 'title', text: 'of the Vale' },
  },
  chr_vale_gatherer: {
    id: 'chr_vale_gatherer',
    name: 'Living off the Land',
    desc: 'Harvest an ore vein, a wood stand, and an herb patch in Eastbrook Vale.',
    category: 'chronicle',
    renown: 5,
    trigger: {
      kind: 'visits',
      markIds: [
        'gather:eastbrook_vale:ore',
        'gather:eastbrook_vale:wood',
        'gather:eastbrook_vale:herb',
      ],
    },
  },
  chr_vale_first_cast: {
    id: 'chr_vale_first_cast',
    name: 'Something in Mirror Lake',
    desc: 'Catch a fish from the waters of Eastbrook Vale.',
    category: 'chronicle',
    renown: 5,
    trigger: { kind: 'visit', markId: 'fish:eastbrook_vale' },
  },
  chr_vale_packbreaker: {
    id: 'chr_vale_packbreaker',
    name: 'Packbreaker',
    desc: 'Slay 3 Forest Wolves within 10 seconds.',
    category: 'chronicle',
    renown: 5,
    trigger: { kind: 'manual' },
  },
  chr_vale_cup_debut: {
    id: 'chr_vale_cup_debut',
    name: 'Copper Pail Contender',
    desc: 'Take the field and touch the ball in a Vale Cup match at the Sowfield.',
    category: 'chronicle',
    renown: 5,
    trigger: { kind: 'manual' },
  },
  chr_vale_rares: {
    id: 'chr_vale_rares',
    name: 'Terrors of the Vale',
    desc: 'Slay the five named terrors of Eastbrook Vale: Old Greyjaw, Mogger, Grix the Tunnelking, Captain Verlan, and Wraithbinder Maldrec.',
    category: 'chronicle',
    renown: 10,
    trigger: {
      kind: 'visits',
      markIds: [
        'slain:old_greyjaw',
        'slain:mogger',
        'slain:grix_the_tunnelking',
        'slain:captain_verlan',
        'slain:wraithbinder_maldrec',
      ],
    },
  },
  chr_marsh_chapter_i: {
    id: 'chr_marsh_chapter_i',
    name: 'Marsh Chronicle, Chapter I',
    desc: "Finish the first chapter of Osric Fenn's chronicle: answer the Fenbridge muster, secure the causeway, and learn the shape of the fen.",
    category: 'chronicle',
    renown: 5,
    trigger: {
      kind: 'meta',
      deedIds: ['exp_marsh_wayfarer', 'chr_marsh_gatherer'],
      questIds: [
        'q_fenbridge_muster',
        'q_prowlers',
        'q_prowler_pelts',
        'q_fen_supplies',
        'q_deepfen',
      ],
    },
  },
  chr_marsh_chapter_ii: {
    id: 'chr_marsh_chapter_ii',
    name: 'Marsh Chronicle, Chapter II',
    desc: "Finish the second chapter of Osric Fenn's chronicle: the widows burned out, the drowned laid to rest, the Codfather landed, and the Litany braved.",
    category: 'chronicle',
    renown: 10,
    trigger: {
      kind: 'meta',
      deedIds: ['chr_marsh_unburst', 'dlv_litany'],
      questIds: [
        'q_idols',
        'q_deepfen_purge',
        'q_widows',
        'q_broodmother',
        'q_drowned',
        'q_drowned_censers',
        'q_no_rest',
        'q_the_codfather',
      ],
    },
  },
  chr_marsh_chapter_iii: {
    id: 'chr_marsh_chapter_iii',
    name: 'Chronicle of the Mirefen',
    desc: "See the fen's whole story through: the cult camp broken, the Fogbinder silenced in the Sunken Bastion, and every named terror of the mist laid low.",
    category: 'chronicle',
    renown: 25,
    trigger: {
      kind: 'meta',
      deedIds: [
        'chr_marsh_chapter_i',
        'chr_marsh_chapter_ii',
        'chr_marsh_hush_the_mending',
        'chr_marsh_rares',
        'dgn_sunken_bastion',
      ],
      questIds: [
        'q_trolls',
        'q_troll_fetishes',
        'q_grubjaw',
        'q_cult_camp',
        'q_summoners',
        'q_deacon',
        'q_bastion_door',
        'q_olen',
        'q_mistcaller',
      ],
    },
    reward: { kind: 'title', text: 'of the Mirefen' },
  },
  chr_marsh_gatherer: {
    id: 'chr_marsh_gatherer',
    name: 'Fenbridge Foraging',
    desc: 'Harvest an ore vein, a wood stand, and an herb patch in Mirefen Marsh.',
    category: 'chronicle',
    renown: 5,
    trigger: {
      kind: 'visits',
      markIds: [
        'gather:mirefen_marsh:ore',
        'gather:mirefen_marsh:wood',
        'gather:mirefen_marsh:herb',
      ],
    },
  },
  chr_marsh_unburst: {
    id: 'chr_marsh_unburst',
    name: 'Do Not Stand in the Spores',
    desc: 'Slay 8 Bog Bloats without being caught in their Caustic Spores burst.',
    category: 'chronicle',
    renown: 10,
    trigger: { kind: 'stat', stat: 'bloatCleanKills', count: 8 },
  },
  chr_marsh_hush_the_mending: {
    id: 'chr_marsh_hush_the_mending',
    name: 'Silence the Mending',
    desc: 'In the Gravecaller encampment, slay a Gravecaller Mender before any of the cultists it tends.',
    category: 'chronicle',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  chr_marsh_rares: {
    id: 'chr_marsh_rares',
    name: 'Named in the Mist',
    desc: 'Slay the three named terrors of Mirefen Marsh: Mirejaw the Ravenous, Sloomtooth the Drowned, and Sister Nhalia.',
    category: 'chronicle',
    renown: 10,
    trigger: {
      kind: 'visits',
      markIds: [
        'slain:mirejaw_the_ravenous',
        'slain:sloomtooth_the_drowned',
        'slain:sister_nhalia',
      ],
    },
  },
  chr_peaks_chapter_i: {
    id: 'chr_peaks_chapter_i',
    name: 'Peaks Chronicle, Chapter I',
    desc: "Finish the first chapter of Zenzie's chronicle: clear the ridge road, empty the burrows, and learn every path Highwatch guards.",
    category: 'chronicle',
    renown: 5,
    trigger: {
      kind: 'meta',
      deedIds: ['exp_peaks_wayfarer', 'chr_peaks_sparring'],
      questIds: [
        'q_highwatch_summons',
        'q_stalkers',
        'q_stalker_pelts',
        'q_stalkers_return',
        'q_stalker_cloaks',
        'q_old_cragmaw',
        'q_kobold_tunnels',
        'q_glowing_wax',
      ],
    },
  },
  chr_peaks_chapter_ii: {
    id: 'chr_peaks_chapter_ii',
    name: 'Peaks Chronicle, Chapter II',
    desc: "Finish the second chapter of Zenzie's chronicle: break Drogmar's war-camp, read the waking storm, and stand where the Glimmermere glows.",
    category: 'chronicle',
    renown: 10,
    trigger: {
      kind: 'meta',
      deedIds: ['chr_peaks_glimmer_cast', 'chr_peaks_moongate', 'chr_peaks_waking_witness'],
      questIds: [
        'q_ogre_edges',
        'q_ogre_totems',
        'q_ogre_bounty',
        'q_crushers',
        'q_drogmar',
        'q_elementals',
        'q_shard_cores',
        'q_kazzix',
        'q_glimmermere_light',
        'q_tarn_waders',
      ],
    },
  },
  chr_peaks_chapter_iii: {
    id: 'chr_peaks_chapter_iii',
    name: 'Chronicle of Thornpeak',
    desc: "See the mountain's whole story through: the Wyrmcult broken, the Sanctum silenced, the Waking Peak felled, and every named terror of the crags laid low.",
    category: 'chronicle',
    renown: 50,
    trigger: {
      kind: 'meta',
      deedIds: [
        'chr_peaks_chapter_i',
        'chr_peaks_chapter_ii',
        'chr_peaks_rares',
        'dgn_gravewyrm_sanctum',
        'cmb_thunzharr',
      ],
      questIds: [
        'q_zealots',
        'q_cult_orders',
        'q_necromancers',
        'q_revenants',
        'q_revenant_vanguard',
        'q_wyrm_sigils',
        'q_breaking_the_seal',
        'q_voice_below',
        'q_sanctum_gate',
        'q_korgath',
        'q_velkhar',
        'q_gravewyrm',
      ],
    },
    reward: { kind: 'title', text: 'of Thornpeak' },
  },
  chr_peaks_sparring: {
    id: 'chr_peaks_sparring',
    name: 'Wall Drills',
    desc: 'Deal 1,000 total damage to the training dummy above Highwatch.',
    category: 'chronicle',
    renown: 5,
    trigger: { kind: 'stat', stat: 'dummyDamage', count: 1000 },
  },
  chr_peaks_glimmer_cast: {
    id: 'chr_peaks_glimmer_cast',
    name: 'Cold Water, Colder Light',
    desc: 'Catch a fish from the Glimmermere.',
    category: 'chronicle',
    renown: 5,
    trigger: { kind: 'visit', markId: 'fish:thornpeak_heights' },
  },
  chr_peaks_moongate: {
    id: 'chr_peaks_moongate',
    name: 'Through the Cold Gate',
    desc: 'Step through the moongate on the Glimmermere shore.',
    category: 'chronicle',
    renown: 5,
    trigger: { kind: 'visit', markId: 'dungeon:drowned_temple' },
  },
  chr_peaks_waking_witness: {
    id: 'chr_peaks_waking_witness',
    name: 'The Mountain That Walks',
    desc: 'Lay eyes on Thunzharr, the Waking Peak while he strides the mountain.',
    category: 'chronicle',
    renown: 5,
    trigger: { kind: 'visit', markId: 'witness:thunzharr_waking_peak' },
  },
  chr_peaks_rares: {
    id: 'chr_peaks_rares',
    name: 'Names Cut into the Crag',
    desc: 'Slay the four named terrors of Thornpeak Heights: the Ironvein Foreman, Brutok Skullsmasher, Voskar the Emberwing, and Marrowlord Varkas.',
    category: 'chronicle',
    renown: 10,
    trigger: {
      kind: 'visits',
      markIds: [
        'slain:ironvein_foreman',
        'slain:brutok_skullsmasher',
        'slain:voskar_emberwing',
        'slain:marrowlord_varkas',
      ],
    },
  },

  col_discovery_25: {
    id: 'col_discovery_25',
    name: 'Packrat',
    desc: 'Discover 25 different items (an item counts the first time it ever enters your possession).',
    category: 'collection',
    renown: 5,
    trigger: { kind: 'meter', meter: 'itemsDiscoveredCount', amount: 25 },
  },
  col_discovery_75: {
    id: 'col_discovery_75',
    name: 'Magpie',
    desc: 'Discover 75 different items.',
    category: 'collection',
    renown: 10,
    trigger: { kind: 'meter', meter: 'itemsDiscoveredCount', amount: 75 },
  },
  col_discovery_150: {
    id: 'col_discovery_150',
    name: 'Cabinet of Curiosities',
    desc: 'Discover 150 different items.',
    category: 'collection',
    renown: 25,
    trigger: { kind: 'meter', meter: 'itemsDiscoveredCount', amount: 150 },
    reward: { kind: 'title', text: 'the Curator' },
  },
  col_discovery_250: {
    id: 'col_discovery_250',
    name: 'The Grand Catalogue',
    desc: 'Discover 250 different items.',
    category: 'collection',
    renown: 50,
    trigger: { kind: 'meter', meter: 'itemsDiscoveredCount', amount: 250 },
    reward: { kind: 'border', slug: 'curators_gilt' },
  },
  col_first_rare: {
    id: 'col_first_rare',
    name: 'Something Blue',
    desc: 'Acquire your first item of rare quality.',
    category: 'collection',
    renown: 0,
    trigger: { kind: 'visit', markId: 'quality:rare' },
  },
  col_first_epic: {
    id: 'col_first_epic',
    name: 'Born to the Purple',
    desc: 'Acquire your first item of epic quality.',
    category: 'collection',
    renown: 0,
    trigger: { kind: 'visit', markId: 'quality:epic' },
  },
  col_first_legendary: {
    id: 'col_first_legendary',
    name: 'Orange You Lucky',
    desc: 'Acquire your first item of legendary quality.',
    category: 'collection',
    renown: 0,
    trigger: { kind: 'visit', markId: 'quality:legendary' },
  },
  col_set_vale_arcanist: {
    id: 'col_set_vale_arcanist',
    name: "Vale Arcanist's Regalia",
    desc: "Discover every piece of the Vale Arcanist's Regalia.",
    category: 'collection',
    renown: 0,
    trigger: { kind: 'collectItems', itemIds: ['woven_robe', 'acolytes_circlet', 'silk_sash'] },
  },
  col_set_boundstone_vanguard: {
    id: 'col_set_boundstone_vanguard',
    name: 'Boundstone Vanguard',
    desc: 'Discover every piece of the Boundstone Vanguard.',
    category: 'collection',
    renown: 0,
    trigger: {
      kind: 'collectItems',
      itemIds: ['boundstone_helm', 'boundstone_girdle', 'gravewyrm_gauntlets'],
    },
  },
  col_set_greyjaw_stalker: {
    id: 'col_set_greyjaw_stalker',
    name: "Greyjaw Stalker's Kit",
    desc: "Discover every piece of the Greyjaw Stalker's Kit.",
    category: 'collection',
    renown: 0,
    trigger: {
      kind: 'collectItems',
      itemIds: ['shadow_jerkin', 'greyjaw_hide_boots', 'trail_leggings'],
    },
  },
  col_set_deathlord: {
    id: 'col_set_deathlord',
    name: 'Barrowlord Battlegear',
    desc: 'Discover every piece of the Barrowlord Battlegear.',
    category: 'collection',
    renown: 0,
    trigger: {
      kind: 'collectItems',
      itemIds: [
        'deathlord_warplate',
        'deathlord_legguards',
        'deathlord_sabatons',
        'deathlords_dread_visage',
      ],
    },
  },
  col_set_wyrmshadow: {
    id: 'col_set_wyrmshadow',
    name: 'Nightfang Vestments',
    desc: 'Discover every piece of the Nightfang Vestments.',
    category: 'collection',
    renown: 0,
    trigger: {
      kind: 'collectItems',
      itemIds: [
        'wyrmshadow_harness',
        'wyrmshadow_treads',
        'wyrmshadow_legguards',
        'wyrmshadow_talongrips',
      ],
    },
  },
  col_set_necromancers: {
    id: 'col_set_necromancers',
    name: 'Mournweave Raiment',
    desc: 'Discover every piece of the Mournweave Raiment.',
    category: 'collection',
    renown: 0,
    trigger: {
      kind: 'collectItems',
      itemIds: [
        'necromancers_starshroud',
        'necromancers_soulsteps',
        'necromancers_legwraps',
        'necromancers_soulspire_mantle',
      ],
    },
  },
  col_set_crownforged: {
    id: 'col_set_crownforged',
    name: 'Bonewrought Regalia',
    desc: 'Discover every piece of the Bonewrought Regalia.',
    category: 'collection',
    renown: 0,
    trigger: {
      kind: 'collectItems',
      itemIds: [
        'crownforged_gauntlets',
        'crownforged_girdle',
        'crownforged_dreadhelm',
        'crownforged_warspaulders',
      ],
    },
  },
  col_set_nighttalon: {
    id: 'col_set_nighttalon',
    name: 'Direfang Pelt',
    desc: 'Discover every piece of the Direfang Pelt.',
    category: 'collection',
    renown: 0,
    trigger: {
      kind: 'collectItems',
      itemIds: [
        'nighttalon_grips',
        'nighttalon_waistband',
        'nighttalon_crown',
        'nighttalon_shoulderguards',
      ],
    },
  },
  col_set_soulflame: {
    id: 'col_set_soulflame',
    name: 'Wraithfire Regalia',
    desc: 'Discover every piece of the Wraithfire Regalia.',
    category: 'collection',
    renown: 0,
    trigger: {
      kind: 'collectItems',
      itemIds: ['soulflame_gloves', 'soulflame_cord', 'soulflame_cowl', 'soulflame_mantle'],
    },
  },
  col_set_stormcallers: {
    id: 'col_set_stormcallers',
    name: 'Galecall Vestments',
    desc: 'Discover every piece of the Galecall Vestments.',
    category: 'collection',
    renown: 0,
    trigger: {
      kind: 'collectItems',
      itemIds: [
        'stormcallers_handguards',
        'stormcallers_waistguard',
        'stormcallers_crown',
        'stormcallers_spaulders',
      ],
    },
  },
  col_seven_regalia: {
    id: 'col_seven_regalia',
    name: 'The Sevenfold Wardrobe',
    desc: 'Discover every piece of all seven epic armor families.',
    category: 'collection',
    renown: 0,
    trigger: {
      kind: 'meta',
      deedIds: [
        'col_set_deathlord',
        'col_set_wyrmshadow',
        'col_set_necromancers',
        'col_set_crownforged',
        'col_set_nighttalon',
        'col_set_soulflame',
        'col_set_stormcallers',
      ],
    },
    reward: { kind: 'title', text: 'the Resplendent' },
  },
  col_true_colors: {
    id: 'col_true_colors',
    name: 'True Colors',
    desc: 'Take the field wearing any appearance other than your class default.',
    category: 'collection',
    renown: 0,
    trigger: { kind: 'flag', flag: 'nonDefaultSkin' },
  },
  col_all_slots: {
    id: 'col_all_slots',
    name: 'Dressed to the Elevens',
    desc: 'Have an item equipped in all eleven equipment slots at the same time.',
    category: 'collection',
    renown: 25,
    trigger: { kind: 'flag', flag: 'allEquipSlotsFilled' },
  },
  col_quartermaster_buyout: {
    id: 'col_quartermaster_buyout',
    name: 'Preferred Customer',
    desc: "Discover all ten pieces of the Heroic Quartermaster's stock.",
    category: 'collection',
    renown: 25,
    trigger: {
      kind: 'collectItems',
      itemIds: [
        'seal_of_the_nine_oaths',
        'nielas_coldlight_band',
        'sutils_gambit',
        'oath_of_the_round_table',
        'zyzzs_deathless_signet',
        'architects_cornerstone',
        'yumis_keepsake_locket',
        'zense_meridian',
        'swiftfang_talisman',
        'medallion_of_endless_profit',
      ],
    },
  },
  col_glimmerfin: {
    id: 'col_glimmerfin',
    name: 'Glimmer of Hope',
    desc: 'Catch a Glimmerfin Koi.',
    category: 'collection',
    renown: 0,
    trigger: { kind: 'collectItems', itemIds: ['glimmerfin_koi'] },
  },
  col_full_creel: {
    id: 'col_full_creel',
    name: 'Full Creel',
    desc: 'Discover all six common catches from the waters of the Vale, the Marsh, and the Heights.',
    category: 'collection',
    renown: 10,
    trigger: {
      kind: 'collectItems',
      itemIds: [
        'raw_mirror_trout',
        'raw_river_perch',
        'raw_marsh_pike',
        'raw_bog_eel',
        'raw_frostgill_trout',
        'raw_stonescale_carp',
      ],
    },
  },
  col_junk_drawer: {
    id: 'col_junk_drawer',
    name: 'The Junk Drawer',
    desc: 'Discover 10 different poor-quality items.',
    category: 'collection',
    renown: 5,
    trigger: { kind: 'meter', meter: 'poorItemsDiscoveredCount', amount: 10 },
  },

  pvp_arena_first_match: {
    id: 'pvp_arena_first_match',
    name: 'Sand in Your Boots',
    desc: 'Fight a ranked match in the Ashen Coliseum, in either bracket.',
    category: 'pvp',
    renown: 5,
    trigger: { kind: 'meter', meter: 'arenaRankedMatches', amount: 1 },
  },
  pvp_arena_first_win: {
    id: 'pvp_arena_first_win',
    name: 'The Crowd Roars',
    desc: 'Win a ranked arena match in either bracket.',
    category: 'pvp',
    renown: 10,
    trigger: { kind: 'meter', meter: 'arenaRankedWins', amount: 1 },
  },
  pvp_arena_1v1_1600: {
    id: 'pvp_arena_1v1_1600',
    name: 'Coliseum Contender',
    desc: 'Reach 1600 rating in the 1v1 arena bracket.',
    category: 'pvp',
    renown: 10,
    trigger: { kind: 'arenaRating', bracket: '1v1', rating: 1600 },
  },
  pvp_arena_1v1_1750: {
    id: 'pvp_arena_1v1_1750',
    name: 'Coliseum Rival',
    desc: 'Reach 1750 rating in the 1v1 arena bracket.',
    category: 'pvp',
    renown: 25,
    trigger: { kind: 'arenaRating', bracket: '1v1', rating: 1750 },
  },
  pvp_arena_1v1_1900: {
    id: 'pvp_arena_1v1_1900',
    name: 'Gladiator',
    desc: 'Reach 1900 rating in the 1v1 arena bracket.',
    category: 'pvp',
    renown: 50,
    trigger: { kind: 'arenaRating', bracket: '1v1', rating: 1900 },
    reward: { kind: 'title', text: 'Gladiator' },
  },
  pvp_arena_2v2_1600: {
    id: 'pvp_arena_2v2_1600',
    name: 'Two Strong',
    desc: 'Reach 1600 rating in the 2v2 arena bracket.',
    category: 'pvp',
    renown: 10,
    trigger: { kind: 'arenaRating', bracket: '2v2', rating: 1600 },
  },
  pvp_arena_2v2_1750: {
    id: 'pvp_arena_2v2_1750',
    name: 'Fearsome Twosome',
    desc: 'Reach 1750 rating in the 2v2 arena bracket.',
    category: 'pvp',
    renown: 25,
    trigger: { kind: 'arenaRating', bracket: '2v2', rating: 1750 },
  },
  pvp_arena_2v2_1900: {
    id: 'pvp_arena_2v2_1900',
    name: 'Perfect Partnership',
    desc: 'Reach 1900 rating in the 2v2 arena bracket.',
    category: 'pvp',
    renown: 50,
    trigger: { kind: 'arenaRating', bracket: '2v2', rating: 1900 },
  },
  pvp_duel_first_win: {
    id: 'pvp_duel_first_win',
    name: 'Settle It Outside',
    desc: 'Win a duel.',
    category: 'pvp',
    renown: 5,
    trigger: { kind: 'stat', stat: 'duelsWon', count: 1 },
  },
  pvp_duel_grace: {
    id: 'pvp_duel_grace',
    name: 'A Lesson in Humility',
    desc: 'Lose a duel with your dignity mostly intact.',
    category: 'pvp',
    renown: 5,
    trigger: { kind: 'stat', stat: 'duelsLost', count: 1 },
  },
  pvp_vcup_first_match: {
    id: 'pvp_vcup_first_match',
    name: 'Boots on the Pitch',
    desc: 'See out a full Vale Cup match at the Sowfield, win or lose.',
    category: 'pvp',
    renown: 5,
    trigger: { kind: 'manual' },
  },
  pvp_vcup_first_win: {
    id: 'pvp_vcup_first_win',
    name: 'First Silverware',
    desc: 'Win a rated Vale Cup match.',
    category: 'pvp',
    renown: 10,
    trigger: { kind: 'meter', meter: 'vcupWins', amount: 1 },
  },
  pvp_vcup_wins_10: {
    id: 'pvp_vcup_wins_10',
    name: 'Seasoned Boarballer',
    desc: 'Win 10 rated Vale Cup matches.',
    category: 'pvp',
    renown: 10,
    trigger: { kind: 'meter', meter: 'vcupWins', amount: 10 },
  },
  pvp_vcup_wins_25: {
    id: 'pvp_vcup_wins_25',
    name: 'Boarball Legend',
    desc: 'Win 25 rated Vale Cup matches.',
    category: 'pvp',
    renown: 25,
    trigger: { kind: 'meter', meter: 'vcupWins', amount: 25 },
    reward: { kind: 'title', text: 'Boarball Legend' },
  },
  pvp_vcup_first_goal: {
    id: 'pvp_vcup_first_goal',
    name: 'Off the Mark',
    desc: 'Score a goal in a rated Vale Cup match.',
    category: 'pvp',
    renown: 5,
    trigger: { kind: 'manual' },
  },
  pvp_vcup_hat_trick: {
    id: 'pvp_vcup_hat_trick',
    name: 'Hat Trick Hero',
    desc: 'Score three goals in a single rated Vale Cup match, in the 3v3 bracket or larger.',
    category: 'pvp',
    renown: 25,
    trigger: { kind: 'manual' },
  },
  pvp_vcup_golden_goal: {
    id: 'pvp_vcup_golden_goal',
    name: 'Golden Moment',
    desc: 'Score the golden goal that decides a rated Vale Cup match.',
    category: 'pvp',
    renown: 25,
    trigger: { kind: 'manual' },
  },
  pvp_vcup_first_save: {
    id: 'pvp_vcup_first_save',
    name: 'Safe Hands',
    desc: 'Make a save as keeper in a rated Vale Cup match.',
    category: 'pvp',
    renown: 5,
    trigger: { kind: 'manual' },
  },
  pvp_vcup_clean_sheet: {
    id: 'pvp_vcup_clean_sheet',
    name: 'Nothing Gets Past Me',
    desc: 'Win a rated Vale Cup match as keeper without conceding a goal.',
    category: 'pvp',
    renown: 25,
    trigger: { kind: 'manual' },
  },
  pvp_vcup_guild_win: {
    id: 'pvp_vcup_guild_win',
    name: 'For the Banner',
    desc: "Win a rated Vale Cup match entered under your guild's banner.",
    category: 'pvp',
    renown: 10,
    trigger: { kind: 'meter', meter: 'vcupGuildWins', amount: 1 },
  },
  pvp_fiesta_first_bout: {
    id: 'pvp_fiesta_first_bout',
    name: 'Party Crasher',
    desc: 'Fight a full 2v2 Fiesta bout, win or lose.',
    category: 'pvp',
    renown: 5,
    trigger: { kind: 'manual' },
  },
  pvp_fiesta_first_win: {
    id: 'pvp_fiesta_first_win',
    name: 'Life of the Fiesta',
    desc: 'Win a 2v2 Fiesta bout.',
    category: 'pvp',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  pvp_fiesta_double: {
    id: 'pvp_fiesta_double',
    name: 'Double Trouble',
    desc: 'Score two Fiesta takedowns within four seconds.',
    category: 'pvp',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  pvp_fiesta_shutdown: {
    id: 'pvp_fiesta_shutdown',
    name: 'Party Pooper',
    desc: 'Take down a Fiesta foe who is on a streak of three or more.',
    category: 'pvp',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  pvp_fiesta_full_build: {
    id: 'pvp_fiesta_full_build',
    name: 'Dressed for the Occasion',
    desc: 'Win a Fiesta bout with an augment locked in from all three waves.',
    category: 'pvp',
    renown: 10,
    trigger: { kind: 'manual' },
  },
  pvp_fiesta_powerups: {
    id: 'pvp_fiesta_powerups',
    name: 'One of Everything',
    desc: 'Grab each of the four ring power-ups at least once: Speed Demon, Colossus, Moon Boots, and Berserker.',
    category: 'pvp',
    renown: 10,
    trigger: {
      kind: 'visits',
      markIds: [
        'fiesta:pow_speed_demon',
        'fiesta:pow_colossus',
        'fiesta:pow_moon_boots',
        'fiesta:pow_berserker',
      ],
    },
  },
  pvp_fiesta_five_kills: {
    id: 'pvp_fiesta_five_kills',
    name: 'Carrying the Party',
    desc: 'Score five takedowns in a single Fiesta bout.',
    category: 'pvp',
    renown: 10,
    trigger: { kind: 'manual' },
  },

  soc_first_party: {
    id: 'soc_first_party',
    name: 'Better Together',
    desc: 'Join a party with another player.',
    category: 'social',
    renown: 5,
    trigger: { kind: 'stat', stat: 'partiesJoined', count: 1 },
  },
  soc_full_house: {
    id: 'soc_full_house',
    name: 'Full House',
    desc: 'Clear a dungeon with a full party of five.',
    category: 'social',
    renown: 10,
    trigger: { kind: 'stat', stat: 'fullPartyDungeonClears', count: 1 },
  },
  soc_guild_joined: {
    id: 'soc_guild_joined',
    name: 'Under One Banner',
    desc: 'Become a member of a guild.',
    category: 'social',
    renown: 5,
    trigger: { kind: 'flag', flag: 'guildMember' },
  },
  soc_guild_founded: {
    id: 'soc_guild_founded',
    name: "Founder's Quill",
    desc: 'Found a guild of your own.',
    category: 'social',
    renown: 10,
    trigger: { kind: 'stat', stat: 'guildsFounded', count: 1 },
  },
  soc_first_trade: {
    id: 'soc_first_trade',
    name: 'A Fair Exchange',
    desc: 'Complete a trade with another player.',
    category: 'social',
    renown: 5,
    trigger: { kind: 'stat', stat: 'tradesCompleted', count: 1 },
  },
  soc_first_sale: {
    id: 'soc_first_sale',
    name: 'Open for Business',
    desc: 'Collect the coin from your first World Market sale.',
    category: 'social',
    renown: 5,
    trigger: { kind: 'stat', stat: 'marketSaleCopper', count: 1 },
  },
  soc_steady_custom: {
    id: 'soc_steady_custom',
    name: 'Steady Custom',
    desc: 'Collect a lifetime total of 10 gold from your World Market sales.',
    category: 'social',
    renown: 10,
    trigger: { kind: 'stat', stat: 'marketSaleCopper', count: 100000 },
  },
  soc_market_magnate: {
    id: 'soc_market_magnate',
    name: 'Market Magnate',
    desc: 'Collect a lifetime total of 100 gold from your World Market sales.',
    category: 'social',
    renown: 25,
    trigger: { kind: 'stat', stat: 'marketSaleCopper', count: 1000000 },
    reward: { kind: 'title', text: 'Magnate' },
  },
  soc_by_ravens_wing: {
    id: 'soc_by_ravens_wing',
    name: "By Raven's Wing",
    desc: 'Send a Ravenpost letter carrying coin or a parcel.',
    category: 'social',
    renown: 5,
    trigger: { kind: 'stat', stat: 'mailAttachmentsSent', count: 1 },
  },
  soc_room_for_more: {
    id: 'soc_room_for_more',
    name: 'Room for More',
    desc: 'Buy your first bank expansion.',
    category: 'social',
    renown: 5,
    trigger: { kind: 'meter', meter: 'bankPurchasedSlots', amount: 6 },
  },
  soc_gilded_strongbox: {
    id: 'soc_gilded_strongbox',
    name: 'The Gilded Strongbox',
    desc: 'Purchase every bank expansion the bursars will sell you.',
    category: 'social',
    renown: 25,
    trigger: { kind: 'meter', meter: 'bankPurchasedSlots', amount: 72 },
  },
  soc_meet_bursar: {
    id: 'soc_meet_bursar',
    name: 'In Fernando We Trust',
    desc: 'Pay your respects to Bursar Fernando, keeper of the Gilded Strongbox in Eastbrook.',
    category: 'social',
    renown: 5,
    trigger: { kind: 'visit', markId: 'npc:bursar_fernando' },
  },
  soc_pocket_money: {
    id: 'soc_pocket_money',
    name: 'Pocket Money',
    desc: 'Loot a lifetime total of 1 gold in coin.',
    category: 'social',
    renown: 5,
    trigger: { kind: 'stat', stat: 'lootCopper', count: 10000 },
  },
  soc_heavy_purse: {
    id: 'soc_heavy_purse',
    name: 'Heavy Purse',
    desc: 'Loot a lifetime total of 10 gold in coin.',
    category: 'social',
    renown: 10,
    trigger: { kind: 'stat', stat: 'lootCopper', count: 100000 },
  },
  soc_wyrms_hoard: {
    id: 'soc_wyrms_hoard',
    name: "A Wyrm's Hoard",
    desc: 'Loot a lifetime total of 100 gold in coin.',
    category: 'social',
    renown: 25,
    trigger: { kind: 'stat', stat: 'lootCopper', count: 1000000 },
  },
  soc_civic_duty: {
    id: 'soc_civic_duty',
    name: 'Civic Duty',
    desc: 'Allocate your first town focus point.',
    category: 'social',
    renown: 5,
    trigger: { kind: 'meter', meter: 'townFocusPoints', amount: 1 },
  },
  exp_long_road_north: {
    id: 'exp_long_road_north',
    name: 'The Long Road North',
    desc: 'Visit all three hub settlements: Eastbrook, Fenbridge, and Highwatch.',
    category: 'exploration',
    renown: 5,
    trigger: {
      kind: 'visits',
      markIds: [
        'poi:eastbrook_vale:eastbrook',
        'poi:mirefen_marsh:fenbridge',
        'poi:thornpeak_heights:highwatch',
      ],
    },
  },
  exp_vale_wayfarer: {
    id: 'exp_vale_wayfarer',
    name: 'Wayfarer of the Vale',
    desc: 'Visit all eleven named places of Eastbrook Vale.',
    category: 'exploration',
    renown: 10,
    trigger: {
      kind: 'visits',
      markIds: [
        'poi:eastbrook_vale:eastbrook',
        'poi:eastbrook_vale:wolf_run',
        'poi:eastbrook_vale:boar_meadow',
        'poi:eastbrook_vale:mirror_lake',
        'poi:eastbrook_vale:sableweb',
        'poi:eastbrook_vale:copper_dig',
        'poi:eastbrook_vale:bandit_camp',
        'poi:eastbrook_vale:fallen_chapel',
        'poi:eastbrook_vale:reliquary_hill',
        'poi:eastbrook_vale:brightwood_glade',
        'poi:eastbrook_vale:the_sowfield',
      ],
    },
  },
  exp_marsh_wayfarer: {
    id: 'exp_marsh_wayfarer',
    name: 'Wayfarer of the Marsh',
    desc: 'Visit all eight named places of Mirefen Marsh.',
    category: 'exploration',
    renown: 10,
    trigger: {
      kind: 'visits',
      markIds: [
        'poi:mirefen_marsh:fenbridge',
        'poi:mirefen_marsh:prowler_reeds',
        'poi:mirefen_marsh:deepfen_shallows',
        'poi:mirefen_marsh:widow_thicket',
        'poi:mirefen_marsh:drowned_chapel',
        'poi:mirefen_marsh:troll_mounds',
        'poi:mirefen_marsh:gravecaller_encampment',
        'poi:mirefen_marsh:the_sunken_bastion',
      ],
    },
  },
  exp_peaks_wayfarer: {
    id: 'exp_peaks_wayfarer',
    name: 'Wayfarer of the Heights',
    desc: 'Visit all ten named places of Thornpeak Heights.',
    category: 'exploration',
    renown: 10,
    trigger: {
      kind: 'visits',
      markIds: [
        'poi:thornpeak_heights:highwatch',
        'poi:thornpeak_heights:stalker_ridge',
        'poi:thornpeak_heights:deeprock_burrows',
        'poi:thornpeak_heights:ogre_foothills',
        'poi:thornpeak_heights:drogmars_war_camp',
        'poi:thornpeak_heights:stormcrag',
        'poi:thornpeak_heights:the_glimmermere',
        'poi:thornpeak_heights:wyrmcult_tents',
        'poi:thornpeak_heights:revenant_fields',
        'poi:thornpeak_heights:gravewyrm_sanctum',
      ],
    },
  },
  exp_world_traveler: {
    id: 'exp_world_traveler',
    name: 'World Traveler',
    desc: 'Earn the wayfarer deed of all three zones.',
    category: 'exploration',
    renown: 25,
    trigger: {
      kind: 'meta',
      deedIds: ['exp_vale_wayfarer', 'exp_marsh_wayfarer', 'exp_peaks_wayfarer'],
    },
    reward: { kind: 'title', text: 'the Wayfarer' },
  },
  exp_something_shiny: {
    id: 'exp_something_shiny',
    name: 'Something Shiny',
    desc: 'Pick up a sparkling object from the ground.',
    category: 'exploration',
    renown: 5,
    trigger: { kind: 'stat', stat: 'groundObjectsLooted', count: 1 },
  },
  exp_first_ore: {
    id: 'exp_first_ore',
    name: 'Strike the Earth',
    desc: 'Harvest your first ore node.',
    category: 'exploration',
    renown: 5,
    trigger: { kind: 'gathering', professionId: 'mining', amount: 1 },
  },
  exp_first_timber: {
    id: 'exp_first_timber',
    name: 'Timber!',
    desc: 'Harvest your first wood node.',
    category: 'exploration',
    renown: 5,
    trigger: { kind: 'gathering', professionId: 'logging', amount: 1 },
  },
  exp_first_herb: {
    id: 'exp_first_herb',
    name: 'Green Thumb',
    desc: 'Harvest your first herb node.',
    category: 'exploration',
    renown: 5,
    trigger: { kind: 'gathering', professionId: 'herbalism', amount: 1 },
  },

  feat_era_cap: {
    id: 'feat_era_cap',
    name: 'Child of the First Era',
    desc: 'Reached level 20 while the First Era was current.',
    category: 'feat',
    renown: 0,
    trigger: { kind: 'flag', flag: 'firstEraCap' },
    feat: true,
  },
  feat_book_complete: {
    id: 'feat_book_complete',
    name: 'The Whole Book',
    desc: 'Earn every deed in the Book of Deeds.',
    category: 'feat',
    renown: 0,
    trigger: { kind: 'meta', deedIds: BOOK_COMPLETE_REQUIREMENTS },
    feat: true,
  },
  // Legacy feat of strength, the feat_era_cap class: both relics only ever
  // dropped from the retired Brightwood content (removed_zone1_content.ts
  // preserves held copies but no live source remains), so new copies cannot
  // be created. Holders earn it at login or receipt (the items are unbound,
  // so they still trade); a fresh realm can never mint a first earner. That
  // is the intended nature of this feat class, it stays visible as a history
  // marker, and feat deeds are excluded from BOOK_COMPLETE_REQUIREMENTS.
  feat_brightwood_relic: {
    id: 'feat_brightwood_relic',
    name: 'Brightwood Remembered',
    desc: "Keep a relic of the old Brightwood: the Bramblehide Jerkin or the Monarch's Crown.",
    category: 'feat',
    renown: 0,
    trigger: {
      kind: 'collectItems',
      itemIds: ['bramblehide_jerkin', 'monarch_crown_helm'],
      count: 1,
    },
    feat: true,
  },
  hid_saul_footnote: {
    id: 'hid_saul_footnote',
    name: 'A Footnote in History',
    desc: 'Pestered Saul the Chronicler nine times without pause.',
    category: 'hidden',
    renown: 5,
    trigger: { kind: 'manual' },
    reward: { kind: 'title', text: 'the Footnote' },
    hidden: true,
  },
  hid_gilded_tour: {
    id: 'hid_gilded_tour',
    name: 'The Gilded Tour',
    desc: 'Did business with all three branches of the Gilded Strongbox.',
    category: 'hidden',
    renown: 5,
    trigger: {
      kind: 'visits',
      markIds: ['npc:bursar_fernando', 'npc:bursar_petra_vell', 'npc:bursar_aldous_crane'],
    },
    hidden: true,
  },
  hid_fall_death: {
    id: 'hid_fall_death',
    name: 'Gravity Always Wins',
    desc: 'Died of a long conversation with the ground.',
    category: 'hidden',
    renown: 5,
    trigger: { kind: 'manual' },
    hidden: true,
  },
  hid_keepers_toll_twice: {
    id: 'hid_keepers_toll_twice',
    name: 'The Keeper Collects Twice',
    desc: "Died while The Keeper's Toll still weighed on you.",
    category: 'hidden',
    renown: 5,
    trigger: { kind: 'manual' },
    hidden: true,
  },
  hid_roll_hundred: {
    id: 'hid_roll_hundred',
    name: 'Natural Hundred',
    desc: 'Rolled a perfect 100 on a plain /roll.',
    category: 'hidden',
    renown: 0,
    trigger: { kind: 'manual' },
    hidden: true,
  },
  hid_yumi_cheer: {
    id: 'hid_yumi_cheer',
    name: "Yumi's Biggest Fan",
    desc: 'Cheered for Yumi where she could hear you, mid-bout.',
    category: 'hidden',
    renown: 5,
    trigger: { kind: 'manual' },
    hidden: true,
  },
  hid_bountiful_coffer: {
    id: 'hid_bountiful_coffer',
    name: 'The Purple Coffer',
    desc: 'Cracked a Bountiful Coffer before it could jam.',
    category: 'hidden',
    renown: 0,
    trigger: { kind: 'manual' },
    hidden: true,
  },
  hid_companion_save: {
    id: 'hid_companion_save',
    name: 'Not on Her Watch',
    desc: 'Your delve companion hauled a fallen partymate back to their feet.',
    category: 'hidden',
    renown: 5,
    trigger: { kind: 'manual' },
    hidden: true,
  },
  hid_codfather: {
    id: 'hid_codfather',
    name: 'Joined the Family',
    desc: 'Dragged The Codfather out of the Deepfen Shallows.',
    category: 'hidden',
    renown: 10,
    trigger: { kind: 'quest', questId: 'q_the_codfather' },
    hidden: true,
  },

  // Post-launch additions land at the table END regardless of category (the
  // append-only header contract: DEED_ORDER derives from table order), grouped
  // by category within this tail block only.
  prog_crown_below: {
    id: 'prog_crown_below',
    name: 'The Crown Below',
    desc: "Follow the crown from the restless bonefields to the tomb of King Nythraxis and see Scourge's End through.",
    category: 'progression',
    renown: 25,
    trigger: {
      kind: 'quests',
      questIds: [
        'q_nythraxis_restless_dead',
        'q_nythraxis_graves',
        'q_nythraxis_sealed_crypt',
        'q_nythraxis_bound_guardian',
        'q_nythraxis_scourges_end',
      ],
    },
  },
  prog_mere_at_rest: {
    id: 'prog_mere_at_rest',
    name: 'The Mere at Rest',
    desc: "See Tidewatcher Ondrel's watch through to the end: the choir silenced, the Palecoil slain, and the Drowned Moon put to rest.",
    category: 'progression',
    renown: 25,
    trigger: {
      kind: 'quests',
      questIds: ['q_drowned_choir', 'q_palecoil', 'q_silence_the_choir', 'q_drowned_moon'],
    },
  },
  prog_callused_hands: {
    id: 'prog_callused_hands',
    name: 'Callused Hands',
    desc: "Complete A Trade for Every Hand and earn your first callus in Eastbrook's trades.",
    category: 'progression',
    renown: 5,
    trigger: { kind: 'quest', questId: 'q_prof_intro' },
  },
  // Reagent sourcing: every hub recipe requires one of the six tier 4/5
  // reagents (thorium_ore, arcanite_bar, ashwood_log, elderwood_log,
  // goldleaf_herb, sunpetal_herb), sold by Quartermaster Bree at the
  // Highwatch hub (zone3.ts), so this deed (and feat_book_complete through
  // it) is completable in live play. The vendor-to-craft-to-grant chain is
  // pinned by tests/professions_crafting_hub.test.ts.
  prog_tools_of_the_trade: {
    id: 'prog_tools_of_the_trade',
    name: 'Tools of the Trade',
    desc: 'Complete a station-bound craft at the Highwatch crafting hub.',
    category: 'progression',
    renown: 10,
    trigger: { kind: 'stat', stat: 'hubCraftsPerformed', count: 1 },
  },
  dgn_nythraxis_crypt: {
    id: 'dgn_nythraxis_crypt',
    name: 'What the Crypt Kept',
    desc: 'Brave the Abandoned Crypt and recover both keystone halves and the ancient diary from its guardians.',
    category: 'dungeon',
    renown: 10,
    trigger: { kind: 'quest', questId: 'q_nythraxis_sealed_crypt' },
  },
  chr_marsh_first_cast: {
    id: 'chr_marsh_first_cast',
    name: 'Eels in the Reeds',
    desc: 'Catch a fish from the waters of Mirefen Marsh.',
    category: 'chronicle',
    renown: 5,
    trigger: { kind: 'visit', markId: 'fish:mirefen_marsh' },
  },
};

for (const def of Object.values(DEEDS)) {
  if (!def.feat && !def.hidden) BOOK_COMPLETE_REQUIREMENTS.push(def.id);
}

// Append-only (see the header contract); derived from the table so the two
// can never drift.
export const DEED_ORDER: string[] = Object.keys(DEEDS);
