import type { ItemDef, PlayerClass } from '../types';

// Archetype groups for class-locked rewards (REWARD_ARCHETYPE hands warrior
// rewards to paladins/shamans etc., so the lock must admit the whole group).
const WAR: PlayerClass[] = ['warrior', 'paladin', 'shaman'];
const MAG: PlayerClass[] = ['mage', 'priest', 'warlock', 'druid'];
const ROG: PlayerClass[] = ['rogue', 'hunter'];

// ---------------------------------------------------------------------------
// Items
// ---------------------------------------------------------------------------

export const BASE_ITEMS: Record<string, ItemDef> = {
  // --- starting gear ---
  worn_sword: {
    id: 'worn_sword',
    name: 'Pitted Shortsword',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 2, max: 5, speed: 2.0 },
    sellValue: 10,
  },
  gnarled_staff: {
    id: 'gnarled_staff',
    name: 'Bogoak Staff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 3, max: 6, speed: 2.9 },
    stats: { int: 1 },
    sellValue: 12,
  },
  rusty_dagger: {
    id: 'rusty_dagger',
    name: 'Rusty Dagger',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 2, max: 4, speed: 1.8, dagger: true },
    sellValue: 10,
  },
  training_mace: {
    id: 'training_mace',
    name: 'Training Mace',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 2, max: 5, speed: 2.6 },
    sellValue: 10,
  },
  rusty_hatchet: {
    id: 'rusty_hatchet',
    name: 'Rusty Hatchet',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 2, max: 5, speed: 2.2 },
    sellValue: 10,
  },
  recruit_tunic: {
    id: 'recruit_tunic',
    name: "Levyman's Tunic",
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 20 },
    sellValue: 5,
  },
  apprentice_robe: {
    id: 'apprentice_robe',
    name: 'Threadbare Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 8 },
    sellValue: 5,
  },
  footpad_jerkin: {
    id: 'footpad_jerkin',
    name: 'Cutpurse Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 14 },
    sellValue: 5,
  },
  // --- quest reward gear ---
  redbrook_blade: {
    id: 'redbrook_blade',
    name: 'Redbrook Militia Blade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 6, max: 11, speed: 2.2 },
    stats: { str: 2 },
    sellValue: 120,
    requiredClass: WAR,
  },
  apprentice_staff: {
    id: 'apprentice_staff',
    name: 'Vale Apprentice Staff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 7, max: 12, speed: 3.0 },
    stats: { int: 3, sta: 1 },
    sellValue: 120,
    requiredClass: MAG,
  },
  keen_dirk: {
    id: 'keen_dirk',
    name: 'Keen Dirk',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 4, max: 8, speed: 1.7, dagger: true },
    stats: { agi: 2 },
    sellValue: 120,
    requiredClass: ROG,
  },
  militia_vest: {
    id: 'militia_vest',
    name: 'Militia Chainvest',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 90, sta: 2 },
    sellValue: 150,
    requiredClass: WAR,
  },
  woven_robe: {
    id: 'woven_robe',
    set: 'vale_arcanist',
    name: 'Valewoven Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 30, int: 3, spi: 2 },
    sellValue: 150,
    requiredClass: MAG,
  },
  shadow_jerkin: {
    id: 'shadow_jerkin',
    set: 'greyjaw_stalker',
    name: 'Shadowstitch Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 55, agi: 3 },
    sellValue: 150,
    requiredClass: ROG,
  },
  oiled_boots: {
    id: 'oiled_boots',
    name: 'Oiled Leather Boots',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 25, agi: 1 },
    sellValue: 80,
  },
  quilted_trousers: {
    id: 'quilted_trousers',
    name: 'Quilted Trousers',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 30, sta: 2 },
    sellValue: 90,
  },
  greyjaw_pelt_cloak: {
    id: 'greyjaw_pelt_cloak',
    name: "Greyjaw's Pelt Leggings",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 35, sta: 1, agi: 1 },
    sellValue: 110,
  },
  greyjaw_hide_boots: {
    id: 'greyjaw_hide_boots',
    set: 'greyjaw_stalker',
    name: 'Greyjaw Hide Boots',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 28, agi: 1, sta: 1 },
    sellValue: 130,
  },
  bristleback_maul: {
    id: 'bristleback_maul',
    name: 'Gallowglass Hammer',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 7, max: 12, speed: 2.8 },
    stats: { str: 2, sta: 1 },
    sellValue: 160,
    requiredClass: WAR,
  },
  sableweb_slippers: {
    id: 'sableweb_slippers',
    name: 'Sableweb Slippers',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 18, int: 2, spi: 1 },
    sellValue: 150,
    requiredClass: MAG,
  },
  gorraks_cruel_chopper: {
    id: 'gorraks_cruel_chopper',
    name: "Gorrak's Cruel Chopper",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 8, max: 13, speed: 2.4 },
    stats: { str: 2, sta: 1 },
    sellValue: 180,
    requiredClass: WAR,
  },
  tunnelkings_spade: {
    id: 'tunnelkings_spade',
    name: "Tunnelking's Spade",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 9, max: 15, speed: 2.7 },
    stats: { str: 3, sta: 2 },
    sellValue: 190,
    requiredClass: WAR,
  },
  moggers_stomper_boots: {
    id: 'moggers_stomper_boots',
    name: "Mogger's Stomper Boots",
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 32, agi: 2, sta: 1 },
    sellValue: 180,
    requiredClass: ROG,
  },
  moggers_copper_cudgel: {
    id: 'moggers_copper_cudgel',
    name: "Mogger's Copper Cudgel",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 9, max: 15, speed: 2.6 },
    stats: { str: 3, sta: 2 },
    sellValue: 850,
    requiredClass: WAR,
  },
  moggers_shiv: {
    id: 'moggers_shiv',
    name: "Mogger's Shiv",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 6, max: 11, speed: 1.7, dagger: true },
    stats: { agi: 4, sta: 2 },
    sellValue: 850,
    requiredClass: ROG,
  },
  valeborn_spellblade: {
    id: 'valeborn_spellblade',
    name: 'Valeborn Spellblade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 8, max: 14, speed: 2.2 },
    stats: { int: 4, spi: 2 },
    sellValue: 850,
    requiredClass: MAG,
  },
  cryptbone_greaves: {
    id: 'cryptbone_greaves',
    name: 'Cryptbone Greaves',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 48, sta: 2 },
    sellValue: 180,
  },
  // --- Inventory 2.0: helmet/shoulder/waist/gloves. ---
  // No documented armor/stat budget exists, so these are balanced to the
  // *empirical* convention of the existing class-neutral mid-tier pieces:
  // armor is slot-weighted off the legs/chest baseline (head≈1.0, shoulder≈0.75,
  // gloves≈0.65, waist≈0.55) and stat points track peers (uncommon ~L10-13 ≈ 2-4
  // pts; class-neutral rare ~L20 ≈ 5-7 pts, cf. cryptbone_greaves / trollhide_leggings
  // / korgaths_chainwraps / stormshard_leggings). Class-neutral on purpose.
  cryptbone_helm: {
    id: 'cryptbone_helm',
    name: 'Cryptbone Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'uncommon',
    stats: { armor: 48, sta: 3 },
    sellValue: 185,
  },
  cryptbone_pauldrons: {
    id: 'cryptbone_pauldrons',
    name: 'Cryptbone Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'uncommon',
    stats: { armor: 36, sta: 2 },
    sellValue: 140,
  },
  mistveil_cord: {
    id: 'mistveil_cord',
    name: 'Mistveil Cord',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'waist',
    quality: 'uncommon',
    stats: { armor: 30, sta: 2, agi: 1 },
    sellValue: 150,
  },
  mistveil_grips: {
    id: 'mistveil_grips',
    name: 'Mistveil Grips',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'uncommon',
    stats: { armor: 36, agi: 2, sta: 1 },
    sellValue: 165,
  },
  boundstone_helm: {
    id: 'boundstone_helm',
    set: 'boundstone_vanguard',
    name: 'Boundstone Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'rare',
    stats: { armor: 105, sta: 6, str: 5 },
    sellValue: 460,
  },
  boundstone_girdle: {
    id: 'boundstone_girdle',
    set: 'boundstone_vanguard',
    name: 'Boundstone Girdle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'rare',
    stats: { armor: 60, sta: 6, str: 3 },
    sellValue: 340,
  },
  gravewyrm_mantle: {
    id: 'gravewyrm_mantle',
    name: 'Gravewyrm Mantle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'rare',
    stats: { armor: 82, agi: 7, sta: 3 },
    sellValue: 410,
  },
  gravewyrm_gauntlets: {
    id: 'gravewyrm_gauntlets',
    set: 'boundstone_vanguard',
    name: 'Gravewyrm Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'rare',
    stats: { armor: 72, str: 5, sta: 4 },
    sellValue: 390,
  },
  // --- bags (kind:'bag', equip into one of the 4 bag sockets for +bagSlots
  // pooled inventory capacity; the 16-slot backpack is implicit). Tiered by
  // quality: common bags are vendor goods, uncommon drops from beasts, rare
  // and epic from dungeon bosses. See src/sim/bags.ts for the capacity rules. ---
  linen_pouch: {
    id: 'linen_pouch',
    name: 'Linen Pouch',
    kind: 'bag',
    quality: 'common',
    bagSlots: 6,
    sellValue: 60,
    buyValue: 250,
  },
  travelers_knapsack: {
    id: 'travelers_knapsack',
    name: "Traveler's Knapsack",
    kind: 'bag',
    quality: 'common',
    bagSlots: 8,
    sellValue: 500,
    buyValue: 2000,
  },
  wolfhide_satchel: {
    id: 'wolfhide_satchel',
    name: 'Wolfhide Satchel',
    kind: 'bag',
    quality: 'uncommon',
    bagSlots: 10,
    sellValue: 1200,
  },
  gravewoven_bag: {
    id: 'gravewoven_bag',
    name: 'Gravewoven Bag',
    kind: 'bag',
    quality: 'rare',
    bagSlots: 12,
    sellValue: 3500,
  },
  mistcallers_duffel: {
    id: 'mistcallers_duffel',
    name: "Fogbinder's Duffel",
    kind: 'bag',
    quality: 'epic',
    bagSlots: 14,
    sellValue: 9000,
  },
  // --- food & drink (vendor) ---
  baked_bread: {
    id: 'baked_bread',
    name: 'Cottage Loaf',
    kind: 'food',
    quality: 'common',
    foodHp: 61,
    sellValue: 6,
    buyValue: 25,
  },
  spring_water: {
    id: 'spring_water',
    name: 'Cold Well Water',
    kind: 'drink',
    quality: 'common',
    drinkMana: 76,
    sellValue: 6,
    buyValue: 25,
  },
  simple_fishing_pole: {
    id: 'simple_fishing_pole',
    name: 'Simple Fishing Pole',
    kind: 'tool',
    quality: 'common',
    use: { type: 'fishing' },
    sellValue: 4,
    buyValue: 20,
  },
  // Base gathering tools (#1123). Each is infinite-durability (this repo has
  // no durability field on ItemDef) and tiered: `use.tier` gates which
  // node/material tiers it can gather (see src/sim/professions/tools.ts).
  copper_mining_pick: {
    id: 'copper_mining_pick',
    name: 'Copper Mining Pick',
    kind: 'tool',
    quality: 'common',
    use: { type: 'gatherTool', professionId: 'mining', tier: 1 },
    sellValue: 4,
    buyValue: 20,
  },
  iron_mining_pick: {
    id: 'iron_mining_pick',
    name: 'Iron Mining Pick',
    kind: 'tool',
    quality: 'common',
    use: { type: 'gatherTool', professionId: 'mining', tier: 2 },
    sellValue: 10,
    buyValue: 60,
  },
  mithril_mining_pick: {
    id: 'mithril_mining_pick',
    name: 'Mithril Mining Pick',
    kind: 'tool',
    quality: 'uncommon',
    use: { type: 'gatherTool', professionId: 'mining', tier: 3 },
    sellValue: 25,
    buyValue: 150,
  },
  handaxe: {
    id: 'handaxe',
    name: 'Handaxe',
    kind: 'tool',
    quality: 'common',
    use: { type: 'gatherTool', professionId: 'logging', tier: 1 },
    sellValue: 4,
    buyValue: 20,
  },
  felling_axe: {
    id: 'felling_axe',
    name: 'Felling Axe',
    kind: 'tool',
    quality: 'common',
    use: { type: 'gatherTool', professionId: 'logging', tier: 2 },
    sellValue: 10,
    buyValue: 60,
  },
  ironbark_axe: {
    id: 'ironbark_axe',
    name: 'Ironbark Axe',
    kind: 'tool',
    quality: 'uncommon',
    use: { type: 'gatherTool', professionId: 'logging', tier: 3 },
    sellValue: 25,
    buyValue: 150,
  },
  gathering_sickle: {
    id: 'gathering_sickle',
    name: 'Gathering Sickle',
    kind: 'tool',
    quality: 'common',
    use: { type: 'gatherTool', professionId: 'herbalism', tier: 1 },
    sellValue: 4,
    buyValue: 20,
  },
  bronze_sickle: {
    id: 'bronze_sickle',
    name: 'Bronze Sickle',
    kind: 'tool',
    quality: 'common',
    use: { type: 'gatherTool', professionId: 'herbalism', tier: 2 },
    sellValue: 10,
    buyValue: 60,
  },
  silverleaf_sickle: {
    id: 'silverleaf_sickle',
    name: 'Silverleaf Sickle',
    kind: 'tool',
    quality: 'uncommon',
    use: { type: 'gatherTool', professionId: 'herbalism', tier: 3 },
    sellValue: 25,
    buyValue: 150,
  },
  // Crafted base tools, tier 4 and 5 (#1135). Same shape and gating as the
  // vendor tools above (infinite-durability, `use.tier` gates node AND
  // monster-material tier access via src/sim/professions/tools.ts), but these
  // are produced by a profession (see COMMON_RECIPES in content/recipes.ts),
  // never sold by any vendor: no `buyValue` and deliberately absent from
  // every NPC `vendorItems` list. `quality` (rarity) is independent of
  // `use.tier` and never affects gating: only the tool's `use.tier` value is
  // read by the gate.
  // are produced by a profession, never sold by any vendor: no `buyValue` and
  // deliberately absent from every NPC `vendorItems` list. `quality` (rarity)
  // is independent of `use.tier` and never affects gating: only the tool's
  // `use.tier` value is read by the gate.
  thorium_mining_pick: {
    id: 'thorium_mining_pick',
    name: 'Thorium Mining Pick',
    kind: 'tool',
    quality: 'rare',
    use: { type: 'gatherTool', professionId: 'mining', tier: 4 },
    sellValue: 60,
  },
  arcanite_mining_pick: {
    id: 'arcanite_mining_pick',
    name: 'Arcanite Mining Pick',
    kind: 'tool',
    quality: 'epic',
    use: { type: 'gatherTool', professionId: 'mining', tier: 5 },
    sellValue: 150,
  },
  ashwood_axe: {
    id: 'ashwood_axe',
    name: 'Ashwood Axe',
    kind: 'tool',
    quality: 'rare',
    use: { type: 'gatherTool', professionId: 'logging', tier: 4 },
    sellValue: 60,
  },
  elderwood_axe: {
    id: 'elderwood_axe',
    name: 'Elderwood Axe',
    kind: 'tool',
    quality: 'epic',
    use: { type: 'gatherTool', professionId: 'logging', tier: 5 },
    sellValue: 150,
  },
  goldleaf_sickle: {
    id: 'goldleaf_sickle',
    name: 'Goldleaf Sickle',
    kind: 'tool',
    quality: 'rare',
    use: { type: 'gatherTool', professionId: 'herbalism', tier: 4 },
    sellValue: 60,
  },
  sunpetal_sickle: {
    id: 'sunpetal_sickle',
    name: 'Sunpetal Sickle',
    kind: 'tool',
    quality: 'epic',
    use: { type: 'gatherTool', professionId: 'herbalism', tier: 5 },
    sellValue: 150,
  },
  // Tier 4/5 crafting reagents for the tools directly above (#1135's
  // `TOOL_RECIPE_STUBS`, de-stubbed into src/sim/content/recipes.ts once
  // #1127's crafting action existed to consume them). `kind: 'junk'`, same
  // generic-material shape as bone_fragments/linen_scrap/spider_leg below:
  // not gathered from a dedicated node yet (see gathering.ts NODE_HARVEST_TABLE).
  // Sold by Quartermaster Bree at the Highwatch hub (zone3.ts) so every hub
  // recipe has a live reagent source; buyValue is the trade-goods staple
  // markup already used in this file (4x sellValue, travelers_knapsack's
  // exact ratio, with linen_pouch and spring_water close by at 4.17x), not
  // a new balance number.
  thorium_ore: {
    id: 'thorium_ore',
    name: 'Thorium Ore',
    kind: 'junk',
    quality: 'rare',
    sellValue: 15,
    buyValue: 60,
  },
  arcanite_bar: {
    id: 'arcanite_bar',
    name: 'Arcanite Bar',
    kind: 'junk',
    quality: 'epic',
    sellValue: 40,
    buyValue: 160,
  },
  ashwood_log: {
    id: 'ashwood_log',
    name: 'Ashwood Log',
    kind: 'junk',
    quality: 'rare',
    sellValue: 15,
    buyValue: 60,
  },
  elderwood_log: {
    id: 'elderwood_log',
    name: 'Elderwood Log',
    kind: 'junk',
    quality: 'epic',
    sellValue: 40,
    buyValue: 160,
  },
  goldleaf_herb: {
    id: 'goldleaf_herb',
    name: 'Goldleaf Herb',
    kind: 'junk',
    quality: 'rare',
    sellValue: 15,
    buyValue: 60,
  },
  sunpetal_herb: {
    id: 'sunpetal_herb',
    name: 'Sunpetal Herb',
    kind: 'junk',
    quality: 'epic',
    sellValue: 40,
    buyValue: 160,
  },
  // Cosmetic event reward: using it rolls a rarity rank (server-side) and opens
  // the skin-select overlay. See src/sim/content/skins.ts. Dev-grant for now.
  event_skin_token: {
    id: 'event_skin_token',
    name: 'Mysterious Cosmetic Cache',
    kind: 'tool',
    quality: 'epic',
    use: { type: 'skinSelect', catalog: 'class' },
    sellValue: 0,
  },
  // Heroic-dungeon participation token: the final boss of a heroic instance
  // drops one personal mark per eligible participant (awardHeroicMarks in
  // src/sim/instances/dungeons.ts). Not vendorable; a spend sink ships later.
  heroic_mark: {
    id: 'heroic_mark',
    name: 'Heroic Mark',
    kind: 'tool',
    quality: 'rare',
    // Currency-like: marks stack so saving toward a 12-16 mark vendor price
    // (content/heroic_vendor.ts) does not eat a bag slot per mark.
    stackSize: 20,
    sellValue: 0,
    // Bound to the earner: marks can only be spent at the Heroic Quartermaster,
    // never traded, mailed, listed, or destroyed. See the soulbound flag in types.ts.
    soulbound: true,
  },
  raw_mirror_trout: {
    id: 'raw_mirror_trout',
    name: 'Raw Mirror Trout',
    kind: 'food',
    quality: 'common',
    foodHp: 61,
    sellValue: 3,
  },
  tangled_weed: {
    id: 'tangled_weed',
    name: 'Tangled Weed',
    kind: 'junk',
    quality: 'poor',
    sellValue: 1,
  },
  // --- fishing catches (see FISHING_TABLES below). Food heals scale with the
  // depth/level of the zone you fish in; junk just vendors for coppers. ---
  raw_river_perch: {
    id: 'raw_river_perch',
    name: 'Raw River Perch',
    kind: 'food',
    quality: 'common',
    foodHp: 45,
    sellValue: 2,
  },
  raw_marsh_pike: {
    id: 'raw_marsh_pike',
    name: 'Raw Marsh Pike',
    kind: 'food',
    quality: 'common',
    foodHp: 90,
    sellValue: 6,
  },
  raw_bog_eel: {
    id: 'raw_bog_eel',
    name: 'Raw Bog Eel',
    kind: 'food',
    quality: 'common',
    foodHp: 90,
    sellValue: 6,
  },
  raw_frostgill_trout: {
    id: 'raw_frostgill_trout',
    name: 'Raw Frostgill Trout',
    kind: 'food',
    quality: 'common',
    foodHp: 117,
    sellValue: 10,
  },
  raw_stonescale_carp: {
    id: 'raw_stonescale_carp',
    name: 'Raw Slatefin Carp',
    kind: 'food',
    quality: 'common',
    foodHp: 117,
    sellValue: 10,
  },
  soggy_boot: {
    id: 'soggy_boot',
    name: 'Soggy Boot',
    kind: 'junk',
    quality: 'poor',
    sellValue: 1,
  },
  // The prized rare catch, reelable from any water — a lucky hook.
  glimmerfin_koi: {
    id: 'glimmerfin_koi',
    name: 'Glimmerfin Koi',
    kind: 'food',
    quality: 'uncommon',
    foodHp: 117,
    sellValue: 75,
  },
  roasted_boar: {
    id: 'roasted_boar',
    name: 'Spitted Boar Haunch',
    kind: 'food',
    quality: 'common',
    foodHp: 117,
    sellValue: 12,
    buyValue: 100,
  },
  // --- combat potions (vendor): instant, usable in combat, 2-minute shared cooldown.
  // Restore less than sitting to eat/drink, the price you pay for not sitting (#103).
  minor_healing_potion: {
    id: 'minor_healing_potion',
    name: 'Minor Healing Potion',
    kind: 'potion',
    quality: 'common',
    potionHp: 90,
    sellValue: 8,
    buyValue: 40,
  },
  minor_mana_potion: {
    id: 'minor_mana_potion',
    name: 'Minor Mana Potion',
    kind: 'potion',
    quality: 'common',
    potionMana: 120,
    sellValue: 8,
    buyValue: 40,
  },
  // --- battle elixir: a temporary stat buff on use (classic flask/elixir staple).
  // Drops from the Mirefen brutes; +Stamina helps anyone push deeper into the marsh.
  elixir_of_the_bear: {
    id: 'elixir_of_the_bear',
    name: 'Elixir of the Bear',
    kind: 'elixir',
    quality: 'uncommon',
    elixir: { aura: 'Might of the Bear', kind: 'buff_sta', value: 12, duration: 900 },
    sellValue: 20,
    buyValue: 100,
  },
  // Higher tiers of the combat-potion ladder, keeping pace with the zone-2/3
  // level bands (classic Minor -> Lesser -> standard progression). Same instant,
  // in-combat, 2-minute-shared-cooldown rules as the Minor tier above.
  lesser_healing_potion: {
    id: 'lesser_healing_potion',
    name: 'Lesser Healing Potion',
    kind: 'potion',
    quality: 'common',
    potionHp: 150,
    sellValue: 16,
    buyValue: 85,
  },
  lesser_mana_potion: {
    id: 'lesser_mana_potion',
    name: 'Lesser Mana Potion',
    kind: 'potion',
    quality: 'common',
    potionMana: 200,
    sellValue: 16,
    buyValue: 85,
  },
  healing_potion: {
    id: 'healing_potion',
    name: 'Healing Potion',
    kind: 'potion',
    quality: 'common',
    potionHp: 280,
    sellValue: 32,
    buyValue: 170,
  },
  mana_potion: {
    id: 'mana_potion',
    name: 'Mana Potion',
    kind: 'potion',
    quality: 'common',
    potionMana: 360,
    sellValue: 32,
    buyValue: 170,
  },
  conjured_water: {
    id: 'conjured_water',
    name: 'Conjured Rainwater',
    kind: 'drink',
    quality: 'common',
    drinkMana: 76,
    sellValue: 0,
  },
  conjured_water2: {
    id: 'conjured_water2',
    name: 'Conjured Wellwater',
    kind: 'drink',
    quality: 'common',
    drinkMana: 288,
    sellValue: 0,
  },
  conjured_water3: {
    id: 'conjured_water3',
    name: 'Conjured Clearwater',
    kind: 'drink',
    quality: 'common',
    drinkMana: 672,
    sellValue: 0,
  },
  // --- conjured food (mage Conjure Food ranks; foodHp tiers pair with the
  // conjured-water mana tiers above) ---
  conjured_bread: {
    id: 'conjured_bread',
    name: 'Conjured Oatcake',
    kind: 'food',
    quality: 'common',
    foodHp: 61,
    sellValue: 0,
  },
  conjured_bread2: {
    id: 'conjured_bread2',
    name: 'Conjured Black Loaf',
    kind: 'food',
    quality: 'common',
    foodHp: 243,
    sellValue: 0,
  },
  conjured_bread3: {
    id: 'conjured_bread3',
    name: 'Conjured Honeycake',
    kind: 'food',
    quality: 'common',
    foodHp: 552,
    sellValue: 0,
  },
  // --- Smith Haldren's stock (common/white, levels 3-7) ---
  eastbrook_arming_sword: {
    id: 'eastbrook_arming_sword',
    name: 'Eastbrook Arming Sword',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 5, max: 9, speed: 2.2 },
    sellValue: 140,
    buyValue: 1400,
  },
  bronzework_mace: {
    id: 'bronzework_mace',
    name: 'Bronzework Mace',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 6, max: 10, speed: 2.6 },
    sellValue: 140,
    buyValue: 1400,
  },
  vale_carving_knife: {
    id: 'vale_carving_knife',
    name: 'Vale Carving Knife',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 4, max: 7, speed: 1.8, dagger: true },
    sellValue: 120,
    buyValue: 1200,
  },
  hickory_shortstaff: {
    id: 'hickory_shortstaff',
    name: 'Hickory Shortstaff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 6, max: 11, speed: 3.0 },
    stats: { int: 1 },
    sellValue: 150,
    buyValue: 1500,
  },
  eastbrook_chain_vest: {
    id: 'eastbrook_chain_vest',
    name: 'Eastbrook Chainmail Vest',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 60 },
    sellValue: 180,
    buyValue: 1800,
  },
  valespun_robe: {
    id: 'valespun_robe',
    name: 'Valespun Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 22 },
    sellValue: 140,
    buyValue: 1400,
  },
  tanned_leather_jerkin: {
    id: 'tanned_leather_jerkin',
    name: 'Tanned Leather Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 40 },
    sellValue: 160,
    buyValue: 1600,
  },
  hobnail_boots: {
    id: 'hobnail_boots',
    name: 'Hobnailed Boots',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'common',
    stats: { armor: 18 },
    sellValue: 90,
    buyValue: 900,
  },
  eastbrook_wool_trousers: {
    id: 'eastbrook_wool_trousers',
    name: 'Eastbrook Wool Trousers',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'common',
    stats: { armor: 24 },
    sellValue: 110,
    buyValue: 1100,
  },
  // --- Hollow Crypt rewards (rare/blue) ---
  // Item-level showcase: these rares are NORMALIZED to the stat budget their item
  // level earns (see src/sim/item_level.ts). The three weapons are the q_hollow
  // reward for felling Morthen (level 10), so item level 13 (rare +3) -> a 7-point
  // primary-stat budget; each keeps its own stat identity (str/sta, agi/sta,
  // int/spi) at the same total. The three archetype chests drop from the level-7
  // chapel elites, so item level 10 -> a 6-point budget. tests/item_level.test.ts
  // pins data == formula. (hollowbone_hauberk and cryptstalker_jerkin already sat
  // at 6, so only the off-budget pieces below moved.)
  gravecaller_blade: {
    id: 'gravecaller_blade',
    name: "Gravecaller's Broadblade",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 9, max: 16, speed: 2.4 },
    stats: { str: 4, sta: 3 },
    sellValue: 800,
  },
  widowfang_dirk: {
    id: 'widowfang_dirk',
    name: 'Widowfang Dirk',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 6, max: 10, speed: 1.7, dagger: true },
    stats: { agi: 4, sta: 3 },
    sellValue: 800,
  },
  gravecaller_staff: {
    id: 'gravecaller_staff',
    name: 'Staff of the Hollow',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 10, max: 17, speed: 3.0 },
    stats: { int: 5, spi: 2 },
    sellValue: 800,
  },
  marrowtread_boots: {
    id: 'marrowtread_boots',
    name: 'Marrowtread Boots',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'rare',
    stats: { armor: 45, sta: 2, str: 1 },
    sellValue: 500,
    requiredClass: WAR,
  },
  sextons_slippers: {
    id: 'sextons_slippers',
    name: "Sexton's Slippers",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'rare',
    stats: { armor: 20, int: 2, spi: 2 },
    sellValue: 500,
    requiredClass: MAG,
  },
  gravewalker_softboots: {
    id: 'gravewalker_softboots',
    name: 'Gravewalker Softboots',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'rare',
    stats: { armor: 32, agi: 3 },
    sellValue: 500,
    requiredClass: ROG,
  },
  hollowbone_hauberk: {
    id: 'hollowbone_hauberk',
    name: 'Hollowbone Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'rare',
    stats: { armor: 105, str: 3, sta: 3 },
    sellValue: 700,
    requiredClass: WAR,
  },
  gravewoven_raiment: {
    id: 'gravewoven_raiment',
    name: 'Gravewoven Raiment',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'rare',
    stats: { armor: 38, int: 3, spi: 3 },
    sellValue: 700,
    requiredClass: MAG,
  },
  cryptstalker_jerkin: {
    id: 'cryptstalker_jerkin',
    name: 'Gravestalker Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'rare',
    stats: { armor: 65, agi: 4, sta: 2 },
    sellValue: 700,
    requiredClass: ROG,
  },
  hollowbound_legguards: {
    id: 'hollowbound_legguards',
    name: 'Hollowbound Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'rare',
    stats: { armor: 62, sta: 3 },
    sellValue: 600,
  },
  gravepath_treads: {
    id: 'gravepath_treads',
    name: 'Gravepath Treads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'rare',
    stats: { armor: 42, sta: 2 },
    sellValue: 600,
  },
  // --- Captain Verlan (ruins rare) drops ---
  // A shared uncommon trophy (any class) plus a mutually-exclusive rare chase
  // group, one item per archetype, mirroring the other zone-1 rare elites.
  oathbound_greaves: {
    id: 'oathbound_greaves',
    name: 'Oathbound Greaves',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 52, sta: 2, str: 1 },
    sellValue: 200,
  },
  verlans_oathblade: {
    id: 'verlans_oathblade',
    name: "Verlan's Oathblade",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 10, max: 16, speed: 2.5 },
    stats: { str: 4, sta: 2 },
    sellValue: 880,
    requiredClass: WAR,
  },
  hollow_vigil_staff: {
    id: 'hollow_vigil_staff',
    name: 'Staff of the Hollow Vigil',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 11, max: 18, speed: 3.0 },
    stats: { int: 5, spi: 2 },
    sellValue: 880,
    requiredClass: MAG,
  },
  gravewardens_shiv: {
    id: 'gravewardens_shiv',
    name: "Gravewarden's Shiv",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 7, max: 11, speed: 1.7, dagger: true },
    stats: { agi: 4, sta: 2 },
    sellValue: 880,
    requiredClass: ROG,
  },
  maldrecs_soulbinder: {
    id: 'maldrecs_soulbinder',
    name: "Maldrec's Soulbinder",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 11, max: 18, speed: 3.0 },
    stats: { int: 4, spi: 3 },
    sellValue: 850,
  },
  // --- quest items ---
  boar_hide: {
    id: 'boar_hide',
    name: 'Bristly Boar Hide',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_boars',
  },
  gravecaller_sigil: {
    id: 'gravecaller_sigil',
    name: "Gravecaller's Sigil",
    kind: 'quest',
    sellValue: 0,
    questId: 'q_whispers',
  },
  blessed_wax: {
    id: 'blessed_wax',
    name: 'Blessed Tallow',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_rite',
  },
  ghostly_essence: {
    id: 'ghostly_essence',
    name: 'Ghostly Essence',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_rite',
  },
  webwood_silk: {
    id: 'webwood_silk',
    name: 'Sableweb Silk Gland',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_spiders',
  },
  supply_crate: {
    id: 'supply_crate',
    name: 'Stolen Supply Crate',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_supplies',
  },
  greyjaw_fang: {
    id: 'greyjaw_fang',
    name: "Old Greyjaw's Fang",
    kind: 'quest',
    sellValue: 0,
    questId: 'q_greyjaw',
  },
  chunk_of_ore: {
    id: 'chunk_of_ore',
    name: 'Chunk of Ore',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_prof_intro',
  },
  weathered_ledger_page: {
    id: 'weathered_ledger_page',
    name: 'Weathered Ledger Page',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_names_of_the_dead',
  },
  morthen_grimoire: {
    id: 'morthen_grimoire',
    name: "Morthen's Grimoire",
    kind: 'quest',
    sellValue: 0,
    questId: 'q_gravecallers_trail',
  },
  // --- Brightwood Glade wildlife pack ---
  soft_down: {
    id: 'soft_down',
    name: 'Soft Down Tuft',
    kind: 'junk',
    quality: 'poor',
    sellValue: 4,
  },
  amber_hide: { id: 'amber_hide', name: 'Amber Hide', kind: 'junk', quality: 'poor', sellValue: 9 },
  stag_antler: {
    id: 'stag_antler',
    name: 'Branching Antler',
    kind: 'junk',
    quality: 'poor',
    sellValue: 8,
  },
  brightwood_venison: {
    id: 'brightwood_venison',
    name: 'Brightwood Venison',
    kind: 'food',
    quality: 'common',
    foodHp: 92,
    sellValue: 4,
    buyValue: 35,
  },
  bramblehide_jerkin: {
    id: 'bramblehide_jerkin',
    name: 'Bramblehide Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 40, sta: 2, agi: 1 },
    sellValue: 120,
  },
  monarch_crown_helm: {
    id: 'monarch_crown_helm',
    name: "Monarch's Crown",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'rare',
    stats: { armor: 46, sta: 3, agi: 2, str: 1 },
    sellValue: 320,
  },
  // --- junk (gray) ---
  wolf_fang: {
    id: 'wolf_fang',
    name: 'Cracked Wolf Fang',
    kind: 'junk',
    quality: 'poor',
    sellValue: 4,
  },
  bandit_bandana: {
    id: 'bandit_bandana',
    name: 'Red Bandana',
    kind: 'junk',
    quality: 'poor',
    sellValue: 6,
  },
  tough_jerky: {
    id: 'tough_jerky',
    name: 'Salted Jerky',
    kind: 'food',
    quality: 'common',
    foodHp: 61,
    sellValue: 2,
    buyValue: 25,
  },
  mudfin_scale: {
    id: 'mudfin_scale',
    name: 'Slimy Mudfin Scale',
    kind: 'junk',
    quality: 'poor',
    sellValue: 5,
  },
  tallow_candle: {
    id: 'tallow_candle',
    name: 'Greasy Tallow Lump',
    kind: 'junk',
    quality: 'poor',
    sellValue: 5,
  },
  spider_leg: {
    id: 'spider_leg',
    name: 'Twitching Spider Leg',
    kind: 'junk',
    quality: 'poor',
    sellValue: 4,
  },
  bone_fragments: {
    id: 'bone_fragments',
    name: 'Bone Fragments',
    kind: 'junk',
    quality: 'poor',
    sellValue: 7,
  },
  linen_scrap: {
    id: 'linen_scrap',
    name: 'Linen Scrap',
    kind: 'junk',
    quality: 'poor',
    sellValue: 3,
  },

  // --- Enchanting materials ------------------------------------------------
  // Disenchant yield (src/sim/professions/enchanting.ts), tiered by the
  // disenchanted item's rarity: common/uncommon -> dust, rare -> essence,
  // epic/legendary -> shard. Consumed as reagents by the ENCHANTS table
  // (content/enchants.ts). Reuses the 'junk' kind, same as bone_fragments/
  // linen_scrap/spider_leg above (this repo has no dedicated material kind).
  arcane_dust: {
    id: 'arcane_dust',
    name: 'Arcane Dust',
    kind: 'junk',
    quality: 'common',
    sellValue: 6,
  },
  arcane_essence: {
    id: 'arcane_essence',
    name: 'Arcane Essence',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 18,
  },
  arcane_shard: {
    id: 'arcane_shard',
    name: 'Arcane Shard',
    kind: 'junk',
    quality: 'rare',
    sellValue: 55,
  },

  // --- Quartermaster's Consignment ---------------------------------------
  // A standing line of practical adventuring gear. The Merchant keeps eight
  // pieces stocked on the World Market (see seedHouseListings); four more are
  // looted from threats around the Vale. All uncommon, Eastbrook-tier (~L5-9),
  // filling the helmet/shoulder/waist/gloves slots the early game leaves thin.
  roadwardens_helm: {
    id: 'roadwardens_helm',
    name: "Roadwarden's Helm",
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'uncommon',
    stats: { armor: 45, sta: 2 },
    sellValue: 130,
    requiredClass: WAR,
  },
  wayfarers_hood: {
    id: 'wayfarers_hood',
    name: "Wayfarer's Hood",
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'uncommon',
    stats: { armor: 30, agi: 2 },
    sellValue: 120,
    requiredClass: ROG,
  },
  acolytes_circlet: {
    id: 'acolytes_circlet',
    set: 'vale_arcanist',
    name: "Acolyte's Circlet",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'uncommon',
    stats: { armor: 16, int: 2, spi: 1 },
    sellValue: 120,
    requiredClass: MAG,
  },
  reinforced_pauldrons: {
    id: 'reinforced_pauldrons',
    name: 'Reinforced Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'uncommon',
    stats: { armor: 50, str: 1, sta: 1 },
    sellValue: 140,
    requiredClass: WAR,
  },
  embroidered_mantle: {
    id: 'embroidered_mantle',
    name: 'Embroidered Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'uncommon',
    stats: { armor: 14, int: 2 },
    sellValue: 110,
    requiredClass: MAG,
  },
  sturdy_belt: {
    id: 'sturdy_belt',
    name: "Sturdy Traveler's Belt",
    kind: 'armor',
    armorType: 'leather',
    slot: 'waist',
    quality: 'uncommon',
    stats: { armor: 35, sta: 2 },
    sellValue: 100,
  },
  silk_sash: {
    id: 'silk_sash',
    set: 'vale_arcanist',
    name: 'Woven Silk Sash',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'waist',
    quality: 'uncommon',
    stats: { armor: 10, int: 2, spi: 1 },
    sellValue: 100,
    requiredClass: MAG,
  },
  roughspun_gloves: {
    id: 'roughspun_gloves',
    name: 'Roughspun Gloves',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'uncommon',
    stats: { armor: 28, agi: 1, sta: 1 },
    sellValue: 95,
  },
  // looted pieces
  bristlehide_spaulders: {
    id: 'bristlehide_spaulders',
    name: 'Bristlehide Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'uncommon',
    stats: { armor: 40, agi: 1, sta: 2 },
    sellValue: 150,
    requiredClass: ROG,
  },
  sableweb_cord: {
    id: 'sableweb_cord',
    name: 'Sableweb Cord',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'waist',
    quality: 'uncommon',
    stats: { armor: 11, agi: 1, int: 2 },
    sellValue: 150,
  },
  gorraks_cleaver: {
    id: 'gorraks_cleaver',
    name: "Gorrak's Cleaver",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 8, max: 14, speed: 2.5 },
    stats: { str: 3 },
    sellValue: 180,
    requiredClass: WAR,
  },
  mossy_handwraps: {
    id: 'mossy_handwraps',
    name: 'Mossgrown Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'uncommon',
    stats: { armor: 12, int: 1, spi: 2 },
    sellValue: 140,
    requiredClass: MAG,
  },
  // --- Crossroads Outfitters ----------------------------------------------
  // A travelling caravan quartermaster's standing stock, filling the slots the
  // Quartermaster's Consignment left thin: mainhand weapons plus chest, legs and
  // feet. All uncommon, Eastbrook-tier (~L8-12); most are unrestricted so any
  // melee adventurer can outfit a full set. The Merchant keeps eight on the
  // World Market (see seedHouseListings); four more drop around the Vale.
  crossroads_saber: {
    id: 'crossroads_saber',
    name: 'Crossroads Saber',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 8, max: 14, speed: 2.5 },
    stats: { str: 2 },
    sellValue: 170,
  },
  tradesman_hatchet: {
    id: 'tradesman_hatchet',
    name: "Tradesman's Hatchet",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 7, max: 13, speed: 2.3 },
    stats: { str: 1, sta: 1 },
    sellValue: 160,
  },
  drovers_staff: {
    id: 'drovers_staff',
    name: "Drover's Staff",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 9, max: 15, speed: 3.0 },
    stats: { int: 3, spi: 2 },
    sellValue: 175,
    requiredClass: MAG,
  },
  caravan_warden_dirk: {
    id: 'caravan_warden_dirk',
    name: 'Caravan Warden Dirk',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 5, max: 9, speed: 1.7, dagger: true },
    stats: { agi: 3 },
    sellValue: 170,
    requiredClass: ROG,
  },
  outrider_brigandine: {
    id: 'outrider_brigandine',
    name: 'Outrider Brigandine',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 95, str: 1, sta: 2 },
    sellValue: 165,
  },
  caravan_quilted_vest: {
    id: 'caravan_quilted_vest',
    name: 'Caravan Quilted Vest',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 40, sta: 2 },
    sellValue: 130,
  },
  wanderers_chestguard: {
    id: 'wanderers_chestguard',
    name: "Wanderer's Chestguard",
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 60, agi: 2, sta: 1 },
    sellValue: 150,
  },
  outrider_legguards: {
    id: 'outrider_legguards',
    name: 'Outrider Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 70, sta: 2 },
    sellValue: 150,
  },
  trail_leggings: {
    id: 'trail_leggings',
    set: 'greyjaw_stalker',
    name: 'Trailworn Leggings',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 45, agi: 2 },
    sellValue: 120,
  },
  pilgrims_leggings: {
    id: 'pilgrims_leggings',
    name: "Pilgrim's Leggings",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 24, int: 2, spi: 1 },
    sellValue: 120,
  },
  outrider_sabatons: {
    id: 'outrider_sabatons',
    name: 'Outrider Sabatons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 55, sta: 2 },
    sellValue: 130,
  },
  milepost_boots: {
    id: 'milepost_boots',
    name: 'Milepost Boots',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 30, agi: 1, sta: 1 },
    sellValue: 110,
  },
};

// --- Zone-aware fishing loot ----------------------------------------------
// A cast resolves to one weighted draw from the table for the zone the angler
// is standing in. `itemId: null` means "no fish are biting" (an empty hook).
// The engine (Sim.completeFishing) rolls a single this.rng draw against the
// running weight total, so catches stay replay-deterministic.
export interface FishingEntry {
  itemId: string | null;
  weight: number;
}

export const FISHING_TABLES: Record<string, FishingEntry[]> = {
  eastbrook_vale: [
    { itemId: 'raw_mirror_trout', weight: 45 },
    { itemId: 'raw_river_perch', weight: 30 },
    { itemId: 'tangled_weed', weight: 12 },
    { itemId: 'glimmerfin_koi', weight: 3 },
    { itemId: null, weight: 10 },
  ],
  mirefen_marsh: [
    { itemId: 'raw_marsh_pike', weight: 40 },
    { itemId: 'raw_bog_eel', weight: 30 },
    { itemId: 'soggy_boot', weight: 8 },
    { itemId: 'tangled_weed', weight: 9 },
    { itemId: 'glimmerfin_koi', weight: 3 },
    { itemId: null, weight: 10 },
  ],
  thornpeak_heights: [
    { itemId: 'raw_frostgill_trout', weight: 40 },
    { itemId: 'raw_stonescale_carp', weight: 30 },
    { itemId: 'tangled_weed', weight: 14 },
    { itemId: 'glimmerfin_koi', weight: 4 },
    { itemId: null, weight: 12 },
  ],
};

// The rare catch worth a celebratory shout in the combat log.
export const FISHING_RARE_ID = 'glimmerfin_koi';
