// ---------------------------------------------------------------------------
// Classic-inspired talent content for the eight non-warrior classes. The tree
// scale matches the level-20 micro-MMO cap: a shared class tree plus one compact
// spec tree per class specialization, using the same passive/active/choice node
// language as the warrior vertical slice.
// ---------------------------------------------------------------------------

import type { PlayerClass } from '../types';
import type {
  ClassTalents,
  Role,
  SpecDef,
  TalentChoiceOption,
  TalentEffect,
  TalentNode,
  TalentTree,
} from './talents';

type Gate = Pick<TalentNode, 'requires' | 'pointsGate'>;

function passive(
  id: string,
  tree: TalentTree,
  specId: string | undefined,
  maxRank: number,
  effect: TalentEffect,
  icon: string,
  name: string,
  description: string,
  row: number,
  col: number,
  gate: Gate = {},
): TalentNode {
  return {
    id,
    tree,
    ...(specId ? { specId } : {}),
    kind: 'passive',
    maxRank,
    effect,
    icon,
    name,
    description,
    row,
    col,
    ...gate,
  };
}

function active(
  id: string,
  tree: TalentTree,
  specId: string | undefined,
  effect: TalentEffect,
  icon: string,
  name: string,
  description: string,
  row: number,
  col: number,
  gate: Gate = {},
): TalentNode {
  return {
    id,
    tree,
    ...(specId ? { specId } : {}),
    kind: 'active',
    maxRank: 1,
    effect,
    icon,
    name,
    description,
    row,
    col,
    ...gate,
  };
}

function choice(
  id: string,
  tree: TalentTree,
  specId: string | undefined,
  icon: string,
  name: string,
  description: string,
  row: number,
  col: number,
  choices: TalentChoiceOption[],
  gate: Gate = {},
): TalentNode {
  return {
    id,
    tree,
    ...(specId ? { specId } : {}),
    kind: 'choice',
    maxRank: 1,
    icon,
    name,
    description,
    row,
    col,
    choices,
    ...gate,
  };
}

function spec(
  id: string,
  cls: PlayerClass,
  name: string,
  role: Role,
  icon: string,
  description: string,
  signature: string,
  masteryName: string,
  masteryDescription: string,
  effect: TalentEffect,
): SpecDef {
  return {
    id,
    class: cls,
    name,
    role,
    icon,
    description,
    signature,
    mastery: { name: masteryName, description: masteryDescription, effect },
  };
}

const PALADIN_CLASS: TalentNode[] = [
  passive(
    'pal_divine_strength',
    'class',
    undefined,
    3,
    { stats: { str: 2 } },
    '+',
    'Sworn Strength',
    'Increases your Strength by 2 per rank.',
    0,
    0,
  ),
  passive(
    'pal_spiritual_focus',
    'class',
    undefined,
    3,
    { stats: { spi: 2 }, global: { healPct: 0.02 } },
    '*',
    'Quiet Fervor',
    'Increases Spirit by 2 and healing done by 2% per rank.',
    0,
    2,
  ),
  passive(
    'pal_imp_devotion_aura',
    'class',
    undefined,
    2,
    { ability: [{ ability: 'devotion_aura', buffPct: 0.2 }], stats: { armorPct: 0.03 } },
    '#',
    'Improved Steadfast Aura',
    'Increases your armor by 3% per rank. Increases Steadfast Aura by 20% per rank.',
    1,
    0,
    { requires: ['pal_divine_strength'] },
  ),
  passive(
    'pal_benediction',
    'class',
    undefined,
    2,
    {
      ability: [
        { ability: 'seal_of_righteousness', costPct: -0.08 },
        { ability: 'judgement', costPct: -0.08 },
      ],
    },
    'v',
    'Fervent Oath',
    'Reduces the mana cost of Oathbrand and Verdict by 8% per rank.',
    1,
    1,
    { pointsGate: 2 },
  ),
  passive(
    'pal_precision',
    'class',
    undefined,
    3,
    { stats: { crit: 0.01 } },
    'x',
    'Grim Certainty',
    'Increases your critical strike chance by 1% per rank.',
    1,
    2,
    { requires: ['pal_spiritual_focus'] },
  ),
  choice(
    'pal_holy_calling',
    'class',
    undefined,
    '@',
    'Votive Calling',
    'Choose one paladin emphasis.',
    2,
    1,
    [
      {
        id: 'pal_calling_light',
        name: "Mender's Vow",
        icon: '+',
        description: 'Increases healing done by 6%.',
        effect: { global: { healPct: 0.06 } },
      },
      {
        id: 'pal_calling_guardian',
        name: "Warder's Vow",
        icon: '#',
        description: 'Increases armor by 8% and dodge by 2%.',
        effect: { stats: { armorPct: 0.08, dodge: 0.02 } },
      },
      {
        id: 'pal_calling_crusader',
        name: "Reaper's Vow",
        icon: 'x',
        description: 'Increases melee ability damage by 6%.',
        effect: { global: { meleeDmgPct: 0.06 } },
      },
    ],
    { pointsGate: 5 },
  ),
  active(
    'pal_divine_favor',
    'class',
    undefined,
    { grant: { ability: 'divine_protection' } },
    'O',
    "Martyr's Boon",
    'Grants early access to Ward of Faith.',
    3,
    0,
    { pointsGate: 8, requires: ['pal_imp_devotion_aura'] },
  ),
  passive(
    'pal_sanctified_light',
    'class',
    undefined,
    2,
    { stats: { int: 3, maxHpPct: 0.04 } },
    '*',
    'Hallowlight',
    'Increases Intellect by 3 and maximum health by 4% per rank.',
    3,
    2,
    { pointsGate: 8, requires: ['pal_holy_calling'] },
  ),
];

const PALADIN_SPECS: SpecDef[] = [
  spec(
    'holy',
    'paladin',
    'Sacrament',
    'healer',
    '+',
    'A devoted healer who turns the Light into steady single-target recovery.',
    'flash_of_light',
    'Kindled Faith',
    'Increases all healing done by 12%.',
    { global: { healPct: 0.12 } },
  ),
  spec(
    'protection',
    'paladin',
    'Vigil',
    'tank',
    '#',
    'A shield-bearing defender who converts Holy power into threat and mitigation.',
    'righteous_fury',
    'Oathward',
    'Increases threat by 25% and armor by 10%.',
    { global: { threatPct: 0.25 }, stats: { armorPct: 0.1 } },
  ),
  spec(
    'retribution',
    'paladin',
    'Requital',
    'dps',
    'x',
    'A holy warrior who judges enemies with weapon strikes and radiant burst.',
    'judgement',
    'Blood Debt',
    'Increases melee and spell ability damage by 6%.',
    { global: { meleeDmgPct: 0.06, spellDmgPct: 0.06 } },
  ),
];

const PALADIN_SPEC_NODES: TalentNode[] = [
  passive(
    'holy_imp_holy_light',
    'spec',
    'holy',
    3,
    { ability: [{ ability: 'holy_light', dmgPct: 0.08 }] },
    '+',
    'Improved Mending Light',
    'Increases Mending Light healing by 8% per rank.',
    0,
    0,
  ),
  passive(
    'holy_divine_intellect',
    'spec',
    'holy',
    3,
    { stats: { int: 3 } },
    '*',
    'Lettered Faith',
    'Increases Intellect by 3 per rank.',
    0,
    2,
  ),
  passive(
    'holy_flash_focus',
    'spec',
    'holy',
    2,
    { ability: [{ ability: 'flash_of_light', castPct: -0.1, costPct: -0.08 }] },
    '>',
    'Lightmend Focus',
    'Makes Lightmend faster and cheaper by 10%/8% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['holy_imp_holy_light'] },
  ),
  passive(
    'holy_lay_blessing',
    'spec',
    'holy',
    2,
    { ability: [{ ability: 'lay_on_hands', cooldownPct: -0.2 }] },
    'O',
    'Improved Last Rite',
    'Reduces Last Rite cooldown by 20% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'holy_choice',
    'spec',
    'holy',
    '@',
    'Lodestar',
    'Choose one Sacrament refinement.',
    2,
    1,
    [
      {
        id: 'holy_choice_grace',
        name: 'Unearned Mercy',
        icon: '+',
        description: 'Increases healing by 8%.',
        effect: { global: { healPct: 0.08 } },
      },
      {
        id: 'holy_choice_judgement',
        name: 'Verdict of Light',
        icon: 'x',
        description: 'Verdict deals 20% more damage.',
        effect: { ability: [{ ability: 'judgement', dmgPct: 0.2 }] },
      },
      {
        id: 'holy_choice_devotion',
        name: 'Steadfast Soul',
        icon: '#',
        description: 'Increases stamina by 8%.',
        effect: { stats: { staPct: 0.08 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'holy_light_mastery',
    'spec',
    'holy',
    2,
    { global: { healPct: 0.06 }, stats: { crit: 0.01 } },
    '*',
    'Lightwright',
    'Increases healing by 6% and critical strike by 1% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['holy_choice'] },
  ),

  passive(
    'prot_redoubt',
    'spec',
    'protection',
    3,
    { stats: { armorPct: 0.05 } },
    '#',
    'Palisade',
    'Increases armor by 5% per rank.',
    0,
    0,
  ),
  passive(
    'prot_anticipation',
    'spec',
    'protection',
    3,
    { stats: { dodge: 0.01 } },
    'o',
    'Forewarning',
    'Increases dodge chance by 1% per rank.',
    0,
    2,
  ),
  passive(
    'prot_imp_righteous_fury',
    'spec',
    'protection',
    2,
    { global: { threatPct: 0.1 }, ability: [{ ability: 'righteous_fury', costPct: -0.25 }] },
    '!',
    'Improved Burning Oath',
    'Increases threat by 10% and reduces Burning Oath cost by 25% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['prot_redoubt'] },
  ),
  passive(
    'prot_guardians_favor',
    'spec',
    'protection',
    2,
    {
      ability: [
        { ability: 'divine_protection', cooldownPct: -0.15 },
        { ability: 'hammer_of_justice', cooldownPct: -0.1 },
      ],
    },
    'O',
    "Warder's Vow",
    'Reduces Ward of Faith cooldown by 15% per rank. Reduces Sundering Gavel cooldown by 10% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'prot_choice',
    'spec',
    'protection',
    '@',
    'Refuge',
    'Choose one Vigil refinement.',
    2,
    1,
    [
      {
        id: 'prot_choice_sanctuary',
        name: 'Oath of Refuge',
        icon: '#',
        description: 'Increases armor by 12%.',
        effect: { stats: { armorPct: 0.12 } },
      },
      {
        id: 'prot_choice_reckoning',
        name: 'Grave Mistake',
        icon: 'x',
        description: 'Increases melee damage by 8%.',
        effect: { global: { meleeDmgPct: 0.08 } },
      },
      {
        id: 'prot_choice_ardent',
        name: 'Deathless Ardor',
        icon: '+',
        description: 'Increases maximum health by 12%.',
        effect: { stats: { maxHpPct: 0.12 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'prot_holy_shield',
    'spec',
    'protection',
    2,
    { ability: [{ ability: 'consecration', dmgPct: 0.12 }], global: { threatPct: 0.08 } },
    '#',
    'Hallowed Wall',
    'Increases Holy Ground damage by 12% and threat by 8% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['prot_choice'] },
  ),

  passive(
    'ret_benediction',
    'spec',
    'retribution',
    3,
    {
      ability: [
        { ability: 'seal_of_righteousness', costPct: -0.08 },
        { ability: 'judgement', costPct: -0.08 },
      ],
    },
    'v',
    'Fervent Oath',
    'Reduces core offensive costs by 8% per rank.',
    0,
    0,
  ),
  passive(
    'ret_conviction',
    'spec',
    'retribution',
    3,
    { stats: { crit: 0.01 } },
    'x',
    'Grim Certainty',
    'Increases critical strike chance by 1% per rank.',
    0,
    2,
  ),
  passive(
    'ret_imp_judgement',
    'spec',
    'retribution',
    2,
    { ability: [{ ability: 'judgement', cooldownPct: -0.15, dmgPct: 0.1 }] },
    '!',
    'Improved Verdict',
    'Reduces Verdict cooldown by 15% and increases damage by 10% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['ret_benediction'] },
  ),
  passive(
    'ret_seal_command',
    'spec',
    'retribution',
    2,
    { ability: [{ ability: 'seal_of_righteousness', dmgPct: 0.2 }] },
    'x',
    'Oathbrand Command',
    'Increases Oathbrand damage by 20% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'ret_choice',
    'spec',
    'retribution',
    '@',
    'Warpath',
    'Choose one Requital refinement.',
    2,
    1,
    [
      {
        id: 'ret_choice_sanctity',
        name: 'Fervid Aura',
        icon: '*',
        description: 'Increases spell damage by 8%.',
        effect: { global: { spellDmgPct: 0.08 } },
      },
      {
        id: 'ret_choice_pursuit',
        name: 'Swift Verdict',
        icon: '>',
        description: 'Increases dodge by 3% and attack power by 10%.',
        effect: { stats: { dodge: 0.03, apPct: 0.1 } },
      },
      {
        id: 'ret_choice_vengeance',
        name: 'Blood Debt',
        icon: 'x',
        description: 'Increases critical strike chance by 4%.',
        effect: { stats: { crit: 0.04 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'ret_crusader_strikes',
    'spec',
    'retribution',
    2,
    {
      global: { meleeDmgPct: 0.06, spellDmgPct: 0.04 },
      ability: [{ ability: 'exorcism', cooldownPct: -0.1 }],
    },
    'x',
    'Punishing Blows',
    'Increases melee ability damage by 6% per rank. Increases spell damage by 4% per rank. Reduces Rite of Expulsion cooldown by 10% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['ret_choice'] },
  ),
];

const HUNTER_CLASS: TalentNode[] = [
  passive(
    'hun_endurance_training',
    'class',
    undefined,
    3,
    { stats: { sta: 2 } },
    '+',
    'Ironsinew',
    'Increases Stamina by 2 per rank.',
    0,
    0,
  ),
  passive(
    'hun_lethal_shots',
    'class',
    undefined,
    3,
    { stats: { crit: 0.01 } },
    'x',
    "Butcher's Aim",
    'Increases critical strike chance by 1% per rank.',
    0,
    2,
  ),
  passive(
    'hun_imp_hawk',
    'class',
    undefined,
    2,
    { ability: [{ ability: 'aspect_of_the_hawk', buffPct: 0.2 }], stats: { ap: 8 } },
    '^',
    "Improved Harrier's Guise",
    "Increases attack power by 8 per rank. Increases Harrier's Guise by 20% per rank.",
    1,
    0,
    { requires: ['hun_endurance_training'] },
  ),
  passive(
    'hun_efficiency',
    'class',
    undefined,
    2,
    {
      ability: [
        { ability: 'arcane_shot', costPct: -0.08 },
        { ability: 'serpent_sting', costPct: -0.08 },
      ],
    },
    'v',
    'Lean Quiver',
    'Reduces shot and sting costs by 8% per rank.',
    1,
    1,
    { pointsGate: 2 },
  ),
  passive(
    'hun_deflection',
    'class',
    undefined,
    3,
    { stats: { dodge: 0.01 } },
    'o',
    'Turnaside',
    'Increases dodge chance by 1% per rank.',
    1,
    2,
    { requires: ['hun_lethal_shots'] },
  ),
  choice(
    'hun_pathfinder',
    'class',
    undefined,
    '@',
    'Waywise',
    'Choose one hunter emphasis.',
    2,
    1,
    [
      {
        id: 'hun_path_beast',
        name: 'First Fang',
        icon: '+',
        description: 'Increases maximum health by 8%.',
        effect: { stats: { maxHpPct: 0.08 } },
      },
      {
        id: 'hun_path_marksman',
        name: 'Carrion Eye',
        icon: 'x',
        description: 'Increases ranged attack power by 12%.',
        effect: { stats: { apPct: 0.12 } },
      },
      {
        id: 'hun_path_survivor',
        name: 'Brackenstride',
        icon: 'o',
        description: 'Increases dodge by 5%.',
        effect: { stats: { dodge: 0.05 } },
      },
    ],
    { pointsGate: 5 },
  ),
  active(
    'hun_rapid_instincts',
    'class',
    undefined,
    { grant: { ability: 'rapid_fire' } },
    '>',
    'Fevered Instinct',
    'Grants early access to Fevered Draw.',
    3,
    0,
    { pointsGate: 8, requires: ['hun_imp_hawk'] },
  ),
  passive(
    'hun_survivalist',
    'class',
    undefined,
    2,
    { stats: { agi: 3, sta: 3 } },
    '+',
    'Old Scars',
    'Increases Agility and Stamina by 3 per rank.',
    3,
    2,
    { pointsGate: 8, requires: ['hun_pathfinder'] },
  ),
];

const HUNTER_SPECS: SpecDef[] = [
  spec(
    'beast_mastery',
    'hunter',
    'Packlord',
    'dps',
    '+',
    'A wild commander who fights beside a durable companion.',
    'tame_beast',
    'Packbond',
    'Increases maximum health and attack power by 8%.',
    { stats: { maxHpPct: 0.08, apPct: 0.08 } },
  ),
  spec(
    'marksmanship',
    'hunter',
    'Coldsight',
    'dps',
    'x',
    'A precise archer built around ranged burst and efficient shots.',
    'aimed_shot',
    'Iron Aim',
    'Increases attack power by 12% and critical strike by 2%.',
    { stats: { apPct: 0.12, crit: 0.02 } },
  ),
  spec(
    'survival',
    'hunter',
    'Fieldcraft',
    'dps',
    'o',
    'A skirmisher who controls distance and survives close pressure.',
    'wing_clip',
    'Quickblood',
    'Increases Agility by 10% and dodge by 2%.',
    { stats: { agiPct: 0.1, dodge: 0.02 } },
  ),
];

const HUNTER_SPEC_NODES: TalentNode[] = [
  passive(
    'bm_thick_hide',
    'spec',
    'beast_mastery',
    3,
    { stats: { armorPct: 0.04, sta: 1 } },
    '#',
    'Calloused Hide',
    'Increases armor by 4% and Stamina by 1 per rank.',
    0,
    0,
  ),
  passive(
    'bm_unleashed_fury',
    'spec',
    'beast_mastery',
    3,
    { stats: { ap: 8 } },
    'x',
    'Slipped Leash',
    'Increases attack power by 8 per rank.',
    0,
    2,
  ),
  passive(
    'bm_imp_mend',
    'spec',
    'beast_mastery',
    2,
    {
      ability: [
        { ability: 'tame_beast', castPct: -0.15 },
        { ability: 'dismiss_pet', cooldownPct: -0.2 },
      ],
    },
    '+',
    'Beast Tending',
    'Reduces Wildbond cast time by 15% per rank. Reduces Release Companion cooldown by 20% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['bm_thick_hide'] },
  ),
  passive(
    'bm_ferocity',
    'spec',
    'beast_mastery',
    2,
    { stats: { crit: 0.015 } },
    'x',
    'Redmaw',
    'Increases critical strike chance by 1.5% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'bm_choice',
    'spec',
    'beast_mastery',
    '@',
    'Beastpact',
    'Choose one Packlord refinement.',
    2,
    1,
    [
      {
        id: 'bm_choice_wrath',
        name: 'Howling Rage',
        icon: 'x',
        description: 'Increases melee and ranged damage by 8%.',
        effect: { global: { meleeDmgPct: 0.08 } },
      },
      {
        id: 'bm_choice_intimidation',
        name: 'Cowing Roar',
        icon: '!',
        description: 'Rattling Shot cooldown is reduced by 25%.',
        effect: { ability: [{ ability: 'concussive_shot', cooldownPct: -0.25 }] },
      },
      {
        id: 'bm_choice_frenzy',
        name: 'Bloodlather',
        icon: '>',
        description: 'Increases attack power by 14%.',
        effect: { stats: { apPct: 0.14 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'bm_focused_fire',
    'spec',
    'beast_mastery',
    2,
    { ability: [{ ability: 'rapid_fire', cooldownPct: -0.15 }], stats: { crit: 0.01 } },
    '>',
    'Shared Quarry',
    'Increases critical strike chance by 1% per rank. Reduces Fevered Draw cooldown by 15% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['bm_choice'] },
  ),

  passive(
    'mm_imp_arcane_shot',
    'spec',
    'marksmanship',
    3,
    { ability: [{ ability: 'arcane_shot', dmgPct: 0.08 }] },
    '*',
    'Improved Fell Shot',
    'Increases Fell Shot damage by 8% per rank.',
    0,
    0,
  ),
  passive(
    'mm_lethal_shots',
    'spec',
    'marksmanship',
    3,
    { stats: { crit: 0.01 } },
    'x',
    "Butcher's Aim",
    'Increases critical strike chance by 1% per rank.',
    0,
    2,
  ),
  passive(
    'mm_aimed_focus',
    'spec',
    'marksmanship',
    2,
    { ability: [{ ability: 'aimed_shot', castPct: -0.1, dmgPct: 0.08 }] },
    '>',
    'Steady Draw',
    'Increases Long Draw damage by 8% per rank. Reduces Long Draw cast time by 10% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['mm_imp_arcane_shot'] },
  ),
  passive(
    'mm_barrage',
    'spec',
    'marksmanship',
    2,
    {
      ability: [
        { ability: 'arcane_shot', cooldownPct: -0.1 },
        { ability: 'concussive_shot', cooldownPct: -0.1 },
      ],
    },
    '*',
    'Arrow Squall',
    'Reduces Fell Shot cooldown by 10% per rank. Reduces Rattling Shot cooldown by 10% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'mm_choice',
    'spec',
    'marksmanship',
    '@',
    'Sureflight',
    'Choose one Coldsight refinement.',
    2,
    1,
    [
      {
        id: 'mm_choice_aura',
        name: 'Sureflight Aura',
        icon: '^',
        description: 'Increases attack power by 16%.',
        effect: { stats: { apPct: 0.16 } },
      },
      {
        id: 'mm_choice_mortal',
        name: 'Cruel Wounds',
        icon: 'x',
        description: 'Increases critical strike by 4%.',
        effect: { stats: { crit: 0.04 } },
      },
      {
        id: 'mm_choice_hawk',
        name: 'Carrion Eye',
        icon: '>',
        description: 'Long Draw costs 20% less mana.',
        effect: { ability: [{ ability: 'aimed_shot', costPct: -0.2 }] },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'mm_marksman_mastery',
    'spec',
    'marksmanship',
    2,
    { ability: [{ ability: 'aimed_shot', cooldownPct: -0.12, dmgPct: 0.1 }] },
    'x',
    'Coldsight Mastery',
    'Increases Long Draw damage by 10% per rank. Reduces Long Draw cooldown by 12% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['mm_choice'] },
  ),

  passive(
    'surv_humanoid_slaying',
    'spec',
    'survival',
    3,
    { global: { meleeDmgPct: 0.02 }, stats: { agi: 1 } },
    'x',
    'Monsterbane',
    'Increases physical damage by 2% and Agility by 1 per rank.',
    0,
    0,
  ),
  passive(
    'surv_savage_strikes',
    'spec',
    'survival',
    3,
    { stats: { crit: 0.01 }, ability: [{ ability: 'raptor_strike', dmgPct: 0.05 }] },
    'x',
    'Merciless Strikes',
    'Increases critical strike chance by 1% per rank. Increases Gutting Strike damage by 5% per rank.',
    0,
    2,
  ),
  passive(
    'surv_imp_wing_clip',
    'spec',
    'survival',
    2,
    { ability: [{ ability: 'wing_clip', costPct: -0.2, dmgPct: 0.1 }] },
    'v',
    'Improved Fettering Slash',
    'Increases Fettering Slash damage by 10% per rank. Reduces Fettering Slash cost by 20% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['surv_humanoid_slaying'] },
  ),
  passive(
    'surv_deterrence',
    'spec',
    'survival',
    2,
    { stats: { dodge: 0.025 } },
    'o',
    'Bristleguard',
    'Increases dodge by 2.5% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'surv_choice',
    'spec',
    'survival',
    '@',
    'Bitter Lessons',
    'Choose one Fieldcraft refinement.',
    2,
    1,
    [
      {
        id: 'surv_choice_counter',
        name: 'Answering Fang',
        icon: 'x',
        description: 'Counterfang deals 30% more damage.',
        effect: { ability: [{ ability: 'mongoose_bite', dmgPct: 0.3 }] },
      },
      {
        id: 'surv_choice_killer',
        name: 'Killing Calm',
        icon: 'x',
        description: 'Increases critical strike by 4%.',
        effect: { stats: { crit: 0.04 } },
      },
      {
        id: 'surv_choice_surefooted',
        name: 'Steadfoot',
        icon: 'o',
        description: 'Increases Agility by 5. Increases dodge chance by 3%.',
        effect: { stats: { agi: 5, dodge: 0.03 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'surv_lightning_reflexes',
    'spec',
    'survival',
    2,
    { stats: { agi: 5, dodge: 0.01 } },
    '>',
    'Quickblood',
    'Increases Agility by 5 and dodge by 1% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['surv_choice'] },
  ),
];

const MAGE_CLASS: TalentNode[] = [
  passive(
    'mag_arcane_focus',
    'class',
    undefined,
    3,
    { ability: [{ ability: 'arcane_missiles', costPct: -0.06 }], stats: { int: 1 } },
    '*',
    'Aetheric Aim',
    'Reduces Aether Darts cost by 6% per rank. Increases Intellect by 1 per rank.',
    0,
    0,
  ),
  passive(
    'mag_elemental_precision',
    'class',
    undefined,
    3,
    {
      ability: [
        { ability: 'fireball', costPct: -0.04 },
        { ability: 'frostbolt', costPct: -0.04 },
      ],
    },
    'v',
    'Elemental Rigor',
    'Reduces Cinderbolt and Rimelance costs by 4% per rank.',
    0,
    2,
  ),
  passive(
    'mag_wand_specialization',
    'class',
    undefined,
    2,
    { stats: { ap: 6, int: 2 } },
    '/',
    'Wandcraft',
    'Increases attack power by 6 per rank. Increases Intellect by 2 per rank.',
    1,
    0,
    { requires: ['mag_arcane_focus'] },
  ),
  passive(
    'mag_flame_throwing',
    'class',
    undefined,
    2,
    {
      ability: [
        { ability: 'fire_blast', dmgPct: 0.12 },
        { ability: 'scorch', dmgPct: 0.12 },
      ],
    },
    '*',
    'Farflame',
    'Increases Cinderfall and Scald damage by 12% per rank.',
    1,
    1,
    { pointsGate: 2 },
  ),
  passive(
    'mag_ice_shards',
    'class',
    undefined,
    3,
    { stats: { crit: 0.01 } },
    'x',
    'Splinterfrost',
    'Increases critical strike chance by 1% per rank.',
    1,
    2,
    { requires: ['mag_elemental_precision'] },
  ),
  choice(
    'mag_school_focus',
    'class',
    undefined,
    '@',
    'School Focus',
    'Choose one mage school emphasis.',
    2,
    1,
    [
      {
        id: 'mag_school_arcane',
        name: 'Aetheric Mind',
        icon: '*',
        description: 'Increases Intellect by 8%.',
        effect: { stats: { intPct: 0.08 } },
      },
      {
        id: 'mag_school_fire',
        name: 'Afterflame',
        icon: 'x',
        description: 'Increases spell damage by 6%.',
        effect: { global: { spellDmgPct: 0.06 } },
      },
      {
        id: 'mag_school_frost',
        name: 'Deep Rime',
        icon: '#',
        description: 'Increases armor by 10% and dodge by 2%.',
        effect: { stats: { armorPct: 0.1, dodge: 0.02 } },
      },
    ],
    { pointsGate: 5 },
  ),
  active(
    'mag_cold_snap',
    'class',
    undefined,
    { grant: { ability: 'frost_nova' } },
    '#',
    'Second Winter',
    'Grants early access to Icebind.',
    3,
    0,
    { pointsGate: 8, requires: ['mag_wand_specialization'] },
  ),
  passive(
    'mag_clearcasting',
    'class',
    undefined,
    2,
    {
      ability: [
        { ability: 'fireball', costPct: -0.08 },
        { ability: 'frostbolt', costPct: -0.08 },
        { ability: 'arcane_missiles', costPct: -0.08 },
      ],
    },
    'v',
    'Effortless Art',
    'Reduces core spell costs by 8% per rank.',
    3,
    2,
    { pointsGate: 8, requires: ['mag_school_focus'] },
  ),
];

const MAGE_SPECS: SpecDef[] = [
  spec(
    'arcane',
    'mage',
    'Aethermancy',
    'dps',
    '*',
    'A precision caster using mana efficiency and focused arcane barrages.',
    'arcane_missiles',
    'Aetheric Flux',
    'Increases spell damage by 8% and Intellect by 4.',
    { global: { spellDmgPct: 0.08 }, stats: { int: 4 } },
  ),
  spec(
    'fire',
    'mage',
    'Pyromancy',
    'dps',
    'x',
    'A volatile caster built around fast, high-damage Fire spells.',
    'scorch',
    'Afterflame',
    'Increases critical strike chance by 2%. Increases spell damage by 8%.',
    { global: { spellDmgPct: 0.08 }, stats: { crit: 0.02 } },
  ),
  spec(
    'frost',
    'mage',
    'Cryomancy',
    'dps',
    '#',
    'A controlling caster who trades peak burst for survival and slows.',
    'ice_barrier',
    'Brittlebreak',
    'Increases armor by 10%. Increases spell damage by 6%.',
    { global: { spellDmgPct: 0.06 }, stats: { armorPct: 0.1 } },
  ),
];

const MAGE_SPEC_NODES: TalentNode[] = [
  passive(
    'arc_imp_missiles',
    'spec',
    'arcane',
    3,
    { ability: [{ ability: 'arcane_missiles', dmgPct: 0.08 }] },
    '*',
    'Improved Aether Darts',
    'Increases Aether Darts damage by 8% per rank.',
    0,
    0,
  ),
  passive(
    'arc_arcane_concentration',
    'spec',
    'arcane',
    3,
    {
      ability: [
        { ability: 'arcane_missiles', costPct: -0.06 },
        { ability: 'polymorph', costPct: -0.06 },
      ],
    },
    'v',
    'Aetheric Poise',
    'Reduces Arcane spell costs by 6% per rank.',
    0,
    2,
  ),
  passive(
    'arc_imp_polymorph',
    'spec',
    'arcane',
    2,
    { ability: [{ ability: 'polymorph', castPct: -0.2 }] },
    'O',
    'Improved Bewitch',
    'Reduces Bewitch cast time by 20% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['arc_imp_missiles'] },
  ),
  passive(
    'arc_arcane_power',
    'spec',
    'arcane',
    2,
    { global: { spellDmgPct: 0.05 }, stats: { int: 2 } },
    '*',
    'Aether Surge',
    'Increases spell damage by 5% and Intellect by 2 per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'arc_choice',
    'spec',
    'arcane',
    '@',
    'Aetheric Thesis',
    'Choose one Aethermancy refinement.',
    2,
    1,
    [
      {
        id: 'arc_choice_presence',
        name: 'Racing Mind',
        icon: '>',
        description: 'Reduces Cinderbolt and Rimelance cast time by 20%.',
        effect: {
          ability: [
            { ability: 'fireball', castPct: -0.2 },
            { ability: 'frostbolt', castPct: -0.2 },
          ],
        },
      },
      {
        id: 'arc_choice_mind',
        name: 'Aetheric Mind',
        icon: '*',
        description: 'Increases Intellect by 10.',
        effect: { stats: { int: 10 } },
      },
      {
        id: 'arc_choice_resilience',
        name: 'Aetheric Shell',
        icon: '#',
        description: 'Increases armor by 15%.',
        effect: { stats: { armorPct: 0.15 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'arc_netherwind',
    'spec',
    'arcane',
    2,
    { ability: [{ ability: 'arcane_missiles', castPct: -0.1, dmgPct: 0.1 }] },
    '*',
    'Sablewind Focus',
    'Increases Aether Darts damage by 10% per rank. Reduces Aether Darts cast time by 10% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['arc_choice'] },
  ),

  passive(
    'fire_imp_fireball',
    'spec',
    'fire',
    3,
    { ability: [{ ability: 'fireball', castPct: -0.04, dmgPct: 0.05 }] },
    'x',
    'Improved Cinderbolt',
    'Increases Cinderbolt damage by 5% per rank. Reduces Cinderbolt cast time by 4% per rank.',
    0,
    0,
  ),
  passive(
    'fire_impact',
    'spec',
    'fire',
    3,
    { stats: { crit: 0.01 } },
    'x',
    'Short Fuse',
    'Increases critical strike chance by 1% per rank.',
    0,
    2,
  ),
  passive(
    'fire_imp_blast',
    'spec',
    'fire',
    2,
    { ability: [{ ability: 'fire_blast', cooldownPct: -0.15, dmgPct: 0.08 }] },
    '*',
    'Improved Cinderfall',
    'Increases Cinderfall damage by 8% per rank. Reduces Cinderfall cooldown by 15% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['fire_imp_fireball'] },
  ),
  passive(
    'fire_incinerate',
    'spec',
    'fire',
    2,
    { ability: [{ ability: 'scorch', dmgPct: 0.15 }] },
    'x',
    'Cremation',
    'Increases Scald damage by 15% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'fire_choice',
    'spec',
    'fire',
    '@',
    'Flashfire',
    'Choose one Pyromancy refinement.',
    2,
    1,
    [
      {
        id: 'fire_choice_combustion',
        name: 'Flashfire',
        icon: 'x',
        description: 'Increases critical strike chance by 3%. Increases spell damage by 6%.',
        effect: { global: { spellDmgPct: 0.06 }, stats: { crit: 0.03 } },
      },
      {
        id: 'fire_choice_blastwave',
        name: 'Rolling Flame',
        icon: '*',
        description: 'Aetherburst deals 25% more damage.',
        effect: { ability: [{ ability: 'arcane_explosion', dmgPct: 0.25 }] },
      },
      {
        id: 'fire_choice_flame',
        name: 'Tipping Point',
        icon: 'x',
        description: 'Increases critical strike by 5%.',
        effect: { stats: { crit: 0.05 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'fire_pyromancer',
    'spec',
    'fire',
    2,
    { global: { spellDmgPct: 0.06 }, ability: [{ ability: 'fireball', dmgPct: 0.06 }] },
    'x',
    'Pyre Tender',
    'Increases spell damage by 6% per rank. Increases Cinderbolt damage by 6% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['fire_choice'] },
  ),

  passive(
    'frost_imp_frostbolt',
    'spec',
    'frost',
    3,
    { ability: [{ ability: 'frostbolt', castPct: -0.04, dmgPct: 0.05 }] },
    '#',
    'Improved Rimelance',
    'Increases Rimelance damage by 5% per rank. Reduces Rimelance cast time by 4% per rank.',
    0,
    0,
  ),
  passive(
    'frost_permafrost',
    'spec',
    'frost',
    3,
    { stats: { armorPct: 0.04 } },
    '#',
    'Deep Rime',
    'Increases armor by 4% per rank.',
    0,
    2,
  ),
  passive(
    'frost_imp_nova',
    'spec',
    'frost',
    2,
    { ability: [{ ability: 'frost_nova', cooldownPct: -0.15, dmgPct: 0.1 }] },
    'O',
    'Improved Icebind',
    'Increases Icebind damage by 10% per rank. Reduces Icebind cooldown by 15% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['frost_imp_frostbolt'] },
  ),
  passive(
    'frost_shatter',
    'spec',
    'frost',
    2,
    { stats: { crit: 0.02 } },
    'x',
    'Brittlebreak',
    'Increases critical strike chance by 2% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'frost_choice',
    'spec',
    'frost',
    '@',
    'Icecraft',
    'Choose one Cryomancy refinement.',
    2,
    1,
    [
      {
        id: 'frost_choice_barrier',
        name: 'Frostveil',
        icon: '#',
        description: 'Frostveil absorbs 25% more.',
        effect: { ability: [{ ability: 'ice_barrier', dmgPct: 0.25 }] },
      },
      {
        id: 'frost_choice_snap',
        name: 'Second Winter',
        icon: 'O',
        description: 'Icebind cooldown is reduced by 25%.',
        effect: { ability: [{ ability: 'frost_nova', cooldownPct: -0.25 }] },
      },
      {
        id: 'frost_choice_warding',
        name: 'Winterguard',
        icon: '#',
        description: 'Increases maximum health by 10%.',
        effect: { stats: { maxHpPct: 0.1 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'frost_winter_chill',
    'spec',
    'frost',
    2,
    { ability: [{ ability: 'frostbolt', dmgPct: 0.1 }], stats: { crit: 0.01 } },
    '#',
    'Cold Shoulder',
    'Increases critical strike chance by 1% per rank. Increases Rimelance damage by 10% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['frost_choice'] },
  ),
];

const ROGUE_CLASS: TalentNode[] = [
  passive(
    'rog_malice',
    'class',
    undefined,
    3,
    { stats: { crit: 0.01 } },
    'x',
    'Ill Will',
    'Increases critical strike chance by 1% per rank.',
    0,
    0,
  ),
  passive(
    'rog_lightning_reflexes',
    'class',
    undefined,
    3,
    { stats: { dodge: 0.01, agi: 1 } },
    'o',
    'Viper Reflexes',
    'Increases dodge chance by 1% per rank. Increases Agility by 1 per rank.',
    0,
    2,
  ),
  passive(
    'rog_imp_sinister',
    'class',
    undefined,
    2,
    { ability: [{ ability: 'sinister_strike', costPct: -0.08 }] },
    'v',
    'Improved Wicked Slash',
    'Reduces Wicked Slash cost by 8% per rank.',
    1,
    0,
    { requires: ['rog_malice'] },
  ),
  passive(
    'rog_camouflage',
    'class',
    undefined,
    2,
    { ability: [{ ability: 'stealth', cooldownPct: -0.2 }], stats: { agi: 2 } },
    '>',
    'Sootcloak',
    'Increases Agility by 2 per rank. Reduces Duskveil cooldown by 20% per rank.',
    1,
    1,
    { pointsGate: 2 },
  ),
  passive(
    'rog_deflection',
    'class',
    undefined,
    3,
    { stats: { dodge: 0.01 } },
    'o',
    'Blade Turn',
    'Increases dodge by 1% per rank.',
    1,
    2,
    { requires: ['rog_lightning_reflexes'] },
  ),
  choice(
    'rog_dirty_tricks',
    'class',
    undefined,
    '@',
    'Foul Play',
    'Choose one rogue emphasis.',
    2,
    1,
    [
      {
        id: 'rog_trick_poison',
        name: 'Cruel Venoms',
        icon: 'x',
        description: 'Increases finisher damage by 8%.',
        effect: { ability: [{ ability: 'eviscerate', dmgPct: 0.08 }] },
      },
      {
        id: 'rog_trick_blade',
        name: 'Mirrored Blades',
        icon: '/',
        description: 'Increases melee ability damage by 8%.',
        effect: { global: { meleeDmgPct: 0.08 } },
      },
      {
        id: 'rog_trick_shadow',
        name: 'Hush Money',
        icon: 'o',
        description: 'Increases dodge by 5%.',
        effect: { stats: { dodge: 0.05 } },
      },
    ],
    { pointsGate: 5 },
  ),
  active(
    'rog_preparation',
    'class',
    undefined,
    { grant: { ability: 'sprint' } },
    '>',
    'Contingency',
    'Grants early access to Swift Heels.',
    3,
    0,
    { pointsGate: 8, requires: ['rog_imp_sinister'] },
  ),
  passive(
    'rog_vigor',
    'class',
    undefined,
    2,
    { stats: { agi: 4, ap: 6 } },
    '+',
    'Stolen Breath',
    'Increases Agility by 4 per rank. Increases attack power by 6 per rank.',
    3,
    2,
    { pointsGate: 8, requires: ['rog_dirty_tricks'] },
  ),
];

const ROGUE_SPECS: SpecDef[] = [
  spec(
    'assassination',
    'rogue',
    'Knifework',
    'dps',
    'x',
    'A burst specialist using critical strikes and finishers.',
    'eviscerate',
    'Redhanded',
    'Increases critical strike chance by 3%. Increases Dirt Nap damage by 8%.',
    { stats: { crit: 0.03 }, ability: [{ ability: 'eviscerate', dmgPct: 0.08 }] },
  ),
  spec(
    'combat',
    'rogue',
    'Thuggery',
    'dps',
    '/',
    'A sustained fighter focused on direct weapon strikes.',
    'adrenaline_rush',
    "Scrapper's Edge",
    'Increases melee ability damage by 10%.',
    { global: { meleeDmgPct: 0.1 } },
  ),
  spec(
    'subtlety',
    'rogue',
    'Skulduggery',
    'dps',
    '>',
    'A stealth attacker built around openers, control, and avoidance.',
    'ambush',
    'False Face',
    'Increases Agility by 4. Increases critical strike chance by 2%.',
    { stats: { agi: 4, crit: 0.02 } },
  ),
];

const ROGUE_SPEC_NODES: TalentNode[] = [
  passive(
    'ass_imp_eviscerate',
    'spec',
    'assassination',
    3,
    { ability: [{ ability: 'eviscerate', dmgPct: 0.08 }] },
    'x',
    'Improved Dirt Nap',
    'Increases Dirt Nap damage by 8% per rank.',
    0,
    0,
  ),
  passive(
    'ass_remorseless',
    'spec',
    'assassination',
    3,
    { stats: { crit: 0.01 } },
    'x',
    'Pitiless Blows',
    'Increases critical strike chance by 1% per rank.',
    0,
    2,
  ),
  passive(
    'ass_murder',
    'spec',
    'assassination',
    2,
    { global: { meleeDmgPct: 0.04 } },
    'x',
    'Dirty Work',
    'Increases melee ability damage by 4% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['ass_imp_eviscerate'] },
  ),
  passive(
    'ass_laceration',
    'spec',
    'assassination',
    2,
    {
      ability: [
        { ability: 'slice_and_dice', costPct: -0.12 },
        { ability: 'kidney_shot', costPct: -0.12 },
      ],
    },
    'v',
    'Ceaseless Cuts',
    'Reduces finisher costs by 12% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'ass_choice',
    'spec',
    'assassination',
    '@',
    "Killer's Calm",
    'Choose one Knifework refinement.',
    2,
    1,
    [
      {
        id: 'ass_choice_cold',
        name: "Killer's Calm",
        icon: 'x',
        description: 'Increases critical strike by 5%.',
        effect: { stats: { crit: 0.05 } },
      },
      {
        id: 'ass_choice_seal',
        name: 'Final Notice',
        icon: '+',
        description: 'Increases Agility by 8.',
        effect: { stats: { agi: 8 } },
      },
      {
        id: 'ass_choice_vile',
        name: 'Vile Precision',
        icon: 'x',
        description: 'Dirt Nap deals 18% more damage.',
        effect: { ability: [{ ability: 'eviscerate', dmgPct: 0.18 }] },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'ass_vigor',
    'spec',
    'assassination',
    2,
    { ability: [{ ability: 'eviscerate', costPct: -0.1, dmgPct: 0.08 }] },
    'x',
    'Grim Vigor',
    'Increases Dirt Nap damage by 8% per rank. Reduces Dirt Nap cost by 10% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['ass_choice'] },
  ),

  passive(
    'combat_imp_gouge',
    'spec',
    'combat',
    3,
    { ability: [{ ability: 'gouge', cooldownPct: -0.08, dmgPct: 0.08 }] },
    'o',
    'Improved Eye Jab',
    'Increases Eye Jab damage by 8% per rank. Reduces Eye Jab cooldown by 8% per rank.',
    0,
    0,
  ),
  passive(
    'combat_precision',
    'spec',
    'combat',
    3,
    { stats: { ap: 8 } },
    '/',
    'Dead Aim',
    'Increases attack power by 8 per rank.',
    0,
    2,
  ),
  passive(
    'combat_imp_sprint',
    'spec',
    'combat',
    2,
    { ability: [{ ability: 'sprint', cooldownPct: -0.2 }] },
    '>',
    'Improved Swift Heels',
    'Reduces Swift Heels cooldown by 20% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['combat_imp_gouge'] },
  ),
  passive(
    'combat_dual_wield',
    'spec',
    'combat',
    2,
    { ability: [{ ability: 'sinister_strike', dmgPct: 0.1 }] },
    '/',
    'Practiced Steel',
    'Increases Wicked Slash damage by 10% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'combat_choice',
    'spec',
    'combat',
    '@',
    "Brawler's Way",
    'Choose one Thuggery refinement.',
    2,
    1,
    [
      {
        id: 'combat_choice_flurry',
        name: 'Mirrored Blades',
        icon: '/',
        description: 'Increases melee ability damage by 10%.',
        effect: { global: { meleeDmgPct: 0.1 } },
      },
      {
        id: 'combat_choice_riposte',
        name: 'Turnabout',
        icon: 'o',
        description: 'Increases dodge chance by 3%. Increases attack power by 12.',
        effect: { stats: { dodge: 0.03, ap: 12 } },
      },
      {
        id: 'combat_choice_adrenaline',
        name: 'Quickened Blood',
        icon: '>',
        description: 'Reduces Quickened Blood cooldown by 25%.',
        effect: { ability: [{ ability: 'adrenaline_rush', cooldownPct: -0.25 }] },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'combat_weapon_mastery',
    'spec',
    'combat',
    2,
    { stats: { apPct: 0.08 }, ability: [{ ability: 'sinister_strike', costPct: -0.06 }] },
    '/',
    'Weapon Mastery',
    'Increases attack power by 8% per rank. Reduces Wicked Slash cost by 6% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['combat_choice'] },
  ),

  passive(
    'sub_master_deception',
    'spec',
    'subtlety',
    3,
    { ability: [{ ability: 'stealth', cooldownPct: -0.1 }], stats: { agi: 1 } },
    '>',
    'False Face',
    'Increases Agility by 1 per rank. Reduces Duskveil cooldown by 10% per rank.',
    0,
    0,
  ),
  passive(
    'sub_opportunity',
    'spec',
    'subtlety',
    3,
    {
      ability: [
        { ability: 'backstab', dmgPct: 0.08 },
        { ability: 'ambush', dmgPct: 0.08 },
      ],
    },
    'x',
    'Low Cunning',
    "Increases Craven Thrust and Lurker's Strike damage by 8% per rank.",
    0,
    2,
  ),
  passive(
    'sub_elusiveness',
    'spec',
    'subtlety',
    2,
    { ability: [{ ability: 'evasion', cooldownPct: -0.15 }] },
    'o',
    "Eel's Grace",
    'Reduces Ghostfoot cooldown by 15% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['sub_master_deception'] },
  ),
  passive(
    'sub_imp_ambush',
    'spec',
    'subtlety',
    2,
    { ability: [{ ability: 'ambush', costPct: -0.1, dmgPct: 0.12 }] },
    'x',
    "Improved Lurker's Strike",
    "Increases Lurker's Strike damage by 12% per rank. Reduces Lurker's Strike cost by 10% per rank.",
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'sub_choice',
    'spec',
    'subtlety',
    '@',
    'Night Trade',
    'Choose one Skulduggery refinement.',
    2,
    1,
    [
      {
        id: 'sub_choice_hemo',
        name: 'Red Ribbon',
        icon: 'x',
        description: 'Craven Thrust deals 22% more damage.',
        effect: { ability: [{ ability: 'backstab', dmgPct: 0.22 }] },
      },
      {
        id: 'sub_choice_prep',
        name: 'Contingency',
        icon: '>',
        description: 'Reduces Swift Heels cooldown by 20%. Reduces Ghostfoot cooldown by 20%.',
        effect: {
          ability: [
            { ability: 'sprint', cooldownPct: -0.2 },
            { ability: 'evasion', cooldownPct: -0.2 },
          ],
        },
      },
      {
        id: 'sub_choice_senses',
        name: 'Hush Money',
        icon: 'o',
        description: 'Increases dodge by 5%.',
        effect: { stats: { dodge: 0.05 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'sub_shadowstep',
    'spec',
    'subtlety',
    2,
    { stats: { agi: 4, crit: 0.01 }, ability: [{ ability: 'ambush', cooldownPct: -0.1 }] },
    '>',
    'Shadeslip',
    "Increases Agility by 4 per rank. Increases critical strike chance by 1% per rank. Reduces Lurker's Strike cooldown by 10% per rank.",
    3,
    1,
    { pointsGate: 8, requires: ['sub_choice'] },
  ),
];

const PRIEST_CLASS: TalentNode[] = [
  passive(
    'pri_wand_specialization',
    'class',
    undefined,
    3,
    { stats: { int: 1, spi: 1 } },
    '/',
    'Baleful Rod',
    'Increases Intellect and Spirit by 1 per rank.',
    0,
    0,
  ),
  passive(
    'pri_spirit_tap',
    'class',
    undefined,
    3,
    { stats: { spi: 3 } },
    '*',
    'Soulglean',
    'Increases Spirit by 3 per rank.',
    0,
    2,
  ),
  passive(
    'pri_imp_fortitude',
    'class',
    undefined,
    2,
    { ability: [{ ability: 'power_word_fortitude', buffPct: 0.2 }], stats: { sta: 2 } },
    '+',
    'Improved Litany of Resolve',
    'Increases Stamina by 2 per rank. Increases Litany of Resolve by 20% per rank.',
    1,
    0,
    { requires: ['pri_wand_specialization'] },
  ),
  passive(
    'pri_meditation',
    'class',
    undefined,
    2,
    {
      ability: [
        { ability: 'lesser_heal', costPct: -0.08 },
        { ability: 'heal', costPct: -0.08 },
        { ability: 'flash_heal', costPct: -0.08 },
      ],
    },
    'v',
    'Nocturns',
    'Reduces healing spell costs by 8% per rank.',
    1,
    1,
    { pointsGate: 2 },
  ),
  passive(
    'pri_shadow_affinity',
    'class',
    undefined,
    3,
    {
      ability: [
        { ability: 'shadow_word_pain', costPct: -0.05 },
        { ability: 'mind_blast', costPct: -0.05 },
      ],
    },
    '*',
    'Duskbound',
    'Reduces Shadow spell costs by 5% per rank.',
    1,
    2,
    { requires: ['pri_spirit_tap'] },
  ),
  choice(
    'pri_inner_calling',
    'class',
    undefined,
    '@',
    'Veiled Calling',
    'Choose one priest emphasis.',
    2,
    1,
    [
      {
        id: 'pri_calling_disc',
        name: 'Stilled Mind',
        icon: '#',
        description: 'Psalm of Warding absorbs 18% more.',
        effect: { ability: [{ ability: 'power_word_shield', dmgPct: 0.18 }] },
      },
      {
        id: 'pri_calling_holy',
        name: 'Wrathful Psalm',
        icon: '+',
        description: 'Increases healing by 8%.',
        effect: { global: { healPct: 0.08 } },
      },
      {
        id: 'pri_calling_shadow',
        name: 'Creeping Dark',
        icon: '*',
        description: 'Increases spell damage by 8%.',
        effect: { global: { spellDmgPct: 0.08 } },
      },
    ],
    { pointsGate: 5 },
  ),
  active(
    'pri_desperate_prayer',
    'class',
    undefined,
    { grant: { ability: 'flash_heal' } },
    '+',
    'Last Prayer',
    'Grants early access to Urgent Prayer.',
    3,
    0,
    { pointsGate: 8, requires: ['pri_imp_fortitude'] },
  ),
  passive(
    'pri_enlightenment',
    'class',
    undefined,
    2,
    { stats: { int: 3, spi: 3 } },
    '*',
    'Bleak Insight',
    'Increases Intellect and Spirit by 3 per rank.',
    3,
    2,
    { pointsGate: 8, requires: ['pri_inner_calling'] },
  ),
];

const PRIEST_SPECS: SpecDef[] = [
  spec(
    'discipline',
    'priest',
    'Doctrine',
    'healer',
    '#',
    'A mitigator who shields allies and heals through controlled efficiency.',
    'power_word_shield',
    'Fixed Purpose',
    'Increases maximum health by 8%. Increases healing done by 8%.',
    { global: { healPct: 0.08 }, stats: { maxHpPct: 0.08 } },
  ),
  spec(
    'holy',
    'priest',
    'Benison',
    'healer',
    '+',
    'A direct healer with strong throughput and restorative prayers.',
    'flash_heal',
    'Grave Mercy',
    'Increases all healing done by 14%.',
    { global: { healPct: 0.14 } },
  ),
  spec(
    'shadow',
    'priest',
    'Vespers',
    'dps',
    '*',
    'A damage caster built around Shadow damage over time and mind spells.',
    'mind_flay',
    'Gloamveil',
    'Increases spell damage by 12% and armor by 8%.',
    { global: { spellDmgPct: 0.12 }, stats: { armorPct: 0.08 } },
  ),
];

const PRIEST_SPEC_NODES: TalentNode[] = [
  passive(
    'disc_unbreakable_will',
    'spec',
    'discipline',
    3,
    { stats: { sta: 2, spi: 1 } },
    '#',
    'Unbowed Mind',
    'Increases Stamina by 2 and Spirit by 1 per rank.',
    0,
    0,
  ),
  passive(
    'disc_twin_disciplines',
    'spec',
    'discipline',
    3,
    { ability: [{ ability: 'power_word_shield', dmgPct: 0.08 }] },
    '#',
    'Twofold Creed',
    'Increases Psalm of Warding absorption by 8% per rank.',
    0,
    2,
  ),
  passive(
    'disc_imp_shield',
    'spec',
    'discipline',
    2,
    { ability: [{ ability: 'power_word_shield', cooldownPct: -0.15, costPct: -0.08 }] },
    '#',
    'Improved Psalm of Warding',
    'Reduces Psalm of Warding cost by 8% per rank. Reduces Psalm of Warding cooldown by 15% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['disc_unbreakable_will'] },
  ),
  passive(
    'disc_mental_agility',
    'spec',
    'discipline',
    2,
    {
      ability: [
        { ability: 'renew', costPct: -0.1 },
        { ability: 'power_word_shield', costPct: -0.1 },
      ],
    },
    'v',
    'Nimble Mind',
    'Reduces instant support spell costs by 10% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'disc_choice',
    'spec',
    'discipline',
    '@',
    'Doctrine Focus',
    'Choose one Doctrine refinement.',
    2,
    1,
    [
      {
        id: 'disc_choice_barrier',
        name: 'Cold Comfort',
        icon: '#',
        description: 'Increases Psalm of Warding damage by 25%.',
        effect: { ability: [{ ability: 'power_word_shield', dmgPct: 0.25 }] },
      },
      {
        id: 'disc_choice_focus',
        name: 'Stilled Mind',
        icon: '*',
        description: 'Healing spells cost 15% less.',
        effect: {
          ability: [
            { ability: 'lesser_heal', costPct: -0.15 },
            { ability: 'heal', costPct: -0.15 },
            { ability: 'flash_heal', costPct: -0.15 },
          ],
        },
      },
      {
        id: 'disc_choice_power',
        name: 'Anointing',
        icon: '+',
        description: 'Increases healing and spell damage by 6%.',
        effect: { global: { healPct: 0.06, spellDmgPct: 0.06 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'disc_penance',
    'spec',
    'discipline',
    2,
    { global: { healPct: 0.05 }, ability: [{ ability: 'smite', dmgPct: 0.08 }] },
    '+',
    'Chastisement',
    'Increases healing done by 5% per rank. Increases Smite damage by 8% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['disc_choice'] },
  ),

  passive(
    'holy_healing_focus',
    'spec',
    'holy',
    3,
    {
      ability: [
        { ability: 'lesser_heal', dmgPct: 0.06 },
        { ability: 'heal', dmgPct: 0.06 },
      ],
    },
    '+',
    'Steadied Prayer',
    'Increases direct healing by 6% per rank.',
    0,
    0,
  ),
  passive(
    'holy_renewal',
    'spec',
    'holy',
    3,
    { ability: [{ ability: 'renew', dmgPct: 0.08 }] },
    '+',
    'Improved Lingering Grace',
    'Increases Lingering Grace healing by 8% per rank.',
    0,
    2,
  ),
  passive(
    'holy_divine_fury',
    'spec',
    'holy',
    2,
    {
      ability: [
        { ability: 'heal', castPct: -0.1 },
        { ability: 'smite', castPct: -0.05 },
      ],
    },
    '>',
    'Wrathful Psalm',
    'Reduces Solemn Prayer cast time by 10% per rank. Reduces Smite cast time by 5% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['holy_healing_focus'] },
  ),
  passive(
    'holy_inspiration',
    'spec',
    'holy',
    2,
    { stats: { armorPct: 0.05 }, global: { healPct: 0.03 } },
    '#',
    'Small Mercies',
    'Increases armor by 5% per rank. Increases healing done by 3% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'holy_priest_choice',
    'spec',
    'holy',
    '@',
    'Deepword',
    'Choose one Benison refinement.',
    2,
    1,
    [
      {
        id: 'holy_priest_choice_spirit',
        name: 'Ghostlight',
        icon: '*',
        description: 'Increases Spirit by 10.',
        effect: { stats: { spi: 10 } },
      },
      {
        id: 'holy_priest_choice_nova',
        name: 'Reaching Word',
        icon: '+',
        description: 'Smite and Holy heals are 8% stronger.',
        effect: { global: { healPct: 0.08 }, ability: [{ ability: 'smite', dmgPct: 0.08 }] },
      },
      {
        id: 'holy_priest_choice_prayer',
        name: 'Gathered Prayers',
        icon: 'v',
        description: 'Healing spells cost 12% less.',
        effect: {
          ability: [
            { ability: 'lesser_heal', costPct: -0.12 },
            { ability: 'heal', costPct: -0.12 },
            { ability: 'flash_heal', costPct: -0.12 },
          ],
        },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'holy_spiritual_healing',
    'spec',
    'holy',
    2,
    { global: { healPct: 0.07 }, stats: { crit: 0.01 } },
    '+',
    'Grave Mercy',
    'Increases critical strike chance by 1% per rank. Increases healing done by 7% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['holy_priest_choice'] },
  ),

  passive(
    'shadow_blackout',
    'spec',
    'shadow',
    3,
    { ability: [{ ability: 'mind_blast', dmgPct: 0.06 }] },
    '*',
    'Snuffed Light',
    'Increases Mindfracture damage by 6% per rank.',
    0,
    0,
  ),
  passive(
    'shadow_word_pain',
    'spec',
    'shadow',
    3,
    { ability: [{ ability: 'shadow_word_pain', dmgPct: 0.08 }] },
    '*',
    'Improved Dirge of Decay',
    'Increases Dirge of Decay damage by 8% per rank.',
    0,
    2,
  ),
  passive(
    'shadow_mind_flay',
    'spec',
    'shadow',
    2,
    { ability: [{ ability: 'mind_flay', dmgPct: 0.12, costPct: -0.08 }] },
    '*',
    'Improved Litany of Woe',
    'Increases Litany of Woe damage by 12% per rank. Reduces Litany of Woe cost by 8% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['shadow_blackout'] },
  ),
  passive(
    'shadow_focus',
    'spec',
    'shadow',
    2,
    { global: { spellDmgPct: 0.04 } },
    'x',
    'Umbral Intent',
    'Increases spell damage by 4% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'shadow_choice',
    'spec',
    'shadow',
    '@',
    'Black Office',
    'Choose one Vespers refinement.',
    2,
    1,
    [
      {
        id: 'shadow_choice_vampiric',
        name: 'Leeching Dirge',
        icon: '+',
        description: 'Increases maximum health by 8%. Increases spell damage by 4%.',
        effect: { stats: { maxHpPct: 0.08 }, global: { spellDmgPct: 0.04 } },
      },
      {
        id: 'shadow_choice_silence',
        name: 'Silent Treatment',
        icon: 'O',
        description: 'Mindfracture cooldown is reduced by 20%.',
        effect: { ability: [{ ability: 'mind_blast', cooldownPct: -0.2 }] },
      },
      {
        id: 'shadow_choice_darkness',
        name: 'Creeping Dark',
        icon: '*',
        description: 'Increases spell damage by 10%.',
        effect: { global: { spellDmgPct: 0.1 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'shadow_shadowform',
    'spec',
    'shadow',
    2,
    { global: { spellDmgPct: 0.07 }, stats: { armorPct: 0.05 } },
    '*',
    'Gloamveil',
    'Increases armor by 5% per rank. Increases spell damage by 7% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['shadow_choice'] },
  ),
];

const SHAMAN_CLASS: TalentNode[] = [
  passive(
    'sha_convection',
    'class',
    undefined,
    3,
    {
      ability: [
        { ability: 'lightning_bolt', costPct: -0.05 },
        { ability: 'earth_shock', costPct: -0.05 },
      ],
    },
    'v',
    'Latent Charge',
    'Reduces Arc Bolt and Earthen Jolt costs by 5% per rank.',
    0,
    0,
  ),
  passive(
    'sha_ancestral_knowledge',
    'class',
    undefined,
    3,
    { stats: { int: 2 } },
    '*',
    'Ancient Lore',
    'Increases Intellect by 2 per rank.',
    0,
    2,
  ),
  passive(
    'sha_shielding',
    'class',
    undefined,
    2,
    { ability: [{ ability: 'lightning_shield', dmgPct: 0.15 }], stats: { armorPct: 0.03 } },
    '#',
    'Improved Thunder Ward',
    'Increases armor by 3% per rank. Increases Thunder Ward damage by 15% per rank.',
    1,
    0,
    { requires: ['sha_convection'] },
  ),
  passive(
    'sha_thundering_strikes',
    'class',
    undefined,
    2,
    { stats: { crit: 0.015 } },
    'x',
    'Thunderous Blows',
    'Increases critical strike chance by 1.5% per rank.',
    1,
    1,
    { pointsGate: 2 },
  ),
  passive(
    'sha_tidal_focus',
    'class',
    undefined,
    3,
    { ability: [{ ability: 'healing_wave', costPct: -0.05 }] },
    '+',
    'Serene Waters',
    'Reduces Mending Waters cost by 5% per rank.',
    1,
    2,
    { requires: ['sha_ancestral_knowledge'] },
  ),
  choice(
    'sha_elemental_calling',
    'class',
    undefined,
    '@',
    'Path of Spirits',
    'Choose one shaman emphasis.',
    2,
    1,
    [
      {
        id: 'sha_calling_elemental',
        name: 'Earthen Fury',
        icon: '*',
        description: 'Increases spell damage by 8%.',
        effect: { global: { spellDmgPct: 0.08 } },
      },
      {
        id: 'sha_calling_enhance',
        name: 'Frenzied Tempo',
        icon: 'x',
        description: 'Increases melee ability damage by 8%.',
        effect: { global: { meleeDmgPct: 0.08 } },
      },
      {
        id: 'sha_calling_restoration',
        name: 'Soothing Grace',
        icon: '+',
        description: 'Increases healing by 8%.',
        effect: { global: { healPct: 0.08 } },
      },
    ],
    { pointsGate: 5 },
  ),
  active(
    'sha_ghost_wolf',
    'class',
    undefined,
    { grant: { ability: 'ghost_wolf' } },
    '>',
    'Improved Shadewolf',
    'Grants early access to Shadewolf.',
    3,
    0,
    { pointsGate: 8, requires: ['sha_shielding'] },
  ),
  passive(
    'sha_natures_guidance',
    'class',
    undefined,
    2,
    { stats: { int: 3, sta: 3 } },
    '+',
    'Sure Footing',
    'Increases Intellect and Stamina by 3 per rank.',
    3,
    2,
    { pointsGate: 8, requires: ['sha_elemental_calling'] },
  ),
];

const SHAMAN_SPECS: SpecDef[] = [
  spec(
    'elemental',
    'shaman',
    'Thundercall',
    'dps',
    '*',
    'A ranged caster who calls lightning, flame, and frost.',
    'lightning_bolt',
    'Earthen Fury',
    'Increases critical strike chance by 2%. Increases spell damage by 10%.',
    { global: { spellDmgPct: 0.1 }, stats: { crit: 0.02 } },
  ),
  spec(
    'enhancement',
    'shaman',
    'Warspirit',
    'dps',
    'x',
    'A weapon fighter who channels the storm through melee swings.',
    'stormstrike',
    'Skyrend',
    'Increases attack power by 10. Increases melee ability damage by 10%.',
    { global: { meleeDmgPct: 0.1 }, stats: { ap: 10 } },
  ),
  spec(
    'restoration',
    'shaman',
    'Spiritmend',
    'healer',
    '+',
    'A healer using ancestral waves and efficient nature magic.',
    'healing_wave',
    'Cleansing Tides',
    'Increases healing done by 14%.',
    { global: { healPct: 0.14 } },
  ),
];

const SHAMAN_SPEC_NODES: TalentNode[] = [
  passive(
    'ele_concussion',
    'spec',
    'elemental',
    3,
    {
      ability: [
        { ability: 'lightning_bolt', dmgPct: 0.06 },
        { ability: 'earth_shock', dmgPct: 0.06 },
      ],
    },
    '*',
    'Fault Line',
    'Increases Arc Bolt and Earthen Jolt damage by 6% per rank.',
    0,
    0,
  ),
  passive(
    'ele_call_flame',
    'spec',
    'elemental',
    3,
    { ability: [{ ability: 'flame_shock', dmgPct: 0.08 }] },
    'x',
    'Ashen Call',
    'Increases Cinder Jolt damage by 8% per rank.',
    0,
    2,
  ),
  passive(
    'ele_reverberation',
    'spec',
    'elemental',
    2,
    {
      ability: [
        { ability: 'earth_shock', cooldownPct: -0.12 },
        { ability: 'frost_shock', cooldownPct: -0.12 },
      ],
    },
    '>',
    'Lingering Echo',
    'Reduces Shock cooldowns by 12% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['ele_concussion'] },
  ),
  passive(
    'ele_elemental_focus',
    'spec',
    'elemental',
    2,
    {
      ability: [
        { ability: 'lightning_bolt', costPct: -0.1 },
        { ability: 'flame_shock', costPct: -0.1 },
      ],
    },
    'v',
    'Primal Clarity',
    'Reduces offensive spell costs by 10% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'ele_choice',
    'spec',
    'elemental',
    '@',
    'Primal Mastery',
    'Choose one Thundercall refinement.',
    2,
    1,
    [
      {
        id: 'ele_choice_mastery',
        name: 'Primal Mastery',
        icon: '*',
        description: 'Increases spell damage by 10%.',
        effect: { global: { spellDmgPct: 0.1 } },
      },
      {
        id: 'ele_choice_devastation',
        name: 'Shattered Earth',
        icon: 'x',
        description: 'Increases critical strike by 5%.',
        effect: { stats: { crit: 0.05 } },
      },
      {
        id: 'ele_choice_storm',
        name: 'Arcing Reach',
        icon: '>',
        description: 'Arc Bolt casts 20% faster.',
        effect: { ability: [{ ability: 'lightning_bolt', castPct: -0.2 }] },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'ele_lightning_mastery',
    'spec',
    'elemental',
    2,
    { ability: [{ ability: 'lightning_bolt', castPct: -0.08, dmgPct: 0.1 }] },
    '*',
    'Arc Mastery',
    'Increases Arc Bolt damage by 10% per rank. Reduces Arc Bolt cast time by 8% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['ele_choice'] },
  ),

  passive(
    'enh_ancestral_weapons',
    'spec',
    'enhancement',
    3,
    { stats: { ap: 8 } },
    'x',
    'Elder Arms',
    'Increases attack power by 8 per rank.',
    0,
    0,
  ),
  passive(
    'enh_shield_spec',
    'spec',
    'enhancement',
    3,
    { stats: { armorPct: 0.04, dodge: 0.005 } },
    '#',
    'Stalwart Shield',
    'Increases armor by 4% per rank. Increases dodge chance by 0.5% per rank.',
    0,
    2,
  ),
  passive(
    'enh_imp_rockbiter',
    'spec',
    'enhancement',
    2,
    { ability: [{ ability: 'rockbiter_weapon', dmgPct: 0.2 }] },
    'x',
    'Improved Stonebound',
    'Increases Stonebound Weapon damage by 20% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['enh_ancestral_weapons'] },
  ),
  passive(
    'enh_flurry',
    'spec',
    'enhancement',
    2,
    { stats: { crit: 0.02 } },
    '>',
    'Frenzied Tempo',
    'Increases critical strike chance by 2% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'enh_choice',
    'spec',
    'enhancement',
    '@',
    'Thunder Path',
    'Choose one Warspirit refinement.',
    2,
    1,
    [
      {
        id: 'enh_choice_stormstrike',
        name: 'Ancestral Strike',
        icon: 'x',
        description: 'Ancestral Strike deals 25% more damage.',
        effect: { ability: [{ ability: 'stormstrike', dmgPct: 0.25 }] },
      },
      {
        id: 'enh_choice_toughness',
        name: 'Earthen Grit',
        icon: '#',
        description: 'Increases armor by 12%. Increases Stamina by 4.',
        effect: { stats: { armorPct: 0.12, sta: 4 } },
      },
      {
        id: 'enh_choice_weapon',
        name: 'Honed Edge',
        icon: 'x',
        description: 'Increases melee damage by 10%.',
        effect: { global: { meleeDmgPct: 0.1 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'enh_spirit_weapons',
    'spec',
    'enhancement',
    2,
    {
      ability: [{ ability: 'stormstrike', cooldownPct: -0.12, costPct: -0.08 }],
      global: { meleeDmgPct: 0.04 },
    },
    'x',
    'Spiritforged Arms',
    'Increases melee ability damage by 4% per rank. Reduces Ancestral Strike cost by 8% per rank. Reduces Ancestral Strike cooldown by 12% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['enh_choice'] },
  ),

  passive(
    'rest_tidal_focus',
    'spec',
    'restoration',
    3,
    { ability: [{ ability: 'healing_wave', costPct: -0.06 }] },
    'v',
    'Serene Waters',
    'Reduces Mending Waters cost by 6% per rank.',
    0,
    0,
  ),
  passive(
    'rest_imp_healing_wave',
    'spec',
    'restoration',
    3,
    { ability: [{ ability: 'healing_wave', castPct: -0.05, dmgPct: 0.05 }] },
    '+',
    'Improved Mending Waters',
    'Increases Mending Waters damage by 5% per rank. Reduces Mending Waters cast time by 5% per rank.',
    0,
    2,
  ),
  passive(
    'rest_ancestral_healing',
    'spec',
    'restoration',
    2,
    { stats: { armorPct: 0.05 }, global: { healPct: 0.03 } },
    '#',
    "Ancestor's Mercy",
    'Increases armor by 5% per rank. Increases healing done by 3% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['rest_tidal_focus'] },
  ),
  passive(
    'rest_healing_grace',
    'spec',
    'restoration',
    2,
    { global: { healPct: 0.04 }, stats: { spi: 2 } },
    '+',
    'Soothing Grace',
    'Increases Spirit by 2 per rank. Increases healing done by 4% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'rest_choice',
    'spec',
    'restoration',
    '@',
    'Tidesworn Path',
    'Choose one Spiritmend refinement.',
    2,
    1,
    [
      {
        id: 'rest_choice_swiftness',
        name: 'Rushing Waters',
        icon: '>',
        description: 'Mending Waters casts 25% faster.',
        effect: { ability: [{ ability: 'healing_wave', castPct: -0.25 }] },
      },
      {
        id: 'rest_choice_mana',
        name: 'Springflood',
        icon: 'v',
        description: 'Mending Waters costs 18% less.',
        effect: { ability: [{ ability: 'healing_wave', costPct: -0.18 }] },
      },
      {
        id: 'rest_choice_purification',
        name: 'Cleansing Tides',
        icon: '+',
        description: 'Increases healing by 10%.',
        effect: { global: { healPct: 0.1 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'rest_chain_focus',
    'spec',
    'restoration',
    2,
    { global: { healPct: 0.07 }, stats: { int: 2 } },
    '+',
    'Guiding Spirits',
    'Increases Intellect by 2 per rank. Increases healing done by 7% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['rest_choice'] },
  ),
];

const WARLOCK_CLASS: TalentNode[] = [
  passive(
    'wlk_suppression',
    'class',
    undefined,
    3,
    {
      ability: [
        { ability: 'corruption', costPct: -0.05 },
        { ability: 'curse_of_agony', costPct: -0.05 },
      ],
    },
    'v',
    'Stifling Grasp',
    'Reduces Affliction spell costs by 5% per rank.',
    0,
    0,
  ),
  passive(
    'wlk_demonic_embrace',
    'class',
    undefined,
    3,
    { stats: { sta: 2 } },
    '+',
    'Fiendish Fortitude',
    'Increases Stamina by 2 per rank.',
    0,
    2,
  ),
  passive(
    'wlk_imp_corruption',
    'class',
    undefined,
    2,
    { ability: [{ ability: 'corruption', castPct: -0.35, dmgPct: 0.05 }] },
    '*',
    'Improved Blackrot',
    'Increases Blackrot damage by 5% per rank. Reduces Blackrot cast time by 35% per rank.',
    1,
    0,
    { requires: ['wlk_suppression'] },
  ),
  passive(
    'wlk_demonic_skin',
    'class',
    undefined,
    2,
    { ability: [{ ability: 'demon_skin', dmgPct: 0.2 }], stats: { armorPct: 0.03 } },
    '#',
    'Improved Fiendhide',
    'Increases armor by 3% per rank. Increases Fiendhide damage by 20% per rank.',
    1,
    1,
    { pointsGate: 2 },
  ),
  passive(
    'wlk_cataclysm',
    'class',
    undefined,
    3,
    {
      ability: [
        { ability: 'shadow_bolt', costPct: -0.04 },
        { ability: 'immolate', costPct: -0.04 },
      ],
    },
    'x',
    'Calamity',
    'Reduces destructive spell costs by 4% per rank.',
    1,
    2,
    { requires: ['wlk_demonic_embrace'] },
  ),
  choice(
    'wlk_dark_pact',
    'class',
    undefined,
    '@',
    'Grim Bargain',
    'Choose one warlock emphasis.',
    2,
    1,
    [
      {
        id: 'wlk_pact_affliction',
        name: 'Grim Tidings',
        icon: '*',
        description: 'Increases Shadow damage by 2%.',
        effect: { global: { spellDmgPct: 0.02 } },
      },
      {
        id: 'wlk_pact_demonology',
        name: 'Blackblood Vigor',
        icon: '+',
        description: 'Increases Stamina by 8%.',
        effect: { stats: { staPct: 0.08 } },
      },
      {
        id: 'wlk_pact_destruction',
        name: 'Wrack',
        icon: 'x',
        description: 'Increases critical strike by 4%.',
        effect: { stats: { crit: 0.04 } },
      },
    ],
    { pointsGate: 5 },
  ),
  active(
    'wlk_shadowburn',
    'class',
    undefined,
    { grant: { ability: 'shadowburn' } },
    'x',
    'Duskfire',
    'Grants early access to Duskfire.',
    3,
    0,
    { pointsGate: 8, requires: ['wlk_imp_corruption'] },
  ),
  passive(
    'wlk_fel_intellect',
    'class',
    undefined,
    2,
    { stats: { int: 3, sta: 3 } },
    '+',
    'Vile Cunning',
    'Increases Intellect and Stamina by 3 per rank.',
    3,
    2,
    { pointsGate: 8, requires: ['wlk_dark_pact'] },
  ),
];

const WARLOCK_SPECS: SpecDef[] = [
  spec(
    'affliction',
    'warlock',
    'Hexcraft',
    'dps',
    '*',
    'A curse-weaver using damage over time and drains.',
    'drain_life',
    'Creeping Rot',
    'Increases Shadow spell damage by 4%.',
    { global: { spellDmgPct: 0.04 } },
  ),
  spec(
    'demonology',
    'warlock',
    'Pactbound',
    'dps',
    '+',
    'A durable warlock who survives through demonic resilience.',
    'demon_skin',
    'Fiendlore',
    'Increases Stamina by 10%. Increases armor by 10%.',
    { stats: { staPct: 0.1, armorPct: 0.1 } },
  ),
  spec(
    'destruction',
    'warlock',
    'Ruination',
    'dps',
    'x',
    'A burst caster using Gloom Bolt, fire, and Duskfire.',
    'shadowburn',
    'Desolation',
    'Increases critical strike chance by 2%. Increases spell damage by 3%.',
    { global: { spellDmgPct: 0.03 }, stats: { crit: 0.02 } },
  ),
];

const WARLOCK_SPEC_NODES: TalentNode[] = [
  passive(
    'aff_imp_agony',
    'spec',
    'affliction',
    3,
    { ability: [{ ability: 'curse_of_agony', dmgPct: 0.03 }] },
    '*',
    'Improved Hex of Anguish',
    'Increases Hex of Anguish damage by 3% per rank.',
    0,
    0,
  ),
  passive(
    'aff_imp_corruption',
    'spec',
    'affliction',
    3,
    { ability: [{ ability: 'corruption', dmgPct: 0.03 }] },
    '*',
    'Improved Blackrot',
    'Increases Blackrot damage by 3% per rank.',
    0,
    2,
  ),
  passive(
    'aff_fel_concentration',
    'spec',
    'affliction',
    2,
    { ability: [{ ability: 'drain_life', dmgPct: 0.12, costPct: -0.08 }] },
    '+',
    'Unbroken Focus',
    'Increases Consume damage by 12% per rank. Reduces Consume cost by 8% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['aff_imp_agony'] },
  ),
  passive(
    'aff_amplify_curse',
    'spec',
    'affliction',
    2,
    { ability: [{ ability: 'curse_of_agony', cooldownPct: -0.1, dmgPct: 0.1 }] },
    '*',
    'Deepened Hex',
    'Increases Hex of Anguish damage by 10% per rank. Reduces Hex of Anguish cooldown by 10% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'aff_choice',
    'spec',
    'affliction',
    '@',
    'Reaping Path',
    'Choose one Hexcraft refinement.',
    2,
    1,
    [
      {
        id: 'aff_choice_siphon',
        name: 'Veinleech',
        icon: '+',
        description: 'Increases Consume damage by 22%.',
        effect: { ability: [{ ability: 'drain_life', dmgPct: 0.22 }] },
      },
      {
        id: 'aff_choice_shadow',
        name: 'Umbral Mastery',
        icon: '*',
        description: 'Increases spell damage by 10%.',
        effect: { global: { spellDmgPct: 0.1 } },
      },
      {
        id: 'aff_choice_nightfall',
        name: 'Grim Tidings',
        icon: '>',
        description: 'Gloom Bolt casts 20% faster.',
        effect: { ability: [{ ability: 'shadow_bolt', castPct: -0.2 }] },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'aff_unstable_affliction',
    'spec',
    'affliction',
    2,
    {
      ability: [
        { ability: 'corruption', dmgPct: 0.1 },
        { ability: 'curse_of_agony', dmgPct: 0.1 },
      ],
    },
    '*',
    'Parting Gift',
    'Increases Blackrot damage by 10% per rank. Increases Hex of Anguish damage by 10% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['aff_choice'] },
  ),

  passive(
    'demo_demonic_embrace',
    'spec',
    'demonology',
    3,
    { stats: { sta: 3 } },
    '+',
    'Fiendish Fortitude',
    'Increases Stamina by 3 per rank.',
    0,
    0,
  ),
  passive(
    'demo_fel_armor',
    'spec',
    'demonology',
    3,
    { ability: [{ ability: 'demon_skin', dmgPct: 0.15 }], stats: { armorPct: 0.03 } },
    '#',
    'Vile Carapace',
    'Increases armor by 3% per rank. Increases Fiendhide damage by 15% per rank.',
    0,
    2,
  ),
  passive(
    'demo_health_funnel',
    'spec',
    'demonology',
    2,
    { ability: [{ ability: 'life_tap', dmgPct: 0.1, costPct: -0.1 }] },
    '+',
    'Improved Hard Bargain',
    'Increases Hard Bargain damage by 10% per rank. Reduces Hard Bargain cost by 10% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['demo_demonic_embrace'] },
  ),
  passive(
    'demo_master_summoner',
    'spec',
    'demonology',
    2,
    { stats: { maxHpPct: 0.04 }, ability: [{ ability: 'fear', castPct: -0.1 }] },
    'O',
    'Grand Binder',
    'Increases maximum health by 4% per rank. Reduces Harrow cast time by 10% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'demo_choice',
    'spec',
    'demonology',
    '@',
    'Court of Fiends',
    'Choose one Pactbound refinement.',
    2,
    1,
    [
      {
        id: 'demo_choice_link',
        name: 'Pain Communion',
        icon: '#',
        description: 'Increases maximum health by 14%.',
        effect: { stats: { maxHpPct: 0.14 } },
      },
      {
        id: 'demo_choice_master',
        name: 'Fiendmaster',
        icon: '*',
        description: 'Increases spell damage by 8%.',
        effect: { global: { spellDmgPct: 0.08 } },
      },
      {
        id: 'demo_choice_resilience',
        name: 'Unyielding Pact',
        icon: '+',
        description: 'Increases armor by 12%. Increases Stamina by 5.',
        effect: { stats: { armorPct: 0.12, sta: 5 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'demo_metamorphosis',
    'spec',
    'demonology',
    2,
    { stats: { staPct: 0.06, armorPct: 0.06 }, global: { spellDmgPct: 0.03 } },
    '#',
    'Dread Aspect',
    'Increases Stamina by 6% per rank. Increases armor by 6% per rank. Increases spell damage by 3% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['demo_choice'] },
  ),

  passive(
    'dest_cataclysm',
    'spec',
    'destruction',
    3,
    {
      ability: [
        { ability: 'shadow_bolt', costPct: -0.05 },
        { ability: 'immolate', costPct: -0.05 },
      ],
    },
    'v',
    'Calamity',
    'Reduces destructive spell costs by 5% per rank.',
    0,
    0,
  ),
  passive(
    'dest_bane',
    'spec',
    'destruction',
    3,
    {
      ability: [
        { ability: 'shadow_bolt', castPct: -0.01 },
        { ability: 'immolate', castPct: -0.01 },
      ],
    },
    '>',
    'Hastened Doom',
    'Reduces Gloom Bolt cast time by 1% per rank. Reduces Burning Pact cast time by 1% per rank.',
    0,
    2,
  ),
  passive(
    'dest_devastation',
    'spec',
    'destruction',
    2,
    { stats: { crit: 0.02 } },
    'x',
    'Wrack',
    'Increases critical strike chance by 2% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['dest_cataclysm'] },
  ),
  passive(
    'dest_imp_searing',
    'spec',
    'destruction',
    2,
    { ability: [{ ability: 'searing_pain', dmgPct: 0.14 }] },
    'x',
    'Improved Sear',
    'Increases Sear damage by 14% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'dest_choice',
    'spec',
    'destruction',
    '@',
    'Desolation',
    'Choose one Ruination refinement.',
    2,
    1,
    [
      {
        id: 'dest_choice_ruin',
        name: 'Desolation',
        icon: 'x',
        description: 'Increases critical strike by 5%.',
        effect: { stats: { crit: 0.05 } },
      },
      {
        id: 'dest_choice_shadowburn',
        name: 'Duskfire',
        icon: '*',
        description: 'Duskfire deals 25% more damage.',
        effect: { ability: [{ ability: 'shadowburn', dmgPct: 0.25 }] },
      },
      {
        id: 'dest_choice_emberstorm',
        name: 'Blackfire',
        icon: 'x',
        description: 'Increases Burning Pact and Sear damage by 10%.',
        effect: {
          ability: [
            { ability: 'immolate', dmgPct: 0.1 },
            { ability: 'searing_pain', dmgPct: 0.1 },
          ],
        },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'dest_backdraft',
    'spec',
    'destruction',
    2,
    { global: { spellDmgPct: 0.06 }, ability: [{ ability: 'shadowburn', cooldownPct: -0.1 }] },
    'x',
    'Flashburn',
    'Increases spell damage by 6% per rank. Reduces Duskfire cooldown by 10% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['dest_choice'] },
  ),
];

const DRUID_CLASS: TalentNode[] = [
  passive(
    'dru_natures_grasp',
    'class',
    undefined,
    3,
    { ability: [{ ability: 'entangling_roots', costPct: -0.06 }], stats: { spi: 1 } },
    'v',
    'Thicket Snare',
    'Increases Spirit by 1 per rank. Reduces Gripping Roots cost by 6% per rank.',
    0,
    0,
  ),
  passive(
    'dru_feral_aggression',
    'class',
    undefined,
    3,
    {
      ability: [
        { ability: 'maul', dmgPct: 0.05 },
        { ability: 'claw', dmgPct: 0.05 },
      ],
    },
    'x',
    'Red Hunger',
    'Increases Bonecrush and Claw damage by 5% per rank.',
    0,
    2,
  ),
  passive(
    'dru_imp_mark',
    'class',
    undefined,
    2,
    { ability: [{ ability: 'mark_of_the_wild', dmgPct: 0.2 }], stats: { armorPct: 0.03 } },
    '+',
    'Improved Wildward',
    'Increases armor by 3% per rank. Increases Wildward damage by 20% per rank.',
    1,
    0,
    { requires: ['dru_natures_grasp'] },
  ),
  passive(
    'dru_naturalist',
    'class',
    undefined,
    2,
    {
      ability: [
        { ability: 'healing_touch', castPct: -0.08 },
        { ability: 'wrath', castPct: -0.04 },
      ],
    },
    '>',
    'Woodwise',
    'Reduces Wildmend cast time by 8% per rank. Reduces Wildbolt cast time by 4% per rank.',
    1,
    1,
    { pointsGate: 2 },
  ),
  passive(
    'dru_thick_hide',
    'class',
    undefined,
    3,
    { stats: { armorPct: 0.04 } },
    '#',
    'Ironpelt',
    'Increases armor by 4% per rank.',
    1,
    2,
    { requires: ['dru_feral_aggression'] },
  ),
  choice(
    'dru_natures_path',
    'class',
    undefined,
    '@',
    'Path of Seasons',
    'Choose one druid emphasis.',
    2,
    1,
    [
      {
        id: 'dru_path_balance',
        name: 'Gentle Gloam',
        icon: '*',
        description: 'Increases spell damage by 8%.',
        effect: { global: { spellDmgPct: 0.08 } },
      },
      {
        id: 'dru_path_feral',
        name: 'Primal Heart',
        icon: 'x',
        description: 'Increases Stamina by 8%. Increases attack power by 8%.',
        effect: { stats: { staPct: 0.08, apPct: 0.08 } },
      },
      {
        id: 'dru_path_resto',
        name: "Grove's Gift",
        icon: '+',
        description: 'Increases healing by 8%.',
        effect: { global: { healPct: 0.08 } },
      },
    ],
    { pointsGate: 5 },
  ),
  active(
    'dru_barkskin',
    'class',
    undefined,
    { grant: { ability: 'barkskin' } },
    '#',
    'Oakhide',
    'Grants early access to Oakhide.',
    3,
    0,
    { pointsGate: 8, requires: ['dru_imp_mark'] },
  ),
  passive(
    'dru_furor',
    'class',
    undefined,
    2,
    { stats: { int: 3, sta: 3 } },
    '+',
    'Wildsurge',
    'Increases Intellect and Stamina by 3 per rank.',
    3,
    2,
    { pointsGate: 8, requires: ['dru_natures_path'] },
  ),
];

const DRUID_SPECS: SpecDef[] = [
  spec(
    'balance',
    'druid',
    'Moongrove',
    'dps',
    '*',
    'A caster who uses lunar and nature magic from range.',
    'starfire',
    'Moonrage',
    'Increases Intellect by 4. Increases spell damage by 10%.',
    { global: { spellDmgPct: 0.1 }, stats: { int: 4 } },
  ),
  spec(
    'feral',
    'druid',
    'Wildfang',
    'tank',
    'x',
    'A shapeshifter who tanks in bear form and fights up close.',
    'bear_form',
    'Primal Heart',
    'Increases armor by 8%. Increases threat generated by 20%. Increases melee ability damage by 6%.',
    { global: { threatPct: 0.2, meleeDmgPct: 0.06 }, stats: { armorPct: 0.08 } },
  ),
  spec(
    'restoration',
    'druid',
    'Groveheart',
    'healer',
    '+',
    'A healer using heal-over-time effects and efficient nature magic.',
    'regrowth',
    "Grove's Gift",
    'Increases healing done by 14%.',
    { global: { healPct: 0.14 } },
  ),
];

const DRUID_SPEC_NODES: TalentNode[] = [
  passive(
    'bal_imp_wrath',
    'spec',
    'balance',
    3,
    { ability: [{ ability: 'wrath', castPct: -0.04, dmgPct: 0.05 }] },
    '*',
    'Improved Wildbolt',
    'Increases Wildbolt damage by 5% per rank. Reduces Wildbolt cast time by 4% per rank.',
    0,
    0,
  ),
  passive(
    'bal_imp_moonfire',
    'spec',
    'balance',
    3,
    { ability: [{ ability: 'moonfire', dmgPct: 0.08 }] },
    '*',
    'Improved Lunar Tempest',
    'Increases Lunar Tempest damage by 8% per rank.',
    0,
    2,
  ),
  passive(
    'bal_natures_reach',
    'spec',
    'balance',
    2,
    {
      ability: [
        { ability: 'entangling_roots', castPct: -0.12 },
        { ability: 'starfire', castPct: -0.08 },
      ],
    },
    '>',
    'Reaching Boughs',
    'Reduces Gripping Roots cast time by 12% per rank. Reduces Skyfall cast time by 8% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['bal_imp_wrath'] },
  ),
  passive(
    'bal_vengeance',
    'spec',
    'balance',
    2,
    { stats: { crit: 0.02 } },
    'x',
    'Cold Reckoning',
    'Increases critical strike chance by 2% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'bal_choice',
    'spec',
    'balance',
    '@',
    'Moonwing Path',
    'Choose one Moongrove refinement.',
    2,
    1,
    [
      {
        id: 'bal_choice_moonkin',
        name: 'Moonwing Form',
        icon: '#',
        description: 'Increases armor by 14%. Increases spell damage by 6%.',
        effect: { stats: { armorPct: 0.14 }, global: { spellDmgPct: 0.06 } },
      },
      {
        id: 'bal_choice_grace',
        name: 'Starlit Grace',
        icon: '>',
        description: 'Wildbolt and Skyfall cast 15% faster.',
        effect: {
          ability: [
            { ability: 'wrath', castPct: -0.15 },
            { ability: 'starfire', castPct: -0.15 },
          ],
        },
      },
      {
        id: 'bal_choice_moonglow',
        name: 'Gentle Gloam',
        icon: 'v',
        description: 'Balance spells cost 15% less.',
        effect: {
          ability: [
            { ability: 'wrath', costPct: -0.15 },
            { ability: 'moonfire', costPct: -0.15 },
            { ability: 'starfire', costPct: -0.15 },
          ],
        },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'bal_starfire_mastery',
    'spec',
    'balance',
    2,
    { ability: [{ ability: 'starfire', dmgPct: 0.12, castPct: -0.08 }] },
    '*',
    'Skyfall Mastery',
    'Increases Skyfall damage by 12% per rank. Reduces Skyfall cast time by 8% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['bal_choice'] },
  ),

  passive(
    'feral_thick_hide',
    'spec',
    'feral',
    3,
    { stats: { armorPct: 0.05 } },
    '#',
    'Ironpelt',
    'Increases armor by 5% per rank.',
    0,
    0,
  ),
  passive(
    'feral_ferocity',
    'spec',
    'feral',
    3,
    {
      ability: [
        { ability: 'maul', costPct: -0.06 },
        { ability: 'claw', costPct: -0.06 },
      ],
    },
    'v',
    'Whetted Fangs',
    'Reduces Bonecrush and Claw cost by 6% per rank.',
    0,
    2,
  ),
  passive(
    'feral_brutal_impact',
    'spec',
    'feral',
    2,
    {
      ability: [
        { ability: 'maul', dmgPct: 0.1 },
        { ability: 'swipe', dmgPct: 0.1 },
      ],
    },
    'x',
    'Heavy Blows',
    'Increases Bonecrush damage by 10% per rank. Increases Sweeping Claws damage by 10% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['feral_thick_hide'] },
  ),
  passive(
    'feral_feline_swiftness',
    'spec',
    'feral',
    2,
    { stats: { dodge: 0.02, agi: 2 } },
    '>',
    'Swiftpaw',
    'Increases dodge chance by 2% per rank. Increases Agility by 2 per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'feral_choice',
    'spec',
    'feral',
    '@',
    'Path of Fangs',
    'Choose one Wildfang refinement.',
    2,
    1,
    [
      {
        id: 'feral_choice_bear',
        name: 'Dire Bruin',
        icon: '#',
        description: 'Increases armor by 12%. Increases threat generated by 10%.',
        effect: { stats: { armorPct: 0.12 }, global: { threatPct: 0.1 } },
      },
      {
        id: 'feral_choice_cat',
        name: "Predator's Cunning",
        icon: 'x',
        description: 'Increases melee damage by 10%.',
        effect: { global: { meleeDmgPct: 0.1 } },
      },
      {
        id: 'feral_choice_survival',
        name: 'Deathless Will',
        icon: '+',
        description: 'Increases maximum health by 14%.',
        effect: { stats: { maxHpPct: 0.14 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'feral_heart_wild',
    'spec',
    'feral',
    2,
    { stats: { staPct: 0.05, apPct: 0.05 }, global: { threatPct: 0.05 } },
    'x',
    'Primal Heart',
    'Increases Stamina by 5% per rank. Increases attack power by 5% per rank. Increases threat generated by 5% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['feral_choice'] },
  ),

  passive(
    'rest_imp_rejuv',
    'spec',
    'restoration',
    3,
    { ability: [{ ability: 'rejuvenation', dmgPct: 0.08 }] },
    '+',
    'Improved Wildbloom',
    'Increases Wildbloom healing by 8% per rank.',
    0,
    0,
  ),
  passive(
    'rest_druid_naturalist',
    'spec',
    'restoration',
    3,
    { ability: [{ ability: 'healing_touch', castPct: -0.05, dmgPct: 0.05 }] },
    '+',
    'Woodwise',
    'Increases Wildmend damage by 5% per rank. Reduces Wildmend cast time by 5% per rank.',
    0,
    2,
  ),
  passive(
    'rest_reflection',
    'spec',
    'restoration',
    2,
    {
      ability: [
        { ability: 'healing_touch', costPct: -0.1 },
        { ability: 'rejuvenation', costPct: -0.1 },
      ],
    },
    'v',
    'Quietude',
    'Reduces core healing costs by 10% per rank.',
    1,
    0,
    { pointsGate: 2, requires: ['rest_imp_rejuv'] },
  ),
  passive(
    'rest_imp_regrowth',
    'spec',
    'restoration',
    2,
    { ability: [{ ability: 'regrowth', dmgPct: 0.12 }] },
    '+',
    'Improved Second Bloom',
    'Increases Second Bloom healing by 12% per rank.',
    1,
    2,
    { pointsGate: 2 },
  ),
  choice(
    'rest_druid_choice',
    'spec',
    'restoration',
    '@',
    'Path of Renewal',
    'Choose one Groveheart refinement.',
    2,
    1,
    [
      {
        id: 'rest_druid_choice_swift',
        name: 'Swiftbloom',
        icon: '>',
        description: 'Wildmend casts 25% faster.',
        effect: { ability: [{ ability: 'healing_touch', castPct: -0.25 }] },
      },
      {
        id: 'rest_druid_choice_innervate',
        name: 'Lifesap',
        icon: 'v',
        description: 'Healing spells cost 16% less.',
        effect: {
          ability: [
            { ability: 'healing_touch', costPct: -0.16 },
            { ability: 'regrowth', costPct: -0.16 },
            { ability: 'rejuvenation', costPct: -0.16 },
          ],
        },
      },
      {
        id: 'rest_druid_choice_living',
        name: 'Evergreen Soul',
        icon: '*',
        description: 'Increases Spirit by 10.',
        effect: { stats: { spi: 10 } },
      },
    ],
    { pointsGate: 5 },
  ),
  passive(
    'rest_tree_life',
    'spec',
    'restoration',
    2,
    { global: { healPct: 0.07 }, stats: { spi: 3 } },
    '+',
    'Heartwood',
    'Increases Spirit by 3 per rank. Increases healing done by 7% per rank.',
    3,
    1,
    { pointsGate: 8, requires: ['rest_druid_choice'] },
  ),
];

export const PALADIN_TALENTS: ClassTalents = {
  class: 'paladin',
  nodes: [...PALADIN_CLASS, ...PALADIN_SPEC_NODES],
  specs: PALADIN_SPECS,
};
export const HUNTER_TALENTS: ClassTalents = {
  class: 'hunter',
  nodes: [...HUNTER_CLASS, ...HUNTER_SPEC_NODES],
  specs: HUNTER_SPECS,
};
export const MAGE_TALENTS: ClassTalents = {
  class: 'mage',
  nodes: [...MAGE_CLASS, ...MAGE_SPEC_NODES],
  specs: MAGE_SPECS,
};
export const ROGUE_TALENTS: ClassTalents = {
  class: 'rogue',
  nodes: [...ROGUE_CLASS, ...ROGUE_SPEC_NODES],
  specs: ROGUE_SPECS,
};
export const PRIEST_TALENTS: ClassTalents = {
  class: 'priest',
  nodes: [...PRIEST_CLASS, ...PRIEST_SPEC_NODES],
  specs: PRIEST_SPECS,
};
export const SHAMAN_TALENTS: ClassTalents = {
  class: 'shaman',
  nodes: [...SHAMAN_CLASS, ...SHAMAN_SPEC_NODES],
  specs: SHAMAN_SPECS,
};
export const WARLOCK_TALENTS: ClassTalents = {
  class: 'warlock',
  nodes: [...WARLOCK_CLASS, ...WARLOCK_SPEC_NODES],
  specs: WARLOCK_SPECS,
};
export const DRUID_TALENTS: ClassTalents = {
  class: 'druid',
  nodes: [...DRUID_CLASS, ...DRUID_SPEC_NODES],
  specs: DRUID_SPECS,
};
