// Surface inventory: the data ledger of every (method, path) the World of
// ClaudeCraft server dispatches today.
//
// This is a CHARACTERIZATION artifact. It records what exists across the four
// HTTP dispatchers (main handleApi, admin, oauth, internal) plus the
// createServer prefix OPTIONS-204 preflight arm, so the route-count freshness
// gate (surface_inventory.test.ts) hard-fails when a route is added or removed
// in source without updating this ledger. It never changes runtime behavior.
//
// Anchoring rule: rows anchor on SYMBOL names (handler fns, `*Match` regex
// consts) and route STRINGS, never on line numbers.
//
// Scope note: the static / SSR content prefix routes dispatched in
// routeHttpRequest (GET /p/* card pages, GET /avatar/* images, GET /c/* profile
// SSR, GET /sitemap-characters.xml, and the serveStatic catch-all) are
// DELIBERATELY NOT rows here. Their content types (image bytes, XML,
// server-rendered HTML for share unfurls) fall outside the five-class API
// content scheme this inventory classifies (the sitemap is XML, a type none of
// the five classes name), and they are not part of the REST API being
// re-architected: they stay on the top-level createServer ladder (the
// route-table migration only moves the four /api sub-dispatchers; the static
// ladder gets only the top-level security-headers wrapper), so they have
// no RouteDef, no error-model envelope, and no golden baseline here. The
// OPTIONS-204 preflight IS the one createServer-prefix row included, because it
// is the CORS contract guarding the whole /api surface.

import {
  BINARY,
  type ContentTypeClass,
  HTML,
  LEGACY_OKFALSE_405,
  PROBLEM_JSON,
} from './content_type_classification';

// Named dispatcher labels (no scattered inline literals). Each maps a row to the
// function (or the createServer prefix ladder) that owns its dispatch arm.
export const DISPATCH = {
  mainApi: 'main-handleApi',
  admin: 'admin',
  oauth: 'oauth',
  internal: 'internal',
  prefix: 'createServer-prefix',
} as const;
export type DispatcherLabel = (typeof DISPATCH)[keyof typeof DISPATCH];

// The HTTP methods the dispatchers branch on today. OPTIONS is the CORS
// preflight short-circuit; PUT exists solely for the map-save route
// (PUT /api/maps/:id, the v0.20.0 map editor); no route uses PATCH.
export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'] as const;
export type HttpMethod = (typeof HTTP_METHODS)[number];

// Auth scope a route requires before it does work. Named so the values are not
// scattered string literals:
//   public        no auth (anti-bot Origin / Turnstile gates are not auth)
//   bearer        any valid bearer, read/companion token accepted, no active
//                 check (bearerAccount / bearerReadAccount)
//   full          a full active session, read tokens rejected
//                 (bearerActiveAccount in main, fullSessionAccount in oauth)
//   admin         an admin account (isAdminAccount)
//   secret-deploy the x-woc-deploy-secret shared secret (RESTART_COUNTDOWN_SECRET)
//   secret-discord the x-woc-discord-secret shared secret (DISCORD_BOT_SECRET)
//   secret-daily-reward the x-woc-daily-reward-secret shared secret
//                 (WOC_DAILY_REWARD_SERVICE_SECRET). Unlike the other two secret
//                 scopes' feature-off 404, this gate FAILS CLOSED: an unset env
//                 AND a wrong header both answer 401 'not authenticated'
//                 (daily_rewards.ts internalAuthorized), and it never falls back
//                 to RESTART_COUNTDOWN_SECRET.
//   dev-gated     guarded by ALLOW_DEV_COMMANDS=1
export const AUTH_SCOPE = {
  public: 'public',
  bearer: 'bearer',
  full: 'full',
  admin: 'admin',
  secretDeploy: 'secret-deploy',
  secretDiscord: 'secret-discord',
  secretDailyReward: 'secret-daily-reward',
  devGated: 'dev-gated',
} as const;
export type AuthScope = (typeof AUTH_SCOPE)[keyof typeof AUTH_SCOPE];

// Expected object-ownership behavior for routes that resolve an object by id.
//   bola-404     owner-scoped: a non-owned/absent object answers 404 (no leak)
//   operator-404 admin operator route: an absent/forbidden id answers 404
//   public-read  intentionally public read-by-name (no ownership)
export const REQUIRE_OWNED = {
  bola404: 'bola-404',
  operator404: 'operator-404',
  publicRead: 'public-read',
} as const;
export type RequireOwnedExpected = (typeof REQUIRE_OWNED)[keyof typeof REQUIRE_OWNED];

export interface SurfaceRoute {
  readonly dispatcher: DispatcherLabel;
  readonly method: HttpMethod;
  // Route string. Exact for fixed routes; the human `:param` pattern for regex
  // routes (the canonical regex source lives in `match`).
  readonly path: string;
  // Symbol-name anchor: a handler fn, a `*Match` regex const, or an inline-arm
  // descriptor ("handleApi arm: /api/status").
  readonly handler: string;
  // One of the five content-type classes, or null for the no-body 204 preflight.
  readonly contentType: ContentTypeClass | null;
  readonly authScope: AuthScope;
  // The ratelimit symbol applied (in the dispatcher or in the delegate handler),
  // or null if the route is not rate limited.
  readonly limiter: string | null;
  readonly requireOwnedExpected: RequireOwnedExpected | null;
  // Distinguishes the query-param forks of /api/leaderboard (same path).
  readonly variant?: string;
  // True for the swag-claim handler that exists but has no dispatch arm.
  readonly unreachable?: true;
  // The exact regex literal for a `:param` route. Its `.source` equals the
  // regex body in the dispatcher source, which the freshness gate compares.
  readonly match?: RegExp;
}

export const SURFACE_INVENTORY: readonly SurfaceRoute[] = [
  // -------------------------------------------------------------------------
  // createServer prefix ladder (routeHttpRequest)
  // -------------------------------------------------------------------------
  // CORS preflight: 204, no body, for any /api, /admin/api, or public-cors path.
  // `path` is the wildcard sentinel '*' so the freshness + classification gates
  // (which key on concrete /api paths) skip it.
  {
    dispatcher: DISPATCH.prefix,
    method: 'OPTIONS',
    path: '*',
    handler: 'routeHttpRequest OPTIONS-204 arm',
    contentType: null,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },

  // -------------------------------------------------------------------------
  // main handleApi (/api/*)
  // -------------------------------------------------------------------------
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/native-attestation/challenge',
    handler: 'handleApi arm: /api/native-attestation/challenge',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  // Method-agnostic dispatch arm: POST records the heartbeat (200 { ok: true });
  // any non-POST falls into the same handler and answers 405 { ok: false }.
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/site-presence',
    handler: 'handleApi arm: /api/site-presence (handleSitePresenceHeartbeat)',
    contentType: LEGACY_OKFALSE_405,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/register',
    handler: 'handleApi arm: /api/register',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: 'rateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/login',
    handler: 'handleApi arm: /api/login',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: 'rateLimited',
    requireOwnedExpected: null,
  },
  // Desktop-login handoff (v0.19.0, server/desktop_login.ts): a logged-in browser
  // session mints a short-lived single-use IP-bound code (create), which the
  // Electron desktop shell trades for a session token (exchange,
  // unauthenticated by design: the 160-bit code IS the credential). Both share
  // the register/login per-IP rateLimited budget. Create requires a FULL active
  // session since the desktop-login create scope fix (bearerActiveAccount in the
  // arm; the earlier scope-blind accountForToken let a read token escalate to the
  // full session exchange mints: see the desktopLoginCreateFullScope deviation).
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/desktop-login/create',
    handler: 'handleApi arm: /api/desktop-login/create (issueDesktopLoginCode)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'rateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/desktop-login/exchange',
    handler: 'handleApi arm: /api/desktop-login/exchange (handleDesktopLoginExchange)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: 'rateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/me/characters',
    handler: 'handleApi arm: /api/me/characters',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.bearer,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/characters',
    handler: 'handleApi arm: /api/characters (GET)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/characters',
    handler: 'handleApi arm: /api/characters (POST)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/public/characters/:name/sheet',
    handler: 'publicSheetMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: 'publicReadRateLimited',
    requireOwnedExpected: REQUIRE_OWNED.publicRead,
    match: /^\/api\/public\/characters\/(.+)\/sheet$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/characters/:id/sheet',
    handler: 'ownerSheetMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.bearer,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.bola404,
    match: /^\/api\/characters\/(\d+)\/sheet$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/characters/:id/standing',
    handler: 'standingMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.bola404,
    match: /^\/api\/characters\/(\d+)\/standing$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/characters/:id/rename',
    handler: 'renameMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.bola404,
    match: /^\/api\/characters\/(\d+)\/rename$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/characters/:id/takeover',
    handler: 'takeoverMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.bola404,
    match: /^\/api\/characters\/(\d+)\/takeover$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'DELETE',
    path: '/api/characters/:id',
    handler: 'delMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.bola404,
    match: /^\/api\/characters\/(\d+)$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/realms',
    handler: 'handleApi arm: /api/realms',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.bearer,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/search',
    handler: 'handleApi arm: /api/search',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.bearer,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/reports',
    handler: 'handleApi arm: /api/reports',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/bug-reports',
    handler: 'handleApi arm: /api/bug-reports',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  // Dispatch arm requires POST; handlePerfReport's non-POST 405 { ok: false }
  // branch is unreachable through the dispatcher. Classified by its ok-shape.
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/perf-report',
    handler: 'handleApi arm: /api/perf-report (handlePerfReport)',
    contentType: LEGACY_OKFALSE_405,
    authScope: AUTH_SCOPE.public,
    limiter: 'rateLimitedPerfReport',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/project-stats',
    handler: 'handleApi arm: /api/project-stats',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/status',
    handler: 'handleApi arm: /api/status',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/perf',
    handler: 'handleApi arm: /api/perf',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.devGated,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/arena/leaderboard',
    handler: 'handleApi arm: /api/arena/leaderboard',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  // /api/leaderboard forks on query params, same path. Each fork is its own row.
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/leaderboard',
    handler: 'handleApi arm: /api/leaderboard',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
    variant: 'players-realm-paged',
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/leaderboard',
    handler: 'handleApi arm: /api/leaderboard',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
    variant: 'players-global-paged',
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/leaderboard',
    handler: 'handleApi arm: /api/leaderboard',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
    variant: 'guilds',
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/leaderboard',
    handler: 'handleApi arm: /api/leaderboard',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
    variant: 'legacy-limit',
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/releases',
    handler: 'handleApi arm: /api/releases',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/account',
    handler: 'handleApi arm: /api/account',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/password',
    handler: 'handleApi arm: /api/account/password',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/logout',
    handler: 'handleApi arm: /api/account/logout',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/email',
    handler: 'handleApi arm: /api/account/email',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/deactivate',
    handler: 'handleApi arm: /api/account/deactivate',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  // Method-agnostic arm; POST mints, GET lists, DELETE revokes a companion token.
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/companion-token',
    handler: 'handleApi arm: /api/account/companion-token (POST)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/account/companion-token',
    handler: 'handleApi arm: /api/account/companion-token (GET)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'DELETE',
    path: '/api/account/companion-token',
    handler: 'handleApi arm: /api/account/companion-token (DELETE)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/email/change',
    handler: 'handleApi arm: /api/account/email/change (handleAccountEmailChange)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  // v0.20.0 mandatory-email backfill: fills the recovery address on an account
  // that has none yet; once one exists it 409s to the verified change flow.
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/email/set-initial',
    handler: 'handleApi arm: /api/account/email/set-initial (handleAccountSetInitialEmail)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  // Unauthenticated: the link token in the query string is the authorization.
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/account/email/verify',
    handler: 'handleApi arm: /api/account/email/verify',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/export',
    handler: 'handleApi arm: /api/account/export',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/marketing',
    handler: 'handleApi arm: /api/account/marketing',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/2fa/setup',
    handler: 'handleApi arm: /api/account/2fa/setup',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/2fa/enable',
    handler: 'handleApi arm: /api/account/2fa/enable',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/account/2fa/disable',
    handler: 'handleApi arm: /api/account/2fa/disable',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/email/unsubscribe',
    handler: 'handleApi arm: /api/email/unsubscribe',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/wallet/link/challenge',
    handler: 'handleApi arm: /api/wallet/link/challenge',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/wallet/link',
    handler: 'handleApi arm: /api/wallet/link (POST)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'DELETE',
    path: '/api/wallet/link',
    handler: 'handleApi arm: /api/wallet/link (DELETE)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/wallet',
    handler: 'handleApi arm: /api/wallet',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  // mode=login is unauthenticated; mode=link requires a full session.
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/auth/discord/start',
    handler: 'handleApi arm: /api/auth/discord/start (handleDiscordStart)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: 'discordRateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/auth/discord/callback',
    handler: 'handleApi arm: /api/auth/discord/callback (handleDiscordCallback)',
    contentType: HTML,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/auth/discord/login/new',
    handler: 'handleApi arm: /api/auth/discord/login/new (handleDiscordLoginNew)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: 'discordRateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/auth/discord/login/link',
    handler: 'handleApi arm: /api/auth/discord/login/link (handleDiscordLoginLink)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: 'discordRateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/discord',
    handler: 'handleApi arm: /api/discord (GET, handleDiscordStatus)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'discordRateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'DELETE',
    path: '/api/discord',
    handler: 'handleApi arm: /api/discord (DELETE, handleDiscordUnlink)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'discordRateLimited',
    requireOwnedExpected: null,
  },
  // GitHub OAuth link (developer badge), mirroring the Discord link flow. Start
  // is link-only (it resolves the caller's account first, so it needs a full
  // session, unlike the Discord login-or-link start); the callback carries no
  // bearer and answers with an HTML page (a github.com redirect).
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/auth/github/start',
    handler: 'handleApi arm: /api/auth/github/start (handleGitHubStart)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'githubRateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/auth/github/callback',
    handler: 'handleApi arm: /api/auth/github/callback (handleGitHubCallback)',
    contentType: HTML,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/github',
    handler: 'handleApi arm: /api/github (GET, handleGitHubStatus)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'githubRateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'DELETE',
    path: '/api/github',
    handler: 'handleApi arm: /api/github (DELETE, handleGitHubUnlink)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'githubRateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/woc/balance',
    handler: 'handleApi arm: /api/woc/balance',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: 'wocBalanceRateLimited',
    requireOwnedExpected: null,
  },
  // Daily-rewards player family (v0.19.0, server/daily_rewards.ts): served by
  // the handleDailyRewardApi sub-dispatcher behind the main.ts PREFIX arm
  // `url.startsWith('/api/daily-rewards')`, which runs bearerActiveAccount
  // (full active session, read tokens 403) BEFORE delegating, method- and
  // subpath-agnostic. The prefix has NO trailing-slash boundary, so a no-slash
  // sibling like '/api/daily-rewardsfoo' also enters the family (auth first,
  // then the in-family 404) instead of falling through the ladder. No rate
  // limiter on any of the three (spin relies on the one-spin-per-day 409 guard
  // only). In-family fallthrough (wrong method or unknown subpath, after auth)
  // is 404 { error: 'unknown endpoint' }.
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/daily-rewards',
    handler: 'handleDailyRewardApi arm: /api/daily-rewards (status)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  // v0.20.0 pagination: the standalone paginated leaderboard read (page/pageSize
  // query params, lenient Number(...) || default decode like history's limit).
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/daily-rewards/leaderboard',
    handler: 'handleDailyRewardApi arm: /api/daily-rewards/leaderboard',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/daily-rewards/spin',
    handler: 'handleDailyRewardApi arm: /api/daily-rewards/spin',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/daily-rewards/history',
    handler: 'handleDailyRewardApi arm: /api/daily-rewards/history',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/card',
    handler: 'handleApi arm: /api/card (handleCardUpload)',
    contentType: BINARY,
    authScope: AUTH_SCOPE.full,
    limiter: 'cardUploadRateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/referrals',
    handler: 'handleApi arm: /api/referrals',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  // v0.20.0 release merge: the map editor surface. Custom maps (owner CRUD +
  // public browse/read, server/maps_routes.ts cores) and uploaded GLB assets
  // (binary upload + public content-addressed byte read,
  // server/user_assets_routes.ts cores). Migrated in-merge: the RouteDefs mount
  // the same guards these ladder arms apply.
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/maps',
    handler: 'handleApi arm: /api/maps (mapsListMineCore)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.bearer,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/maps',
    handler: 'handleApi arm: /api/maps (mapsCreateCore)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'mapMutationRateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/maps/public',
    handler: 'handleApi arm: /api/maps/public (mapsPublicListCore)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: 'publicReadRateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/maps/:id',
    handler: 'mapIdMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: 'publicReadRateLimited',
    requireOwnedExpected: REQUIRE_OWNED.publicRead,
    match: /^\/api\/maps\/(\d+)$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'PUT',
    path: '/api/maps/:id',
    handler: 'mapIdMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'mapMutationRateLimited',
    requireOwnedExpected: REQUIRE_OWNED.bola404,
    match: /^\/api\/maps\/(\d+)$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'DELETE',
    path: '/api/maps/:id',
    handler: 'mapIdMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'mapMutationRateLimited',
    requireOwnedExpected: REQUIRE_OWNED.bola404,
    match: /^\/api\/maps\/(\d+)$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/maps/:id/fork',
    handler: 'mapForkMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'mapMutationRateLimited',
    requireOwnedExpected: REQUIRE_OWNED.publicRead,
    match: /^\/api\/maps\/(\d+)\/fork$/,
  },
  // The (publish|unpublish) regex arm registers as two literal-suffix
  // RouteDefs, so it carries two rows sharing one match source.
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/maps/:id/publish',
    handler: 'mapPublishMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'mapMutationRateLimited',
    requireOwnedExpected: REQUIRE_OWNED.bola404,
    match: /^\/api\/maps\/(\d+)\/(publish|unpublish)$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/maps/:id/unpublish',
    handler: 'mapPublishMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'mapMutationRateLimited',
    requireOwnedExpected: REQUIRE_OWNED.bola404,
    match: /^\/api\/maps\/(\d+)\/(publish|unpublish)$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/assets',
    handler: 'handleApi arm: /api/assets (assetUploadCore)',
    contentType: BINARY,
    authScope: AUTH_SCOPE.full,
    limiter: 'assetUploadRateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/assets/mine',
    handler: 'handleApi arm: /api/assets/mine (assetsListMineCore)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.bearer,
    limiter: null,
    requireOwnedExpected: null,
  },
  // The content-addressed byte read. The registered param is ':file' (one
  // segment, `<sha256>.glb`; the handler validates the shape against the same
  // regex this row's match carries).
  {
    dispatcher: DISPATCH.mainApi,
    method: 'GET',
    path: '/api/assets/:file',
    handler: 'assetGlbMatch',
    contentType: BINARY,
    authScope: AUTH_SCOPE.public,
    limiter: 'publicReadRateLimited',
    requireOwnedExpected: REQUIRE_OWNED.publicRead,
    match: /^\/api\/assets\/([a-f0-9]{64})\.glb$/,
  },
  {
    dispatcher: DISPATCH.mainApi,
    method: 'DELETE',
    path: '/api/assets/:id',
    handler: 'assetIdMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.bola404,
    match: /^\/api\/assets\/(\d+)$/,
  },

  // Orphan: the handler is exported but no dispatcher routes to it. Excluded
  // from the freshness gate's source comparison (it has no dispatch arm).
  {
    dispatcher: DISPATCH.mainApi,
    method: 'POST',
    path: '/api/discord/swag/claim',
    handler: 'handleSwagClaim',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: 'discordRateLimited',
    requireOwnedExpected: null,
    unreachable: true,
  },

  // -------------------------------------------------------------------------
  // admin handleAdminApi (/admin/api/*)
  // -------------------------------------------------------------------------
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/login',
    handler: 'handleAdminApi arm: /admin/api/login',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: 'rateLimited',
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/moderation/accounts/:id/(suspend|unsuspend|ban|unban)',
    handler: 'actionMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/moderation\/accounts\/(\d+)\/(suspend|unsuspend|ban|unban)$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/moderation/accounts/:id/reactivate',
    handler: 'reactivateMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/moderation\/accounts\/(\d+)\/reactivate$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/moderation/accounts/:id/chat-mute',
    handler: 'chatMuteMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/moderation\/accounts\/(\d+)\/chat-mute$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/moderation/reports/:id/ignore',
    handler: 'ignoreMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/moderation\/reports\/(\d+)\/ignore$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/moderation/characters/:id/force-rename',
    handler: 'forceRenameMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/moderation\/characters\/(\d+)\/force-rename$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/moderation/accounts/:id/lift-mute',
    handler: 'liftMuteMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/moderation\/accounts\/(\d+)\/lift-mute$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/moderation/accounts/:id/note',
    handler: 'noteMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/moderation\/accounts\/(\d+)\/note$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/moderation/accounts/:id/reset-strikes',
    handler: 'resetStrikesMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/moderation\/accounts\/(\d+)\/reset-strikes$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/chat-filter/words',
    handler: 'handleAdminApi arm: /admin/api/chat-filter/words',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/chat-filter/words/:id/delete',
    handler: 'wordDeleteMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/chat-filter\/words\/(\d+)\/delete$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/chat-filter/config',
    handler: 'handleAdminApi arm: /admin/api/chat-filter/config',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/blocked-ips',
    handler: 'handleAdminApi arm: /admin/api/blocked-ips (POST)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/blocked-ips',
    handler: 'handleAdminApi arm: /admin/api/blocked-ips (GET)',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/blocked-ips/delete',
    handler: 'handleAdminApi arm: /admin/api/blocked-ips/delete',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/chat-filter',
    handler: 'handleAdminApi arm: /admin/api/chat-filter',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/overview',
    handler: 'handleAdminApi arm: /admin/api/overview',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/online',
    handler: 'handleAdminApi arm: /admin/api/online',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/suspicious-players',
    handler: 'handleAdminApi arm: /admin/api/suspicious-players',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  // v0.20.0: bot-detector calibration histograms for the admin dashboard.
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/detection-calibration',
    handler: 'handleAdminApi arm: /admin/api/detection-calibration',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  // v0.22.0 release merge: staff identity + fine-grained role management
  // (accounts.admin_roles; the central ADMIN_ROUTE_PERMISSIONS gate authorizes
  // every authed admin route, so authScope stays the shared admin gate).
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/me',
    handler: 'handleAdminApi arm: /admin/api/me',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/staff',
    handler: 'handleAdminApi arm: /admin/api/staff',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/staff/history',
    handler: 'handleAdminApi arm: /admin/api/staff/history',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/staff/roles',
    handler: 'handleAdminApi arm: /admin/api/staff/roles',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  // v0.22.0 release merge: provider usage split out of the overview onto its own
  // ops_usage.read route.
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/provider-usage',
    handler: 'handleAdminApi arm: /admin/api/provider-usage',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  // v0.22.0 release merge: bot-detector runtime config (read + validate-apply-
  // persist write + append-only audit history).
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/antibot-config',
    handler: 'handleAdminApi arm: /admin/api/antibot-config',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/antibot-config',
    handler: 'handleAdminApi arm: POST /admin/api/antibot-config',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/antibot-config/history',
    handler: 'handleAdminApi arm: /admin/api/antibot-config/history',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  // v0.20.0 release merge: map editor moderation (lists + forced unpublish +
  // upload block/unblock). The (block|unblock) regex arm registers as two
  // literal-suffix RouteDefs, so it carries two rows sharing one match source.
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/maps',
    handler: 'handleAdminApi arm: /admin/api/maps',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/user-assets',
    handler: 'handleAdminApi arm: /admin/api/user-assets',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/maps/:id/unpublish',
    handler: 'mapUnpublishMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/maps\/(\d+)\/unpublish$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/user-assets/:id/block',
    handler: 'assetBlockMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/user-assets\/(\d+)\/(block|unblock)$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/user-assets/:id/unblock',
    handler: 'assetBlockMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/user-assets\/(\d+)\/(block|unblock)$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/online-history',
    handler: 'handleAdminApi arm: /admin/api/online-history',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/activity',
    handler: 'handleAdminApi arm: /admin/api/activity',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/perf/summary',
    handler: 'handleAdminApi arm: /admin/api/perf/summary',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/perf/raw',
    handler: 'handleAdminApi arm: /admin/api/perf/raw',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/perf/tick',
    handler: 'handleAdminApi arm: /admin/api/perf/tick',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'POST',
    path: '/admin/api/perf/tick/capture',
    handler: 'handleAdminApi arm: /admin/api/perf/tick/capture',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/accounts',
    handler: 'handleAdminApi arm: /admin/api/accounts',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/shared-ips',
    handler: 'handleAdminApi arm: /admin/api/shared-ips',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/ip-associations',
    handler: 'handleAdminApi arm: /admin/api/ip-associations',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/moderation/queue',
    handler: 'handleAdminApi arm: /admin/api/moderation/queue',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/bug-reports',
    handler: 'handleAdminApi arm: /admin/api/bug-reports',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/bug-reports/:id/screenshot',
    handler: 'bugScreenshotMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/bug-reports\/(\d+)\/screenshot$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/moderation/accounts/:id',
    handler: 'moderationAccountMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/moderation\/accounts\/(\d+)$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/accounts/:id',
    handler: 'detailMatch',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: REQUIRE_OWNED.operator404,
    match: /^\/admin\/api\/accounts\/(\d+)$/,
  },
  {
    dispatcher: DISPATCH.admin,
    method: 'GET',
    path: '/admin/api/characters',
    handler: 'handleAdminApi arm: /admin/api/characters',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.admin,
    limiter: null,
    requireOwnedExpected: null,
  },

  // -------------------------------------------------------------------------
  // oauth handleOAuth (/oauth/*)
  // -------------------------------------------------------------------------
  {
    dispatcher: DISPATCH.oauth,
    method: 'GET',
    path: '/oauth/authorize',
    handler: 'renderAuthorize',
    contentType: HTML,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  // Consent decision returns json { redirect } (a client-side redirect URL, not
  // a 302), so its content class is PROBLEM_JSON, not REDIRECT.
  {
    dispatcher: DISPATCH.oauth,
    method: 'POST',
    path: '/oauth/authorize',
    handler: 'approveAuthorize',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.oauth,
    method: 'POST',
    path: '/oauth/token',
    handler: 'tokenEndpoint',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.oauth,
    method: 'POST',
    path: '/oauth/revoke',
    handler: 'revokeEndpoint',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.oauth,
    method: 'POST',
    path: '/oauth/device_authorization',
    handler: 'deviceAuthorization',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.oauth,
    method: 'GET',
    path: '/oauth/device',
    handler: 'renderDevicePage',
    contentType: HTML,
    authScope: AUTH_SCOPE.public,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.oauth,
    method: 'POST',
    path: '/oauth/device',
    handler: 'approveDevice',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.full,
    limiter: null,
    requireOwnedExpected: null,
  },

  // -------------------------------------------------------------------------
  // internal handleInternalApi (/internal/*)
  // -------------------------------------------------------------------------
  {
    dispatcher: DISPATCH.internal,
    method: 'POST',
    path: '/internal/restart-countdown',
    handler: 'handleInternalApi arm: /internal/restart-countdown',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDeploy,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'GET',
    path: '/internal/discord/flex',
    handler: 'handleDiscordInternal arm: /internal/discord/flex',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDiscord,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'GET',
    path: '/internal/discord/roles',
    handler: 'handleDiscordInternal arm: /internal/discord/roles',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDiscord,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'POST',
    path: '/internal/discord/presence',
    handler: 'handleDiscordInternal arm: /internal/discord/presence',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDiscord,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'POST',
    path: '/internal/discord/grant',
    handler: 'handleDiscordInternal arm: /internal/discord/grant',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDiscord,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'POST',
    path: '/internal/discord/member',
    handler: 'handleDiscordInternal arm: /internal/discord/member',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDiscord,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'GET',
    path: '/internal/discord/relay',
    handler: 'handleDiscordInternal arm: /internal/discord/relay',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDiscord,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'GET',
    path: '/internal/discord/activity',
    handler: 'handleDiscordInternal arm: /internal/discord/activity',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDiscord,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'POST',
    path: '/internal/discord/members-meta',
    handler: 'handleDiscordInternal arm: /internal/discord/members-meta',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDiscord,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'GET',
    path: '/internal/discord/daily-rewards-winners',
    handler: 'handleDiscordInternal arm: /internal/discord/daily-rewards-winners',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDiscord,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'POST',
    path: '/internal/discord/daily-rewards-winners/mark',
    handler: 'handleDiscordInternal arm: /internal/discord/daily-rewards-winners/mark',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDiscord,
    limiter: null,
    requireOwnedExpected: null,
  },
  // Daily-rewards ops family (v0.19.0, server/daily_rewards.ts): served by the
  // handleDailyRewardInternalApi sub-dispatcher, which the /internal composite
  // delegate tries FIRST (before handleInternalApi, whose terminal 404 would
  // otherwise swallow the family: the ordering is load-bearing and parity-pinned).
  // NEVER part of handleInternalApi; the family is ALSO on the RouteDef table
  // (fail-closed secret gate + the same sub-dispatcher core), with
  // the composite delegate kept as the rollback arm. The whole `/internal/daily-rewards/` prefix
  // is secret-gated BEFORE path/method resolution, fail-closed (see AUTH_SCOPE),
  // and answers in the admin { success, data, error } envelope on every branch.
  {
    dispatcher: DISPATCH.internal,
    method: 'POST',
    path: '/internal/daily-rewards/pending-payouts',
    handler: 'handleDailyRewardInternalApi arm: /internal/daily-rewards/pending-payouts',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDailyReward,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'POST',
    path: '/internal/daily-rewards/payout-history',
    handler: 'handleDailyRewardInternalApi arm: /internal/daily-rewards/payout-history',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDailyReward,
    limiter: null,
    requireOwnedExpected: null,
  },
  // v0.20.0 pagination: the ops-side paginated leaderboard read (day/page/pageSize
  // query params, lenient decode; defaults to the current reward day).
  {
    dispatcher: DISPATCH.internal,
    method: 'POST',
    path: '/internal/daily-rewards/leaderboard',
    handler: 'handleDailyRewardInternalApi arm: /internal/daily-rewards/leaderboard',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDailyReward,
    limiter: null,
    requireOwnedExpected: null,
  },
  {
    dispatcher: DISPATCH.internal,
    method: 'POST',
    path: '/internal/daily-rewards/mark-payout',
    handler: 'handleDailyRewardInternalApi arm: /internal/daily-rewards/mark-payout',
    contentType: PROBLEM_JSON,
    authScope: AUTH_SCOPE.secretDailyReward,
    limiter: null,
    requireOwnedExpected: null,
  },
];

// The four API prefixes every dispatched route descriptor begins with. The
// freshness gate uses these both to scope its source scan and to pick the
// inventory rows that participate in the source comparison.
export const DISPATCHED_PREFIXES = ['/api/', '/admin/api/', '/internal/', '/oauth/'] as const;
