// GENERATED by scripts/wiki/build_content.mjs from src/sim/content. Do not edit by hand.
// Regenerate with `npm run wiki:content`; tests/guide.test.ts checks it stays fresh.
// Spec names and ability names are the English sim source (proper nouns); all other
// Guide copy is localized via guide.* t() keys, and rich spec/mastery prose resolves
// live through src/ui/talent_i18n.ts. No balance numbers or instanced spoilers here.

export type GuideRole = 'tank' | 'healer' | 'dps';
export type GuideResource = 'rage' | 'mana' | 'energy';

export interface GuideAbilityRef { id: string; name: string; }
export interface GuideClassSpec { id: string; name: string; role: GuideRole; signature: string; }

// Interactive 3D model data, mirrored from the renderer's VisualDef manifest. The Guide's
// standalone viewer builds the model from one GLB on demand; entities reference a model by
// visual key into GUIDE_MODELS and carry their own tint color.
export interface GuideModelAttach { url: string; bone: string; position?: [number, number, number]; rotationY?: number; gripRef?: string; }
export interface GuideModelWeaponFix { node: string; rotX?: number; rotY?: number; rotZ?: number; }
export interface GuideModelSpec {
  url: string;
  idle: string | null;
  height: number;
  yaw?: number;
  hover?: number;
  show?: string[];
  attach?: GuideModelAttach[];
  weaponFix?: GuideModelWeaponFix[];
  tintStrength?: number;
}

export interface GuideClassInfo {
  id: string;
  color: string;
  resource: GuideResource;
  roles: GuideRole[];
  specs: GuideClassSpec[];
  signatureAbilities: GuideAbilityRef[];
  abilities: GuideAbilityRef[];
  model: string;
  tint?: string;
  /** Pre-rendered transparent still (public/guide-stills/), the default poster. */
  still?: string;
}

export interface GuideZoneInfo {
  id: string;
  name: string;
  min: number;
  max: number;
  biome: string;
  hub: string;
  pois: string[];
  welcome: string;
  /** Bestiary families with at least one camp inside this zone, in family order. */
  families: string[];
}

export interface GuideDungeon {
  id: string;
  isRaid: boolean;
  suggestedPlayers: number;
  min: number | null;
  max: number | null;
  name?: string;
}

export interface GuideWarlockPet { id: string; name: string; model: string; tint?: string; still?: string; }

// Druid shapeshift forms. Unnamed on purpose: the gallery labels them with guide.models.form*
// keys so the names localize like the rest of the picker chrome.
export interface GuideDruidForm { id: string; model: string; tint?: string; still?: string; }

export interface GuideCreature { name: string; min: number; max: number; rare: boolean; templateId: string; model: string; tint?: string; still?: string; }
export interface GuideFamily { family: string; creatures: GuideCreature[]; }

export interface GuideDelveKeeper { name: string; title: string; }
export interface GuideDelveCompanion { name: string; role: string; }
export interface GuideDelve {
  id: string;
  name: string;
  theme: string;
  minLevel: number;
  suggestedPlayers: number;
  keeper?: GuideDelveKeeper;
  companion?: GuideDelveCompanion;
  tiers: string[];
  affixes: string[];
}

// A single public deed. Names and reward title text are the English sim source (proper
// nouns), baked like creature and POI names. No criteria beyond this reaches the wiki: the
// trigger and the player-facing desc are deliberately omitted (see the generator note), and
// hidden deeds are filtered out entirely, so this list is safe to publish in full.
export interface GuideDeed {
  id: string;
  name: string;
  category: string;
  renown: number;
  feat: boolean;
  /** Cosmetic title text (English proper noun), when the deed grants one. */
  rewardTitle?: string;
  /** True when the deed grants a cosmetic nameplate border. */
  rewardBorder?: true;
  /** Painted crest URL under /ui/deeds, present only when committed art backs this deed. */
  crest?: string;
}

export const GUIDE_CLASSES: GuideClassInfo[] = [
  {
    "id": "warrior",
    "color": "#c79c6e",
    "resource": "rage",
    "roles": [
      "tank",
      "dps"
    ],
    "specs": [
      {
        "id": "arms",
        "name": "Battlecraft",
        "role": "dps",
        "signature": "mortal_strike"
      },
      {
        "id": "fury",
        "name": "Bloodrush",
        "role": "dps",
        "signature": "bloodthirst"
      },
      {
        "id": "prot",
        "name": "Ironguard",
        "role": "tank",
        "signature": "shield_slam"
      }
    ],
    "signatureAbilities": [
      {
        "id": "heroic_strike",
        "name": "Reaver Strike"
      },
      {
        "id": "battle_shout",
        "name": "Iron Bellow"
      },
      {
        "id": "commanding_shout",
        "name": "Bolstering Cry"
      },
      {
        "id": "charge",
        "name": "Onrush"
      },
      {
        "id": "rend",
        "name": "Deep Gash"
      },
      {
        "id": "thunder_clap",
        "name": "Quaking Blow"
      }
    ],
    "abilities": [
      {
        "id": "heroic_strike",
        "name": "Reaver Strike"
      },
      {
        "id": "battle_shout",
        "name": "Iron Bellow"
      },
      {
        "id": "commanding_shout",
        "name": "Bolstering Cry"
      },
      {
        "id": "charge",
        "name": "Onrush"
      },
      {
        "id": "rend",
        "name": "Deep Gash"
      },
      {
        "id": "thunder_clap",
        "name": "Quaking Blow"
      },
      {
        "id": "hamstring",
        "name": "Hobbling Cut"
      },
      {
        "id": "bloodrage",
        "name": "Blood Toll"
      },
      {
        "id": "overpower",
        "name": "Redhand"
      },
      {
        "id": "execute",
        "name": "Early Grave"
      },
      {
        "id": "slam",
        "name": "Brute Swing"
      },
      {
        "id": "cleave",
        "name": "Reaping Arc"
      },
      {
        "id": "defensive_stance",
        "name": "Guarded Stance"
      },
      {
        "id": "demoralizing_shout",
        "name": "Direhowl"
      },
      {
        "id": "sunder_armor",
        "name": "Armor Shear"
      },
      {
        "id": "taunt",
        "name": "Goad"
      }
    ],
    "model": "player_warrior",
    "still": "/guide-stills/player_warrior.webp"
  },
  {
    "id": "paladin",
    "color": "#f58cba",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "holy",
        "name": "Sacrament",
        "role": "healer",
        "signature": "flash_of_light"
      },
      {
        "id": "protection",
        "name": "Vigil",
        "role": "tank",
        "signature": "righteous_fury"
      },
      {
        "id": "retribution",
        "name": "Requital",
        "role": "dps",
        "signature": "judgement"
      }
    ],
    "signatureAbilities": [
      {
        "id": "seal_of_righteousness",
        "name": "Oathbrand"
      },
      {
        "id": "holy_light",
        "name": "Mending Light"
      },
      {
        "id": "devotion_aura",
        "name": "Steadfast Aura"
      },
      {
        "id": "judgement",
        "name": "Verdict"
      },
      {
        "id": "blessing_of_might",
        "name": "Oath of Iron"
      },
      {
        "id": "divine_protection",
        "name": "Ward of Faith"
      }
    ],
    "abilities": [
      {
        "id": "seal_of_righteousness",
        "name": "Oathbrand"
      },
      {
        "id": "holy_light",
        "name": "Mending Light"
      },
      {
        "id": "devotion_aura",
        "name": "Steadfast Aura"
      },
      {
        "id": "judgement",
        "name": "Verdict"
      },
      {
        "id": "blessing_of_might",
        "name": "Oath of Iron"
      },
      {
        "id": "divine_protection",
        "name": "Ward of Faith"
      },
      {
        "id": "hammer_of_justice",
        "name": "Sundering Gavel"
      },
      {
        "id": "lay_on_hands",
        "name": "Last Rite"
      },
      {
        "id": "flash_of_light",
        "name": "Lightmend"
      },
      {
        "id": "exorcism",
        "name": "Rite of Expulsion"
      },
      {
        "id": "consecration",
        "name": "Holy Ground"
      },
      {
        "id": "righteous_fury",
        "name": "Burning Oath"
      },
      {
        "id": "retribution_aura",
        "name": "Requital Aura"
      }
    ],
    "model": "player_paladin",
    "still": "/guide-stills/player_paladin.webp"
  },
  {
    "id": "hunter",
    "color": "#abd473",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "beast_mastery",
        "name": "Packlord",
        "role": "dps",
        "signature": "tame_beast"
      },
      {
        "id": "marksmanship",
        "name": "Coldsight",
        "role": "dps",
        "signature": "aimed_shot"
      },
      {
        "id": "survival",
        "name": "Fieldcraft",
        "role": "dps",
        "signature": "wing_clip"
      }
    ],
    "signatureAbilities": [
      {
        "id": "raptor_strike",
        "name": "Gutting Strike"
      },
      {
        "id": "aspect_of_the_hawk",
        "name": "Harrier's Guise"
      },
      {
        "id": "serpent_sting",
        "name": "Venom Barb"
      },
      {
        "id": "arcane_shot",
        "name": "Fell Shot"
      },
      {
        "id": "concussive_shot",
        "name": "Rattling Shot"
      },
      {
        "id": "mongoose_bite",
        "name": "Counterfang"
      }
    ],
    "abilities": [
      {
        "id": "raptor_strike",
        "name": "Gutting Strike"
      },
      {
        "id": "aspect_of_the_hawk",
        "name": "Harrier's Guise"
      },
      {
        "id": "serpent_sting",
        "name": "Venom Barb"
      },
      {
        "id": "arcane_shot",
        "name": "Fell Shot"
      },
      {
        "id": "concussive_shot",
        "name": "Rattling Shot"
      },
      {
        "id": "mongoose_bite",
        "name": "Counterfang"
      },
      {
        "id": "wing_clip",
        "name": "Fettering Slash"
      },
      {
        "id": "tame_beast",
        "name": "Wildbond"
      },
      {
        "id": "dismiss_pet",
        "name": "Release Companion"
      },
      {
        "id": "revive_pet",
        "name": "Revive Pet"
      },
      {
        "id": "aspect_of_the_monkey",
        "name": "Marten's Guise"
      },
      {
        "id": "aspect_of_the_cheetah",
        "name": "Courser's Guise"
      },
      {
        "id": "aimed_shot",
        "name": "Long Draw"
      },
      {
        "id": "rapid_fire",
        "name": "Fevered Draw"
      },
      {
        "id": "volley",
        "name": "Volley"
      }
    ],
    "model": "player_hunter",
    "still": "/guide-stills/player_hunter.webp"
  },
  {
    "id": "rogue",
    "color": "#fff569",
    "resource": "energy",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "assassination",
        "name": "Knifework",
        "role": "dps",
        "signature": "eviscerate"
      },
      {
        "id": "combat",
        "name": "Thuggery",
        "role": "dps",
        "signature": "adrenaline_rush"
      },
      {
        "id": "subtlety",
        "name": "Skulduggery",
        "role": "dps",
        "signature": "ambush"
      }
    ],
    "signatureAbilities": [
      {
        "id": "sinister_strike",
        "name": "Wicked Slash"
      },
      {
        "id": "eviscerate",
        "name": "Dirt Nap"
      },
      {
        "id": "garrote",
        "name": "Throat Wire"
      },
      {
        "id": "backstab",
        "name": "Craven Thrust"
      },
      {
        "id": "gouge",
        "name": "Eye Jab"
      },
      {
        "id": "cheap_shot",
        "name": "Gut Punch"
      }
    ],
    "abilities": [
      {
        "id": "sinister_strike",
        "name": "Wicked Slash"
      },
      {
        "id": "eviscerate",
        "name": "Dirt Nap"
      },
      {
        "id": "garrote",
        "name": "Throat Wire"
      },
      {
        "id": "backstab",
        "name": "Craven Thrust"
      },
      {
        "id": "gouge",
        "name": "Eye Jab"
      },
      {
        "id": "cheap_shot",
        "name": "Gut Punch"
      },
      {
        "id": "evasion",
        "name": "Ghostfoot"
      },
      {
        "id": "sap",
        "name": "Sap"
      },
      {
        "id": "slice_and_dice",
        "name": "Cutthroat Tempo"
      },
      {
        "id": "sprint",
        "name": "Swift Heels"
      },
      {
        "id": "crippling_poison",
        "name": "Leaden Venom"
      },
      {
        "id": "kidney_shot",
        "name": "Low Blow"
      },
      {
        "id": "expose_armor",
        "name": "Armor Breach"
      },
      {
        "id": "ambush",
        "name": "Lurker's Strike"
      },
      {
        "id": "rupture",
        "name": "Bleed Out"
      },
      {
        "id": "vanish",
        "name": "Smokestep"
      },
      {
        "id": "instant_poison",
        "name": "Adder's Bite"
      },
      {
        "id": "adrenaline_rush",
        "name": "Quickened Blood"
      },
      {
        "id": "deadly_poison",
        "name": "Festering Venom"
      },
      {
        "id": "blind",
        "name": "Dirt Toss"
      },
      {
        "id": "stealth",
        "name": "Duskveil"
      }
    ],
    "model": "player_rogue",
    "still": "/guide-stills/player_rogue.webp"
  },
  {
    "id": "priest",
    "color": "#fffff0",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "discipline",
        "name": "Doctrine",
        "role": "healer",
        "signature": "power_word_shield"
      },
      {
        "id": "holy",
        "name": "Benison",
        "role": "healer",
        "signature": "flash_heal"
      },
      {
        "id": "shadow",
        "name": "Vespers",
        "role": "dps",
        "signature": "mind_flay"
      }
    ],
    "signatureAbilities": [
      {
        "id": "smite",
        "name": "Smite"
      },
      {
        "id": "lesser_heal",
        "name": "Whispered Prayer"
      },
      {
        "id": "power_word_fortitude",
        "name": "Litany of Resolve"
      },
      {
        "id": "shadow_word_pain",
        "name": "Dirge of Decay"
      },
      {
        "id": "power_word_shield",
        "name": "Psalm of Warding"
      },
      {
        "id": "renew",
        "name": "Lingering Grace"
      }
    ],
    "abilities": [
      {
        "id": "smite",
        "name": "Smite"
      },
      {
        "id": "lesser_heal",
        "name": "Whispered Prayer"
      },
      {
        "id": "power_word_fortitude",
        "name": "Litany of Resolve"
      },
      {
        "id": "shadow_word_pain",
        "name": "Dirge of Decay"
      },
      {
        "id": "power_word_shield",
        "name": "Psalm of Warding"
      },
      {
        "id": "renew",
        "name": "Lingering Grace"
      },
      {
        "id": "mind_blast",
        "name": "Mindfracture"
      },
      {
        "id": "heal",
        "name": "Solemn Prayer"
      },
      {
        "id": "mind_flay",
        "name": "Litany of Woe"
      },
      {
        "id": "flash_heal",
        "name": "Urgent Prayer"
      }
    ],
    "model": "player_priest",
    "tint": "#f0e9d6",
    "still": "/guide-stills/player_priest__f0e9d6.webp"
  },
  {
    "id": "shaman",
    "color": "#0070de",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "elemental",
        "name": "Thundercall",
        "role": "dps",
        "signature": "lightning_bolt"
      },
      {
        "id": "enhancement",
        "name": "Warspirit",
        "role": "dps",
        "signature": "stormstrike"
      },
      {
        "id": "restoration",
        "name": "Spiritmend",
        "role": "healer",
        "signature": "healing_wave"
      }
    ],
    "signatureAbilities": [
      {
        "id": "lightning_bolt",
        "name": "Arc Bolt"
      },
      {
        "id": "rockbiter_weapon",
        "name": "Stonebound Weapon"
      },
      {
        "id": "healing_wave",
        "name": "Mending Waters"
      },
      {
        "id": "earth_shock",
        "name": "Earthen Jolt"
      },
      {
        "id": "lightning_shield",
        "name": "Thunder Ward"
      },
      {
        "id": "flame_shock",
        "name": "Cinder Jolt"
      }
    ],
    "abilities": [
      {
        "id": "lightning_bolt",
        "name": "Arc Bolt"
      },
      {
        "id": "rockbiter_weapon",
        "name": "Stonebound Weapon"
      },
      {
        "id": "healing_wave",
        "name": "Mending Waters"
      },
      {
        "id": "earth_shock",
        "name": "Earthen Jolt"
      },
      {
        "id": "lightning_shield",
        "name": "Thunder Ward"
      },
      {
        "id": "flame_shock",
        "name": "Cinder Jolt"
      },
      {
        "id": "flametongue_weapon",
        "name": "Pyrebrand Weapon"
      },
      {
        "id": "frost_shock",
        "name": "Rime Jolt"
      },
      {
        "id": "frostbrand_weapon",
        "name": "Rimebound Weapon"
      },
      {
        "id": "ghost_wolf",
        "name": "Shadewolf"
      },
      {
        "id": "stormstrike",
        "name": "Ancestral Strike"
      },
      {
        "id": "earthquake",
        "name": "Earthquake"
      }
    ],
    "model": "player_shaman",
    "tint": "#6f8fc9",
    "still": "/guide-stills/player_shaman__6f8fc9.webp"
  },
  {
    "id": "mage",
    "color": "#69ccf0",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "arcane",
        "name": "Aethermancy",
        "role": "dps",
        "signature": "arcane_missiles"
      },
      {
        "id": "fire",
        "name": "Pyromancy",
        "role": "dps",
        "signature": "scorch"
      },
      {
        "id": "frost",
        "name": "Cryomancy",
        "role": "dps",
        "signature": "ice_barrier"
      }
    ],
    "signatureAbilities": [
      {
        "id": "fireball",
        "name": "Cinderbolt"
      },
      {
        "id": "frost_armor",
        "name": "Hoarfrost Mantle"
      },
      {
        "id": "arcane_intellect",
        "name": "Aether Insight"
      },
      {
        "id": "frostbolt",
        "name": "Rimelance"
      },
      {
        "id": "conjure_water",
        "name": "Waterbind"
      },
      {
        "id": "conjure_food",
        "name": "Breadbind"
      }
    ],
    "abilities": [
      {
        "id": "fireball",
        "name": "Cinderbolt"
      },
      {
        "id": "frost_armor",
        "name": "Hoarfrost Mantle"
      },
      {
        "id": "arcane_intellect",
        "name": "Aether Insight"
      },
      {
        "id": "frostbolt",
        "name": "Rimelance"
      },
      {
        "id": "conjure_water",
        "name": "Waterbind"
      },
      {
        "id": "conjure_food",
        "name": "Breadbind"
      },
      {
        "id": "fire_blast",
        "name": "Cinderfall"
      },
      {
        "id": "arcane_missiles",
        "name": "Aether Darts"
      },
      {
        "id": "polymorph",
        "name": "Bewitch"
      },
      {
        "id": "frost_nova",
        "name": "Icebind"
      },
      {
        "id": "arcane_explosion",
        "name": "Aetherburst"
      },
      {
        "id": "scorch",
        "name": "Scald"
      },
      {
        "id": "ice_barrier",
        "name": "Frostveil"
      },
      {
        "id": "pyroblast",
        "name": "Pyrelance"
      },
      {
        "id": "flamestrike",
        "name": "Flamestrike"
      }
    ],
    "model": "player_mage",
    "still": "/guide-stills/player_mage.webp"
  },
  {
    "id": "warlock",
    "color": "#9482c9",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "affliction",
        "name": "Hexcraft",
        "role": "dps",
        "signature": "drain_life"
      },
      {
        "id": "demonology",
        "name": "Pactbound",
        "role": "dps",
        "signature": "demon_skin"
      },
      {
        "id": "destruction",
        "name": "Ruination",
        "role": "dps",
        "signature": "shadowburn"
      }
    ],
    "signatureAbilities": [
      {
        "id": "shadow_bolt",
        "name": "Gloom Bolt"
      },
      {
        "id": "summon_imp",
        "name": "Summon Emberkin"
      },
      {
        "id": "demon_skin",
        "name": "Fiendhide"
      },
      {
        "id": "immolate",
        "name": "Burning Pact"
      },
      {
        "id": "corruption",
        "name": "Blackrot"
      },
      {
        "id": "life_tap",
        "name": "Hard Bargain"
      }
    ],
    "abilities": [
      {
        "id": "shadow_bolt",
        "name": "Gloom Bolt"
      },
      {
        "id": "summon_imp",
        "name": "Summon Emberkin"
      },
      {
        "id": "demon_skin",
        "name": "Fiendhide"
      },
      {
        "id": "immolate",
        "name": "Burning Pact"
      },
      {
        "id": "corruption",
        "name": "Blackrot"
      },
      {
        "id": "life_tap",
        "name": "Hard Bargain"
      },
      {
        "id": "summon_voidwalker",
        "name": "Summon Gloomshade"
      },
      {
        "id": "curse_of_agony",
        "name": "Hex of Anguish"
      },
      {
        "id": "drain_life",
        "name": "Consume"
      },
      {
        "id": "fear",
        "name": "Harrow"
      },
      {
        "id": "searing_pain",
        "name": "Sear"
      },
      {
        "id": "shadowburn",
        "name": "Duskfire"
      },
      {
        "id": "summon_succubus",
        "name": "Summon Duskborn"
      },
      {
        "id": "summon_felhunter",
        "name": "Summon Spellhound"
      },
      {
        "id": "summon_felguard",
        "name": "Summon Warfiend"
      },
      {
        "id": "summon_infernal",
        "name": "Summon Pyre Colossus"
      },
      {
        "id": "summon_doomguard",
        "name": "Summon Wraithborn"
      },
      {
        "id": "rain_of_fire",
        "name": "Rain of Fire"
      }
    ],
    "model": "player_warlock",
    "tint": "#8d5fd3",
    "still": "/guide-stills/player_warlock__8d5fd3.webp"
  },
  {
    "id": "druid",
    "color": "#ff7d0a",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "balance",
        "name": "Moongrove",
        "role": "dps",
        "signature": "starfire"
      },
      {
        "id": "feral",
        "name": "Wildfang",
        "role": "tank",
        "signature": "bear_form"
      },
      {
        "id": "restoration",
        "name": "Groveheart",
        "role": "healer",
        "signature": "regrowth"
      }
    ],
    "signatureAbilities": [
      {
        "id": "wrath",
        "name": "Wildbolt"
      },
      {
        "id": "healing_touch",
        "name": "Wildmend"
      },
      {
        "id": "mark_of_the_wild",
        "name": "Wildward"
      },
      {
        "id": "moonfire",
        "name": "Lunar Tempest"
      },
      {
        "id": "rejuvenation",
        "name": "Wildbloom"
      },
      {
        "id": "thorns",
        "name": "Briarguard"
      }
    ],
    "abilities": [
      {
        "id": "wrath",
        "name": "Wildbolt"
      },
      {
        "id": "healing_touch",
        "name": "Wildmend"
      },
      {
        "id": "mark_of_the_wild",
        "name": "Wildward"
      },
      {
        "id": "moonfire",
        "name": "Lunar Tempest"
      },
      {
        "id": "rejuvenation",
        "name": "Wildbloom"
      },
      {
        "id": "thorns",
        "name": "Briarguard"
      },
      {
        "id": "entangling_roots",
        "name": "Gripping Roots"
      },
      {
        "id": "bear_form",
        "name": "Bruin Form"
      },
      {
        "id": "bear_charge",
        "name": "Bruin Rush"
      },
      {
        "id": "maul",
        "name": "Bonecrush"
      },
      {
        "id": "growl",
        "name": "Menace"
      },
      {
        "id": "demoralizing_roar",
        "name": "Craven Roar"
      },
      {
        "id": "cat_form",
        "name": "Wolf Form"
      },
      {
        "id": "prowl",
        "name": "Stalk"
      },
      {
        "id": "rake",
        "name": "Flense"
      },
      {
        "id": "claw",
        "name": "Claw"
      },
      {
        "id": "regrowth",
        "name": "Second Bloom"
      },
      {
        "id": "ferocious_bite",
        "name": "Gorebite"
      },
      {
        "id": "barkskin",
        "name": "Oakhide"
      },
      {
        "id": "swipe",
        "name": "Sweeping Claws"
      },
      {
        "id": "starfire",
        "name": "Skyfall"
      },
      {
        "id": "travel_form",
        "name": "Fleet Form"
      },
      {
        "id": "enrage",
        "name": "Stoke"
      },
      {
        "id": "bash",
        "name": "Concuss"
      },
      {
        "id": "faerie_fire",
        "name": "Witchlight"
      },
      {
        "id": "hibernate",
        "name": "Slumber"
      },
      {
        "id": "dash",
        "name": "Dash"
      },
      {
        "id": "pounce",
        "name": "Slinkstrike"
      },
      {
        "id": "insect_swarm",
        "name": "Stinging Swarm"
      },
      {
        "id": "tigers_fury",
        "name": "Wolfsblood"
      },
      {
        "id": "rip",
        "name": "Rip"
      },
      {
        "id": "hurricane",
        "name": "Hurricane"
      }
    ],
    "model": "player_druid",
    "still": "/guide-stills/player_druid.webp"
  }
];

export const GUIDE_ZONES: GuideZoneInfo[] = [
  {
    "id": "eastbrook_vale",
    "name": "Eastbrook Vale",
    "min": 1,
    "max": 7,
    "biome": "vale",
    "hub": "Eastbrook",
    "pois": [
      "Eastbrook",
      "Wolf Run",
      "Boar Meadow",
      "Mirror Lake",
      "Sableweb",
      "Copper Dig",
      "Bandit Camp",
      "Fallen Chapel",
      "Reliquary Hill",
      "Brightwood Glade",
      "The Sowfield"
    ],
    "welcome": "Find Marshal Redbrook in town — he has work for you.",
    "families": [
      "beast",
      "spider",
      "mudfin",
      "burrower",
      "humanoid",
      "undead"
    ]
  },
  {
    "id": "mirefen_marsh",
    "name": "Mirefen Marsh",
    "min": 6,
    "max": 13,
    "biome": "marsh",
    "hub": "Fenbridge",
    "pois": [
      "Fenbridge",
      "Prowler Reeds",
      "Deepfen Shallows",
      "Widow Thicket",
      "Drowned Chapel",
      "Troll Mounds",
      "Gravecaller Encampment",
      "The Sunken Bastion"
    ],
    "welcome": "Report to Warden Fenwick at the Fenbridge gate.",
    "families": [
      "beast",
      "spider",
      "mudfin",
      "humanoid",
      "troll",
      "undead"
    ]
  },
  {
    "id": "thornpeak_heights",
    "name": "Thornpeak Heights",
    "min": 13,
    "max": 20,
    "biome": "peaks",
    "hub": "Highwatch",
    "pois": [
      "Highwatch",
      "Stalker Ridge",
      "Deeprock Burrows",
      "Ogre Foothills",
      "Drogmar's War-Camp",
      "Stormcrag",
      "The Glimmermere",
      "Wyrmcult Tents",
      "Revenant Fields",
      "Gravewyrm Sanctum"
    ],
    "welcome": "Captain Thessaly holds the wall at Highwatch — barely.",
    "families": [
      "beast",
      "mudfin",
      "burrower",
      "humanoid",
      "ogre",
      "undead",
      "elemental",
      "dragonkin"
    ]
  }
];

export const GUIDE_DUNGEONS: GuideDungeon[] = [
  {
    "id": "hollow_crypt",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 7,
    "max": 10,
    "name": "The Hollow Crypt"
  },
  {
    "id": "sunken_bastion",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 12,
    "max": 13,
    "name": "The Sunken Bastion"
  },
  {
    "id": "drowned_temple",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 16,
    "max": 18,
    "name": "The Drowned Temple"
  },
  {
    "id": "gravewyrm_sanctum",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 19,
    "max": 20,
    "name": "Gravewyrm Sanctum"
  },
  {
    "id": "raid",
    "isRaid": true,
    "suggestedPlayers": 10,
    "min": 20,
    "max": 20
  }
];

export const GUIDE_WARLOCK_PETS: GuideWarlockPet[] = [
  {
    "id": "emberkin",
    "name": "Emberkin",
    "model": "mob_demon",
    "tint": "#ff7a2a",
    "still": "/guide-stills/mob_demon__ff7a2a.webp"
  },
  {
    "id": "gloomshade",
    "name": "Gloomshade",
    "model": "mob_demon",
    "tint": "#3a3a6e",
    "still": "/guide-stills/mob_demon__3a3a6e.webp"
  },
  {
    "id": "duskborn",
    "name": "Duskborn",
    "model": "mob_demon",
    "tint": "#c6469b",
    "still": "/guide-stills/mob_demon__c6469b.webp"
  },
  {
    "id": "spellhound",
    "name": "Spellhound",
    "model": "mob_demonalt",
    "tint": "#4a7d4a",
    "still": "/guide-stills/mob_demonalt__4a7d4a.webp"
  },
  {
    "id": "warfiend",
    "name": "Warfiend",
    "model": "mob_demonalt",
    "tint": "#6e5a2a",
    "still": "/guide-stills/mob_demonalt__6e5a2a.webp"
  },
  {
    "id": "pyre_colossus",
    "name": "Pyre Colossus",
    "model": "mob_demonalt",
    "tint": "#d24a2a",
    "still": "/guide-stills/mob_demonalt__d24a2a.webp"
  },
  {
    "id": "wraithborn",
    "name": "Wraithborn",
    "model": "mob_demonalt",
    "tint": "#7a3a8e",
    "still": "/guide-stills/mob_demonalt__7a3a8e.webp"
  }
];

export const GUIDE_DRUID_FORMS: GuideDruidForm[] = [
  {
    "id": "form_bear",
    "model": "form_bear",
    "tint": "#5a4030",
    "still": "/guide-stills/form_bear__5a4030.webp"
  },
  {
    "id": "form_cat",
    "model": "form_cat",
    "tint": "#d08b45",
    "still": "/guide-stills/form_cat__d08b45.webp"
  },
  {
    "id": "form_travel",
    "model": "form_travel",
    "still": "/guide-stills/form_travel.webp"
  }
];

export const GUIDE_FAMILIES: GuideFamily[] = [
  {
    "family": "beast",
    "creatures": [
      {
        "name": "Forest Wolf",
        "min": 1,
        "max": 2,
        "rare": false,
        "templateId": "forest_wolf",
        "model": "mob_wolf",
        "tint": "#7f8c8d",
        "still": "/guide-stills/mob_wolf__7f8c8d.webp"
      },
      {
        "name": "Wild Boar",
        "min": 2,
        "max": 3,
        "rare": false,
        "templateId": "wild_boar",
        "model": "mob_boar",
        "tint": "#935116",
        "still": "/guide-stills/mob_boar__935116.webp"
      },
      {
        "name": "Old Greyjaw",
        "min": 4,
        "max": 4,
        "rare": true,
        "templateId": "old_greyjaw",
        "model": "greyjaw",
        "still": "/guide-stills/greyjaw.webp"
      },
      {
        "name": "Mire Prowler",
        "min": 7,
        "max": 8,
        "rare": false,
        "templateId": "mire_prowler",
        "model": "mob_wolf",
        "tint": "#4d5656",
        "still": "/guide-stills/mob_wolf__4d5656.webp"
      },
      {
        "name": "Bog Bloat",
        "min": 9,
        "max": 11,
        "rare": false,
        "templateId": "bog_bloat",
        "model": "mob_murloc",
        "tint": "#6b8e23",
        "still": "/guide-stills/mob_murloc__6b8e23.webp"
      },
      {
        "name": "Ridge Stalker",
        "min": 13,
        "max": 14,
        "rare": false,
        "templateId": "ridge_stalker",
        "model": "mob_wolf",
        "tint": "#8c8270",
        "still": "/guide-stills/mob_wolf__8c8270.webp"
      }
    ]
  },
  {
    "family": "spider",
    "creatures": [
      {
        "name": "Sableweb Lurker",
        "min": 2,
        "max": 4,
        "rare": false,
        "templateId": "webwood_spider",
        "model": "mob_spider",
        "tint": "#4a235a",
        "still": "/guide-stills/mob_spider__4a235a.webp"
      },
      {
        "name": "Mirefen Widow",
        "min": 8,
        "max": 10,
        "rare": false,
        "templateId": "mire_widow",
        "model": "mob_spider",
        "tint": "#283747",
        "still": "/guide-stills/mob_spider__283747.webp"
      }
    ]
  },
  {
    "family": "mudfin",
    "creatures": [
      {
        "name": "Mudfin Skulker",
        "min": 3,
        "max": 5,
        "rare": false,
        "templateId": "mudfin_murloc",
        "model": "mob_murloc",
        "tint": "#52be80",
        "still": "/guide-stills/mob_murloc__52be80.webp"
      },
      {
        "name": "Deepfen Snapper",
        "min": 8,
        "max": 9,
        "rare": false,
        "templateId": "deepfen_murloc",
        "model": "mob_murloc",
        "tint": "#45b39d",
        "still": "/guide-stills/mob_murloc__45b39d.webp"
      },
      {
        "name": "Glimmermere Wader",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "glimmermere_wader",
        "model": "mob_murloc",
        "tint": "#8fb6c4",
        "still": "/guide-stills/mob_murloc__8fb6c4.webp"
      }
    ]
  },
  {
    "family": "burrower",
    "creatures": [
      {
        "name": "Deeprock Digger",
        "min": 4,
        "max": 6,
        "rare": false,
        "templateId": "tunnel_rat",
        "model": "mob_kobold",
        "tint": "#9c640c",
        "still": "/guide-stills/mob_kobold__9c640c.webp"
      },
      {
        "name": "Deeprock Tunneler",
        "min": 14,
        "max": 15,
        "rare": false,
        "templateId": "deeprock_kobold",
        "model": "mob_kobold",
        "tint": "#9c7a3c",
        "still": "/guide-stills/mob_kobold__9c7a3c.webp"
      }
    ]
  },
  {
    "family": "humanoid",
    "creatures": [
      {
        "name": "Vale Bandit",
        "min": 3,
        "max": 5,
        "rare": false,
        "templateId": "vale_bandit",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Gravecaller Cultist",
        "min": 10,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_cultist",
        "model": "mob_dark_caster",
        "tint": "#6c3483",
        "still": "/guide-stills/mob_dark_caster__6c3483.webp"
      },
      {
        "name": "Gravecaller Mender",
        "min": 11,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_mender",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Gravecaller Summoner",
        "min": 11,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_summoner",
        "model": "mob_dark_caster",
        "tint": "#884ea0",
        "still": "/guide-stills/mob_dark_caster__884ea0.webp"
      },
      {
        "name": "Wyrmcult Zealot",
        "min": 17,
        "max": 19,
        "rare": false,
        "templateId": "wyrmcult_zealot",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Wyrmcult Necromancer",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "wyrmcult_necromancer",
        "model": "mob_dark_caster",
        "tint": "#533566",
        "still": "/guide-stills/mob_dark_caster__533566.webp"
      }
    ]
  },
  {
    "family": "troll",
    "creatures": [
      {
        "name": "Mirefen Troll",
        "min": 10,
        "max": 12,
        "rare": false,
        "templateId": "fen_troll",
        "model": "mob_troll",
        "tint": "#229954",
        "still": "/guide-stills/mob_troll__229954.webp"
      },
      {
        "name": "Grubjaw the Glutton",
        "min": 12,
        "max": 12,
        "rare": true,
        "templateId": "grubjaw",
        "model": "mob_troll",
        "tint": "#145a32",
        "still": "/guide-stills/mob_troll__145a32.webp"
      }
    ]
  },
  {
    "family": "ogre",
    "creatures": [
      {
        "name": "Thornpeak Ogre",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "thornpeak_ogre",
        "model": "mob_ogre",
        "tint": "#9e7b53",
        "still": "/guide-stills/mob_ogre__9e7b53.webp"
      }
    ]
  },
  {
    "family": "undead",
    "creatures": [
      {
        "name": "Restless Bones",
        "min": 5,
        "max": 7,
        "rare": false,
        "templateId": "restless_bones",
        "model": "skel_minion",
        "tint": "#d5dbdb",
        "still": "/guide-stills/skel_minion__d5dbdb.webp"
      },
      {
        "name": "Drowned Dead",
        "min": 9,
        "max": 11,
        "rare": false,
        "templateId": "drowned_dead",
        "model": "skel_minion",
        "tint": "#7fb3d5",
        "still": "/guide-stills/skel_minion__7fb3d5.webp"
      },
      {
        "name": "Drowned Votary",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "drowned_votary",
        "model": "skel_minion",
        "tint": "#6c8f8a",
        "still": "/guide-stills/skel_minion__6c8f8a.webp"
      },
      {
        "name": "Boneclad Revenant",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "boneclad_revenant",
        "model": "skel_warrior",
        "tint": "#cacfd2",
        "still": "/guide-stills/skel_warrior__cacfd2.webp"
      }
    ]
  },
  {
    "family": "elemental",
    "creatures": [
      {
        "name": "Stormcrag Elemental",
        "min": 17,
        "max": 18,
        "rare": false,
        "templateId": "stormcrag_elemental",
        "model": "mob_elemental",
        "tint": "#5dade2",
        "still": "/guide-stills/mob_elemental__5dade2.webp"
      },
      {
        "name": "Shardlord Kazzix",
        "min": 18,
        "max": 18,
        "rare": true,
        "templateId": "shardlord_kazzix",
        "model": "mob_elemental",
        "tint": "#aed6f1",
        "still": "/guide-stills/mob_elemental__aed6f1.webp"
      }
    ]
  },
  {
    "family": "dragonkin",
    "creatures": [
      {
        "name": "Sethrael the Palecoil",
        "min": 16,
        "max": 16,
        "rare": true,
        "templateId": "sethrael_palecoil",
        "model": "mob_dragonkin",
        "tint": "#bcd2e6",
        "still": "/guide-stills/mob_dragonkin__bcd2e6.webp"
      }
    ]
  }
];

export const GUIDE_DELVES: GuideDelve[] = [
  {
    "id": "collapsed_reliquary",
    "name": "The Collapsed Reliquary",
    "theme": "crypt",
    "minLevel": 7,
    "suggestedPlayers": 2,
    "keeper": {
      "name": "Brother Halven",
      "title": "Reliquary Keeper"
    },
    "companion": {
      "name": "Acolyte Tessa",
      "role": "healer"
    },
    "tiers": [
      "Normal",
      "Heroic"
    ],
    "affixes": [
      "Restless Graves",
      "Bad Air",
      "Candleblind",
      "Grave Tax",
      "Unstable Roof",
      "Cult Remnants"
    ]
  },
  {
    "id": "drowned_litany",
    "name": "The Drowned Litany",
    "theme": "ruin",
    "minLevel": 12,
    "suggestedPlayers": 2,
    "keeper": {
      "name": "Brother Halven",
      "title": "Reliquary Keeper"
    },
    "companion": {
      "name": "Edda Reedhand",
      "role": "healer"
    },
    "tiers": [
      "Normal",
      "Heroic"
    ],
    "affixes": [
      "High Water",
      "Lively Choir",
      "Belligerent Dead"
    ]
  }
];

export const GUIDE_DEEDS: GuideDeed[] = [
  {
    "id": "prog_first_steps",
    "name": "First Steps",
    "category": "progression",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/prog_first_steps.webp"
  },
  {
    "id": "prog_finding_your_feet",
    "name": "Finding Your Feet",
    "category": "progression",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/prog_finding_your_feet.webp"
  },
  {
    "id": "prog_double_digits",
    "name": "Double Digits",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/prog_double_digits.webp"
  },
  {
    "id": "prog_the_long_middle",
    "name": "The Long Middle",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/prog_the_long_middle.webp"
  },
  {
    "id": "prog_level_cap",
    "name": "The View From the Top",
    "category": "progression",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/prog_level_cap.webp"
  },
  {
    "id": "prog_well_rested",
    "name": "Well Rested",
    "category": "progression",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/prog_well_rested.webp"
  },
  {
    "id": "prog_talented",
    "name": "A Point Well Spent",
    "category": "progression",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/prog_talented.webp"
  },
  {
    "id": "prog_specialized",
    "name": "Declaration of Intent",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/prog_specialized.webp"
  },
  {
    "id": "prog_deep_roots",
    "name": "Deep Roots",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/prog_deep_roots.webp"
  },
  {
    "id": "prog_full_build",
    "name": "The Full Eleven",
    "category": "progression",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/prog_full_build.webp"
  },
  {
    "id": "prog_veteran",
    "name": "Veteran",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "rewardTitle": "Veteran",
    "crest": "/ui/deeds/prog_veteran.webp"
  },
  {
    "id": "prog_champion",
    "name": "Champion",
    "category": "progression",
    "renown": 25,
    "feat": false,
    "rewardTitle": "Champion",
    "crest": "/ui/deeds/prog_champion.webp"
  },
  {
    "id": "prog_paragon",
    "name": "Paragon",
    "category": "progression",
    "renown": 25,
    "feat": false,
    "rewardTitle": "Paragon",
    "crest": "/ui/deeds/prog_paragon.webp"
  },
  {
    "id": "prog_mythic",
    "name": "Mythic",
    "category": "progression",
    "renown": 50,
    "feat": false,
    "rewardTitle": "Mythic",
    "crest": "/ui/deeds/prog_mythic.webp"
  },
  {
    "id": "prog_eternal",
    "name": "Eternal",
    "category": "progression",
    "renown": 50,
    "feat": false,
    "rewardTitle": "Eternal",
    "crest": "/ui/deeds/prog_eternal.webp"
  },
  {
    "id": "prog_prestige",
    "name": "Begin Again",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/prog_prestige.webp"
  },
  {
    "id": "prog_prestige_5",
    "name": "Old Habits",
    "category": "progression",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/prog_prestige_5.webp"
  },
  {
    "id": "prog_prestige_10",
    "name": "Perpetual Motion",
    "category": "progression",
    "renown": 50,
    "feat": false,
    "rewardBorder": true,
    "crest": "/ui/deeds/prog_prestige_10.webp"
  },
  {
    "id": "prog_first_harvest",
    "name": "Fruits of the Field",
    "category": "progression",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/prog_first_harvest.webp"
  },
  {
    "id": "prog_mining_100",
    "name": "Ore in the Blood",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/prog_mining_100.webp"
  },
  {
    "id": "prog_logging_100",
    "name": "Heartwood Hewer",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/prog_logging_100.webp"
  },
  {
    "id": "prog_herbalism_100",
    "name": "Master of the Meadow",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/prog_herbalism_100.webp"
  },
  {
    "id": "prog_master_gatherer",
    "name": "Master Gatherer",
    "category": "progression",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/prog_master_gatherer.webp"
  },
  {
    "id": "prog_first_craft",
    "name": "Made By Hand",
    "category": "progression",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/prog_first_craft.webp"
  },
  {
    "id": "prog_craft_specialist",
    "name": "Trade Secrets",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/prog_craft_specialist.webp"
  },
  {
    "id": "prog_around_the_ring",
    "name": "Around the Ring",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/prog_around_the_ring.webp"
  },
  {
    "id": "cmb_first_blood",
    "name": "First Blood",
    "category": "combat",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/cmb_first_blood.webp"
  },
  {
    "id": "cmb_slayer",
    "name": "Slayer",
    "category": "combat",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/cmb_slayer.webp"
  },
  {
    "id": "cmb_legion_of_one",
    "name": "Legion of One",
    "category": "combat",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/cmb_legion_of_one.webp"
  },
  {
    "id": "cmb_heavy_hitter",
    "name": "Heavy Hitter",
    "category": "combat",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/cmb_heavy_hitter.webp"
  },
  {
    "id": "cmb_critical_eye",
    "name": "Critical Eye",
    "category": "combat",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/cmb_critical_eye.webp"
  },
  {
    "id": "cmb_giantslayer",
    "name": "Giantslayer",
    "category": "combat",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/cmb_giantslayer.webp"
  },
  {
    "id": "cmb_first_fall",
    "name": "Dust Yourself Off",
    "category": "combat",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/cmb_first_fall.webp"
  },
  {
    "id": "dgn_hollow_crypt",
    "name": "Cryptbreaker",
    "category": "dungeon",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/dgn_hollow_crypt.webp"
  },
  {
    "id": "dgn_sunken_bastion",
    "name": "Fogbinder Unbound",
    "category": "dungeon",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/dgn_sunken_bastion.webp"
  },
  {
    "id": "dgn_drowned_temple",
    "name": "Drowning the Moon",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_drowned_temple.webp"
  },
  {
    "id": "dgn_gravewyrm_sanctum",
    "name": "The Wyrm Below",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_gravewyrm_sanctum.webp"
  },
  {
    "id": "dgn_hollow_crypt_heroic",
    "name": "Heroic: The Hollow Crypt",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_hollow_crypt_heroic.webp"
  },
  {
    "id": "dgn_sunken_bastion_heroic",
    "name": "Heroic: The Sunken Bastion",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_sunken_bastion_heroic.webp"
  },
  {
    "id": "dgn_drowned_temple_heroic",
    "name": "Heroic: The Drowned Temple",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_drowned_temple_heroic.webp"
  },
  {
    "id": "dgn_gravewyrm_sanctum_heroic",
    "name": "Heroic: Gravewyrm Sanctum",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_gravewyrm_sanctum_heroic.webp"
  },
  {
    "id": "dgn_nythraxis",
    "name": "Scourge No More",
    "category": "dungeon",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/dgn_nythraxis.webp"
  },
  {
    "id": "dgn_nythraxis_heroic",
    "name": "Heroic: Scourge No More",
    "category": "dungeon",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/dgn_nythraxis_heroic.webp"
  },
  {
    "id": "dgn_thornpeak_rounds",
    "name": "Making the Rounds",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_thornpeak_rounds.webp"
  },
  {
    "id": "dgn_deepward",
    "name": "Deepward",
    "category": "dungeon",
    "renown": 50,
    "feat": false,
    "rewardBorder": true,
    "crest": "/ui/deeds/dgn_deepward.webp"
  },
  {
    "id": "dgn_mark_circuit",
    "name": "The Full Circuit",
    "category": "dungeon",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/dgn_mark_circuit.webp"
  },
  {
    "id": "dgn_boss_clears_50",
    "name": "Fifty Doors Down",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_boss_clears_50.webp"
  },
  {
    "id": "dgn_morthen_flawless",
    "name": "No Bones About It",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_morthen_flawless.webp"
  },
  {
    "id": "dgn_morthen_trio",
    "name": "Three Against the Grave",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_morthen_trio.webp"
  },
  {
    "id": "dgn_olen_arc",
    "name": "Sidestep the Reaper",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_olen_arc.webp"
  },
  {
    "id": "dgn_vael_thralls",
    "name": "No Thrall of Mine",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_vael_thralls.webp"
  },
  {
    "id": "dgn_ysolei_moonspawn",
    "name": "Every Last Moonspawn",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_ysolei_moonspawn.webp"
  },
  {
    "id": "dgn_ysolei_flawless",
    "name": "Dry Eyes",
    "category": "dungeon",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/dgn_ysolei_flawless.webp"
  },
  {
    "id": "dgn_velkhar_bonewalkers",
    "name": "Stay Buried",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_velkhar_bonewalkers.webp"
  },
  {
    "id": "dgn_korzul_flawless",
    "name": "Wyrmfeller",
    "category": "dungeon",
    "renown": 25,
    "feat": false,
    "rewardTitle": "Wyrmfeller",
    "crest": "/ui/deeds/dgn_korzul_flawless.webp"
  },
  {
    "id": "dgn_sanctum_speed",
    "name": "Sanctum Sprint",
    "category": "dungeon",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/dgn_sanctum_speed.webp"
  },
  {
    "id": "dgn_nythraxis_gravebreaker",
    "name": "Kneel to No King",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_nythraxis_gravebreaker.webp"
  },
  {
    "id": "dgn_nythraxis_wardens",
    "name": "Keepers of the Wardstones",
    "category": "dungeon",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/dgn_nythraxis_wardens.webp"
  },
  {
    "id": "dgn_nythraxis_deathless",
    "name": "None More Deathless",
    "category": "dungeon",
    "renown": 50,
    "feat": false,
    "rewardTitle": "the Deathless",
    "crest": "/ui/deeds/dgn_nythraxis_deathless.webp"
  },
  {
    "id": "cmb_thunzharr",
    "name": "The Mountain Fell",
    "category": "combat",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/cmb_thunzharr.webp"
  },
  {
    "id": "cmb_thunzharr_unbroken",
    "name": "Peakbreaker",
    "category": "combat",
    "renown": 25,
    "feat": false,
    "rewardTitle": "Peakbreaker",
    "crest": "/ui/deeds/cmb_thunzharr_unbroken.webp"
  },
  {
    "id": "cmb_thunzharr_ten",
    "name": "A Habit of Mountains",
    "category": "combat",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/cmb_thunzharr_ten.webp"
  },
  {
    "id": "dlv_reliquary",
    "name": "Reliquary Runner",
    "category": "delve",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/dlv_reliquary.webp"
  },
  {
    "id": "dlv_reliquary_heroic",
    "name": "Heroic: The Collapsed Reliquary",
    "category": "delve",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dlv_reliquary_heroic.webp"
  },
  {
    "id": "dlv_litany",
    "name": "Hush the Litany",
    "category": "delve",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/dlv_litany.webp"
  },
  {
    "id": "dlv_litany_heroic",
    "name": "Heroic: The Drowned Litany",
    "category": "delve",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dlv_litany_heroic.webp"
  },
  {
    "id": "dlv_lore_journal",
    "name": "Marginalia",
    "category": "delve",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dlv_lore_journal.webp"
  },
  {
    "id": "dlv_companion_max",
    "name": "A Friend in the Deep",
    "category": "delve",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dlv_companion_max.webp"
  },
  {
    "id": "dlv_companions_both",
    "name": "Both Lanterns Lit",
    "category": "delve",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/dlv_companions_both.webp"
  },
  {
    "id": "dlv_clears_50",
    "name": "Fifty Fathoms",
    "category": "delve",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dlv_clears_50.webp"
  },
  {
    "id": "dlv_solo_heroic",
    "name": "Two's a Crowd",
    "category": "delve",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/dlv_solo_heroic.webp"
  },
  {
    "id": "dlv_tumbler_premium",
    "name": "The Tumbler's Path, Mastered",
    "category": "delve",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/dlv_tumbler_premium.webp"
  },
  {
    "id": "dlv_rite_flawless",
    "name": "Word-Perfect",
    "category": "delve",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/dlv_rite_flawless.webp"
  },
  {
    "id": "dlv_varric_ringers",
    "name": "The Bells Fall Silent",
    "category": "delve",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dlv_varric_ringers.webp"
  },
  {
    "id": "dlv_nhalia_bells",
    "name": "Bellstiller",
    "category": "delve",
    "renown": 25,
    "feat": false,
    "rewardTitle": "Bellstiller",
    "crest": "/ui/deeds/dlv_nhalia_bells.webp"
  },
  {
    "id": "chr_vale_chapter_i",
    "name": "Vale Chronicle, Chapter I",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_vale_chapter_i.webp"
  },
  {
    "id": "chr_vale_chapter_ii",
    "name": "Vale Chronicle, Chapter II",
    "category": "chronicle",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/chr_vale_chapter_ii.webp"
  },
  {
    "id": "chr_vale_chapter_iii",
    "name": "Chronicle of the Vale",
    "category": "chronicle",
    "renown": 25,
    "feat": false,
    "rewardTitle": "of the Vale",
    "crest": "/ui/deeds/chr_vale_chapter_iii.webp"
  },
  {
    "id": "chr_vale_gatherer",
    "name": "Living off the Land",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_vale_gatherer.webp"
  },
  {
    "id": "chr_vale_first_cast",
    "name": "Something in Mirror Lake",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_vale_first_cast.webp"
  },
  {
    "id": "chr_vale_packbreaker",
    "name": "Packbreaker",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_vale_packbreaker.webp"
  },
  {
    "id": "chr_vale_cup_debut",
    "name": "Copper Pail Contender",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_vale_cup_debut.webp"
  },
  {
    "id": "chr_vale_rares",
    "name": "Terrors of the Vale",
    "category": "chronicle",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/chr_vale_rares.webp"
  },
  {
    "id": "chr_marsh_chapter_i",
    "name": "Marsh Chronicle, Chapter I",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_marsh_chapter_i.webp"
  },
  {
    "id": "chr_marsh_chapter_ii",
    "name": "Marsh Chronicle, Chapter II",
    "category": "chronicle",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/chr_marsh_chapter_ii.webp"
  },
  {
    "id": "chr_marsh_chapter_iii",
    "name": "Chronicle of the Mirefen",
    "category": "chronicle",
    "renown": 25,
    "feat": false,
    "rewardTitle": "of the Mirefen",
    "crest": "/ui/deeds/chr_marsh_chapter_iii.webp"
  },
  {
    "id": "chr_marsh_gatherer",
    "name": "Fenbridge Foraging",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_marsh_gatherer.webp"
  },
  {
    "id": "chr_marsh_unburst",
    "name": "Do Not Stand in the Spores",
    "category": "chronicle",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/chr_marsh_unburst.webp"
  },
  {
    "id": "chr_marsh_hush_the_mending",
    "name": "Silence the Mending",
    "category": "chronicle",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/chr_marsh_hush_the_mending.webp"
  },
  {
    "id": "chr_marsh_rares",
    "name": "Named in the Mist",
    "category": "chronicle",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/chr_marsh_rares.webp"
  },
  {
    "id": "chr_peaks_chapter_i",
    "name": "Peaks Chronicle, Chapter I",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_peaks_chapter_i.webp"
  },
  {
    "id": "chr_peaks_chapter_ii",
    "name": "Peaks Chronicle, Chapter II",
    "category": "chronicle",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/chr_peaks_chapter_ii.webp"
  },
  {
    "id": "chr_peaks_chapter_iii",
    "name": "Chronicle of Thornpeak",
    "category": "chronicle",
    "renown": 50,
    "feat": false,
    "rewardTitle": "of Thornpeak",
    "crest": "/ui/deeds/chr_peaks_chapter_iii.webp"
  },
  {
    "id": "chr_peaks_sparring",
    "name": "Wall Drills",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_peaks_sparring.webp"
  },
  {
    "id": "chr_peaks_glimmer_cast",
    "name": "Cold Water, Colder Light",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_peaks_glimmer_cast.webp"
  },
  {
    "id": "chr_peaks_moongate",
    "name": "Through the Cold Gate",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_peaks_moongate.webp"
  },
  {
    "id": "chr_peaks_waking_witness",
    "name": "The Mountain That Walks",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_peaks_waking_witness.webp"
  },
  {
    "id": "chr_peaks_rares",
    "name": "Names Cut into the Crag",
    "category": "chronicle",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/chr_peaks_rares.webp"
  },
  {
    "id": "col_discovery_25",
    "name": "Packrat",
    "category": "collection",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/col_discovery_25.webp"
  },
  {
    "id": "col_discovery_75",
    "name": "Magpie",
    "category": "collection",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/col_discovery_75.webp"
  },
  {
    "id": "col_discovery_150",
    "name": "Cabinet of Curiosities",
    "category": "collection",
    "renown": 25,
    "feat": false,
    "rewardTitle": "the Curator",
    "crest": "/ui/deeds/col_discovery_150.webp"
  },
  {
    "id": "col_discovery_250",
    "name": "The Grand Catalogue",
    "category": "collection",
    "renown": 50,
    "feat": false,
    "rewardBorder": true,
    "crest": "/ui/deeds/col_discovery_250.webp"
  },
  {
    "id": "col_first_rare",
    "name": "Something Blue",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_first_rare.webp"
  },
  {
    "id": "col_first_epic",
    "name": "Born to the Purple",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_first_epic.webp"
  },
  {
    "id": "col_first_legendary",
    "name": "Orange You Lucky",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_first_legendary.webp"
  },
  {
    "id": "col_set_vale_arcanist",
    "name": "Vale Arcanist's Regalia",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_set_vale_arcanist.webp"
  },
  {
    "id": "col_set_boundstone_vanguard",
    "name": "Boundstone Vanguard",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_set_boundstone_vanguard.webp"
  },
  {
    "id": "col_set_greyjaw_stalker",
    "name": "Greyjaw Stalker's Kit",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_set_greyjaw_stalker.webp"
  },
  {
    "id": "col_set_deathlord",
    "name": "Barrowlord Battlegear",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_set_deathlord.webp"
  },
  {
    "id": "col_set_wyrmshadow",
    "name": "Nightfang Vestments",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_set_wyrmshadow.webp"
  },
  {
    "id": "col_set_necromancers",
    "name": "Mournweave Raiment",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_set_necromancers.webp"
  },
  {
    "id": "col_set_crownforged",
    "name": "Bonewrought Regalia",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_set_crownforged.webp"
  },
  {
    "id": "col_set_nighttalon",
    "name": "Direfang Pelt",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_set_nighttalon.webp"
  },
  {
    "id": "col_set_soulflame",
    "name": "Wraithfire Regalia",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_set_soulflame.webp"
  },
  {
    "id": "col_set_stormcallers",
    "name": "Galecall Vestments",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_set_stormcallers.webp"
  },
  {
    "id": "col_seven_regalia",
    "name": "The Sevenfold Wardrobe",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "rewardTitle": "the Resplendent",
    "crest": "/ui/deeds/col_seven_regalia.webp"
  },
  {
    "id": "col_true_colors",
    "name": "True Colors",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_true_colors.webp"
  },
  {
    "id": "col_all_slots",
    "name": "Dressed to the Elevens",
    "category": "collection",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/col_all_slots.webp"
  },
  {
    "id": "col_quartermaster_buyout",
    "name": "Preferred Customer",
    "category": "collection",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/col_quartermaster_buyout.webp"
  },
  {
    "id": "col_glimmerfin",
    "name": "Glimmer of Hope",
    "category": "collection",
    "renown": 0,
    "feat": false,
    "crest": "/ui/deeds/col_glimmerfin.webp"
  },
  {
    "id": "col_full_creel",
    "name": "Full Creel",
    "category": "collection",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/col_full_creel.webp"
  },
  {
    "id": "col_junk_drawer",
    "name": "The Junk Drawer",
    "category": "collection",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/col_junk_drawer.webp"
  },
  {
    "id": "pvp_arena_first_match",
    "name": "Sand in Your Boots",
    "category": "pvp",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/pvp_arena_first_match.webp"
  },
  {
    "id": "pvp_arena_first_win",
    "name": "The Crowd Roars",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_arena_first_win.webp"
  },
  {
    "id": "pvp_arena_1v1_1600",
    "name": "Coliseum Contender",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_arena_1v1_1600.webp"
  },
  {
    "id": "pvp_arena_1v1_1750",
    "name": "Coliseum Rival",
    "category": "pvp",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/pvp_arena_1v1_1750.webp"
  },
  {
    "id": "pvp_arena_1v1_1900",
    "name": "Gladiator",
    "category": "pvp",
    "renown": 50,
    "feat": false,
    "rewardTitle": "Gladiator",
    "crest": "/ui/deeds/pvp_arena_1v1_1900.webp"
  },
  {
    "id": "pvp_arena_2v2_1600",
    "name": "Two Strong",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_arena_2v2_1600.webp"
  },
  {
    "id": "pvp_arena_2v2_1750",
    "name": "Fearsome Twosome",
    "category": "pvp",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/pvp_arena_2v2_1750.webp"
  },
  {
    "id": "pvp_arena_2v2_1900",
    "name": "Perfect Partnership",
    "category": "pvp",
    "renown": 50,
    "feat": false,
    "crest": "/ui/deeds/pvp_arena_2v2_1900.webp"
  },
  {
    "id": "pvp_duel_first_win",
    "name": "Settle It Outside",
    "category": "pvp",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/pvp_duel_first_win.webp"
  },
  {
    "id": "pvp_duel_grace",
    "name": "A Lesson in Humility",
    "category": "pvp",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/pvp_duel_grace.webp"
  },
  {
    "id": "pvp_vcup_first_match",
    "name": "Boots on the Pitch",
    "category": "pvp",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/pvp_vcup_first_match.webp"
  },
  {
    "id": "pvp_vcup_first_win",
    "name": "First Silverware",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_vcup_first_win.webp"
  },
  {
    "id": "pvp_vcup_wins_10",
    "name": "Seasoned Boarballer",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_vcup_wins_10.webp"
  },
  {
    "id": "pvp_vcup_wins_25",
    "name": "Boarball Legend",
    "category": "pvp",
    "renown": 25,
    "feat": false,
    "rewardTitle": "Boarball Legend",
    "crest": "/ui/deeds/pvp_vcup_wins_25.webp"
  },
  {
    "id": "pvp_vcup_first_goal",
    "name": "Off the Mark",
    "category": "pvp",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/pvp_vcup_first_goal.webp"
  },
  {
    "id": "pvp_vcup_hat_trick",
    "name": "Hat Trick Hero",
    "category": "pvp",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/pvp_vcup_hat_trick.webp"
  },
  {
    "id": "pvp_vcup_golden_goal",
    "name": "Golden Moment",
    "category": "pvp",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/pvp_vcup_golden_goal.webp"
  },
  {
    "id": "pvp_vcup_first_save",
    "name": "Safe Hands",
    "category": "pvp",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/pvp_vcup_first_save.webp"
  },
  {
    "id": "pvp_vcup_clean_sheet",
    "name": "Nothing Gets Past Me",
    "category": "pvp",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/pvp_vcup_clean_sheet.webp"
  },
  {
    "id": "pvp_vcup_guild_win",
    "name": "For the Banner",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_vcup_guild_win.webp"
  },
  {
    "id": "pvp_fiesta_first_bout",
    "name": "Party Crasher",
    "category": "pvp",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/pvp_fiesta_first_bout.webp"
  },
  {
    "id": "pvp_fiesta_first_win",
    "name": "Life of the Fiesta",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_fiesta_first_win.webp"
  },
  {
    "id": "pvp_fiesta_double",
    "name": "Double Trouble",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_fiesta_double.webp"
  },
  {
    "id": "pvp_fiesta_shutdown",
    "name": "Party Pooper",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_fiesta_shutdown.webp"
  },
  {
    "id": "pvp_fiesta_full_build",
    "name": "Dressed for the Occasion",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_fiesta_full_build.webp"
  },
  {
    "id": "pvp_fiesta_powerups",
    "name": "One of Everything",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_fiesta_powerups.webp"
  },
  {
    "id": "pvp_fiesta_five_kills",
    "name": "Carrying the Party",
    "category": "pvp",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/pvp_fiesta_five_kills.webp"
  },
  {
    "id": "soc_first_party",
    "name": "Better Together",
    "category": "social",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/soc_first_party.webp"
  },
  {
    "id": "soc_full_house",
    "name": "Full House",
    "category": "social",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/soc_full_house.webp"
  },
  {
    "id": "soc_guild_joined",
    "name": "Under One Banner",
    "category": "social",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/soc_guild_joined.webp"
  },
  {
    "id": "soc_guild_founded",
    "name": "Founder's Quill",
    "category": "social",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/soc_guild_founded.webp"
  },
  {
    "id": "soc_first_trade",
    "name": "A Fair Exchange",
    "category": "social",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/soc_first_trade.webp"
  },
  {
    "id": "soc_first_sale",
    "name": "Open for Business",
    "category": "social",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/soc_first_sale.webp"
  },
  {
    "id": "soc_steady_custom",
    "name": "Steady Custom",
    "category": "social",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/soc_steady_custom.webp"
  },
  {
    "id": "soc_market_magnate",
    "name": "Market Magnate",
    "category": "social",
    "renown": 25,
    "feat": false,
    "rewardTitle": "Magnate",
    "crest": "/ui/deeds/soc_market_magnate.webp"
  },
  {
    "id": "soc_by_ravens_wing",
    "name": "By Raven's Wing",
    "category": "social",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/soc_by_ravens_wing.webp"
  },
  {
    "id": "soc_room_for_more",
    "name": "Room for More",
    "category": "social",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/soc_room_for_more.webp"
  },
  {
    "id": "soc_gilded_strongbox",
    "name": "The Gilded Strongbox",
    "category": "social",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/soc_gilded_strongbox.webp"
  },
  {
    "id": "soc_meet_bursar",
    "name": "In Fernando We Trust",
    "category": "social",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/soc_meet_bursar.webp"
  },
  {
    "id": "soc_pocket_money",
    "name": "Pocket Money",
    "category": "social",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/soc_pocket_money.webp"
  },
  {
    "id": "soc_heavy_purse",
    "name": "Heavy Purse",
    "category": "social",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/soc_heavy_purse.webp"
  },
  {
    "id": "soc_wyrms_hoard",
    "name": "A Wyrm's Hoard",
    "category": "social",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/soc_wyrms_hoard.webp"
  },
  {
    "id": "soc_civic_duty",
    "name": "Civic Duty",
    "category": "social",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/soc_civic_duty.webp"
  },
  {
    "id": "exp_long_road_north",
    "name": "The Long Road North",
    "category": "exploration",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/exp_long_road_north.webp"
  },
  {
    "id": "exp_vale_wayfarer",
    "name": "Wayfarer of the Vale",
    "category": "exploration",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/exp_vale_wayfarer.webp"
  },
  {
    "id": "exp_marsh_wayfarer",
    "name": "Wayfarer of the Marsh",
    "category": "exploration",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/exp_marsh_wayfarer.webp"
  },
  {
    "id": "exp_peaks_wayfarer",
    "name": "Wayfarer of the Heights",
    "category": "exploration",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/exp_peaks_wayfarer.webp"
  },
  {
    "id": "exp_world_traveler",
    "name": "World Traveler",
    "category": "exploration",
    "renown": 25,
    "feat": false,
    "rewardTitle": "the Wayfarer",
    "crest": "/ui/deeds/exp_world_traveler.webp"
  },
  {
    "id": "exp_something_shiny",
    "name": "Something Shiny",
    "category": "exploration",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/exp_something_shiny.webp"
  },
  {
    "id": "exp_first_ore",
    "name": "Strike the Earth",
    "category": "exploration",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/exp_first_ore.webp"
  },
  {
    "id": "exp_first_timber",
    "name": "Timber!",
    "category": "exploration",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/exp_first_timber.webp"
  },
  {
    "id": "exp_first_herb",
    "name": "Green Thumb",
    "category": "exploration",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/exp_first_herb.webp"
  },
  {
    "id": "feat_era_cap",
    "name": "Child of the First Era",
    "category": "feat",
    "renown": 0,
    "feat": true,
    "crest": "/ui/deeds/feat_era_cap.webp"
  },
  {
    "id": "feat_book_complete",
    "name": "The Whole Book",
    "category": "feat",
    "renown": 0,
    "feat": true,
    "crest": "/ui/deeds/feat_book_complete.webp"
  },
  {
    "id": "feat_brightwood_relic",
    "name": "Brightwood Remembered",
    "category": "feat",
    "renown": 0,
    "feat": true,
    "crest": "/ui/deeds/feat_brightwood_relic.webp"
  },
  {
    "id": "prog_crown_below",
    "name": "The Crown Below",
    "category": "progression",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/prog_crown_below.webp"
  },
  {
    "id": "prog_mere_at_rest",
    "name": "The Mere at Rest",
    "category": "progression",
    "renown": 25,
    "feat": false,
    "crest": "/ui/deeds/prog_mere_at_rest.webp"
  },
  {
    "id": "prog_callused_hands",
    "name": "Callused Hands",
    "category": "progression",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/prog_callused_hands.webp"
  },
  {
    "id": "prog_tools_of_the_trade",
    "name": "Tools of the Trade",
    "category": "progression",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/prog_tools_of_the_trade.webp"
  },
  {
    "id": "dgn_nythraxis_crypt",
    "name": "What the Crypt Kept",
    "category": "dungeon",
    "renown": 10,
    "feat": false,
    "crest": "/ui/deeds/dgn_nythraxis_crypt.webp"
  },
  {
    "id": "chr_marsh_first_cast",
    "name": "Eels in the Reeds",
    "category": "chronicle",
    "renown": 5,
    "feat": false,
    "crest": "/ui/deeds/chr_marsh_first_cast.webp"
  }
];

export const GUIDE_MODELS: Record<string, GuideModelSpec> = {
  "player_warrior": {
    "url": "models/chars/players/knight.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Knight_Helmet",
      "Knight_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/sword_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_paladin": {
    "url": "models/chars/players/paladin.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/axe_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_hunter": {
    "url": "models/chars/players/ranger.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/crossbow_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_rogue": {
    "url": "models/chars/players/rogue.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Rogue_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.l"
      }
    ]
  },
  "player_priest": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.5
  },
  "player_shaman": {
    "url": "models/chars/players/barbarian.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Barbarian_BearHat"
    ],
    "attach": [
      {
        "url": "models/weapons/axe_1handed.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.4
  },
  "player_mage": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Mage_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_warlock": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [],
    "attach": [
      {
        "url": "models/weapons/wand.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/spellbook_open.glb",
        "bone": "handslot.l",
        "gripRef": "Spellbook_open"
      }
    ],
    "tintStrength": 0.45
  },
  "player_druid": {
    "url": "models/chars/players/druid.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "form_bear": {
    "url": "models/creatures/yetialt.glb",
    "idle": "Idle",
    "height": 2.4,
    "tintStrength": 0.55
  },
  "form_cat": {
    "url": "models/creatures/wolf_basic.glb",
    "idle": "Idle",
    "height": 1.6,
    "tintStrength": 0.35
  },
  "form_travel": {
    "url": "models/creatures/chicken_cow.glb",
    "idle": "Idle",
    "height": 2.3
  },
  "mob_demon": {
    "url": "models/creatures/demonalt.glb",
    "idle": "Idle",
    "height": 1.8,
    "tintStrength": 0.5
  },
  "mob_demonalt": {
    "url": "models/creatures/demonalt.glb",
    "idle": "Idle",
    "height": 2.1,
    "tintStrength": 0.35
  },
  "mob_wolf": {
    "url": "models/creatures/wolf_basic.glb",
    "idle": "Idle",
    "height": 1.6,
    "tintStrength": 0.35
  },
  "greyjaw": {
    "url": "models/creatures/greyjaw.glb",
    "idle": "Idle",
    "height": 2.2
  },
  "mob_boar": {
    "url": "models/creatures/wild_boar.glb",
    "idle": "Idle1",
    "height": 1.45,
    "tintStrength": 0.4
  },
  "mob_spider": {
    "url": "models/creatures/spider.glb",
    "idle": "Spider_Idle",
    "height": 1.4,
    "tintStrength": 0.35
  },
  "mob_murloc": {
    "url": "models/creatures/frog.glb",
    "idle": "Idle",
    "height": 1.7,
    "tintStrength": 0.45
  },
  "mob_kobold": {
    "url": "models/creatures/goblin.glb",
    "idle": "Idle",
    "height": 2.1,
    "tintStrength": 0.2
  },
  "mob_bandit": {
    "url": "models/chars/players/rogue_hooded.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.l"
      }
    ],
    "tintStrength": 0.3
  },
  "skel_minion": {
    "url": "models/chars/enemies/skeleton_minion.glb",
    "idle": "Idle_Combat",
    "height": 2.5,
    "tintStrength": 0.25
  },
  "mob_troll": {
    "url": "models/creatures/orc.glb",
    "idle": "Idle",
    "height": 2.4,
    "tintStrength": 0.12
  },
  "mob_dark_caster": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Mage_Hat"
    ],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.5
  },
  "mob_ogre": {
    "url": "models/creatures/giant.glb",
    "idle": "Idle",
    "height": 2.8,
    "tintStrength": 0.2
  },
  "mob_elemental": {
    "url": "models/creatures/golelingevolved.glb",
    "idle": "Flying_Idle",
    "height": 2.2,
    "hover": 0.3,
    "tintStrength": 0.4
  },
  "skel_warrior": {
    "url": "models/chars/enemies/skeleton_warrior.glb",
    "idle": "Idle_Combat",
    "height": 2.5,
    "tintStrength": 0.25
  },
  "mob_dragonkin": {
    "url": "models/creatures/dragonevolved.glb",
    "idle": "Flying_Idle",
    "height": 2.4,
    "hover": 0.25,
    "tintStrength": 0.2
  }
};
